<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2017_2018Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2017-2018'],
            ['name' => '2017-2018 Set']
        );

        $alumni = [
            [
                'name' => '1',
                'email' => null,
                'phones' => null,
                'department' => 'AWE DEBBIE',
                'gender' => null,
                'state' => null,
                'address' => '7067837014',
            ],
            [
                'name' => '2',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8034738357',
            ],
            [
                'name' => '3',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8101107993',
            ],
            [
                'name' => '4',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8064128443',
            ],
            [
                'name' => '5',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8167144636',
            ],
            [
                'name' => '6',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8160881677',
            ],
            [
                'name' => '7',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8101346534',
            ],
            [
                'name' => '8',
                'email' => null, 
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8165910406',
            ],
            [
                'name' => '9',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8166612620',
            ],
            [
                'name' => '10',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8153708801',
            ],
            [
                'name' => '11',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8139123445',
            ],
            [
                'name' => '12',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7067500992',
            ],
            [
                'name' => '13',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8066054445',
            ],
            [
                'name' => '14',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8132981726',
            ],
            [
                'name' => '15',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7032451725',
            ],
            [
                'name' => '16',
                'email' => null,
                'phones' => null,
                'department' => 'ARIYO SEUN',
                'gender' => null,
                'state' => null,
                'address' => '8135770365',
            ],
            [
                'name' => '17',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7031892381',
            ],
            [
                'name' => '18',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '9032223878',
            ],
            [
                'name' => '19',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7035471308',
            ],
            [
                'name' => '20',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8168561404',
            ],
            [
                'name' => '21',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8105977882',
            ],
            [
                'name' => '22',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8181926597',
            ],
            [
                'name' => '23',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8063871422',
            ],
            [
                'name' => '24',
                'email' => null,
                'phones' => null,
                'department' => 'AJAO IFE',
                'gender' => null,
                'state' => null,
                'address' => '8149809643',
            ],
            [
                'name' => '25',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7054628599',
            ],
            [
                'name' => '26',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8102348349',
            ],
            [
                'name' => '27',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8107151566',
            ],
            [
                'name' => '28',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8186257510',
            ],
            [
                'name' => '29',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8167158489',
            ],
            [
                'name' => '30',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8140398140',
            ],
            [
                'name' => '31',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8130252922',
            ],
            [
                'name' => '32',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8102564922',
            ],
            [
                'name' => '33',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8160994624',
            ],
            [
                'name' => '34',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7069263676',
            ],
            [
                'name' => '35',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8165260157',
            ],
            [
                'name' => '36',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7062743233',
            ],
            [
                'name' => '37',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '907553349',
            ],
            [
                'name' => '38',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '9030909165',
            ],
            [
                'name' => '39',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8138376172',
            ],
            [
                'name' => '40',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '9038003379',
            ],
            [
                'name' => '41',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8144283420',
            ],
            [
                'name' => '42',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8137530625',
            ],
            [
                'name' => '43',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8168492234',
            ],
            [
                'name' => '44',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8167137610',
            ],
            [
                'name' => '45',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8036792735',
            ],
            [
                'name' => '46',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8100921167',
            ],
            [
                'name' => '47',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8164340150',
            ],
            [
                'name' => '48',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8137534728',
            ],
            [
                'name' => '49',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8067681248',
            ],
            [
                'name' => '50',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8185183321',
            ],
            [
                'name' => '51',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8162345840',
            ],
            [
                'name' => '52',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8124435655',
            ],
            [
                'name' => '53',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8165539137',
            ],
            [
                'name' => '54',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8139331357',
            ],
            [
                'name' => '55',
                'email' => null,
                'phones' => null,
                'department' => 'AROBOTO',
                'gender' => null,
                'state' => null,
                'address' => '8132586404',
            ],
            [
                'name' => '56',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8135556767',
            ],
            [
                'name' => '57',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8108282853',
            ],
            [
                'name' => '58',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8164024225',
            ],
            [
                'name' => '59',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7068540454',
            ],
            [
                'name' => '60',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7033855537',
            ],
            [
                'name' => '61',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8167967805',
            ],
            [
                'name' => '62',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8136481236',
            ],
            [
                'name' => '63',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8114573440',
            ],
            [
                'name' => '64',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8131909011',
            ],
            [
                'name' => '65',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7032779031',
            ],
            [
                'name' => '66',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8069553378',
            ],
            [
                'name' => '67',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8133783310',
            ],
            [
                'name' => '68',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8138231123',
            ],
            [
                'name' => '69',
                'email' => null,
                'phones' => null,
                'department' => 'ONU AMOS',
                'gender' => null,
                'state' => null,
                'address' => '8134708486',
            ],
            [
                'name' => '70',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7069298798',
            ],
            [
                'name' => '71',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '08161121 956',
            ],
            [
                'name' => '72',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8109796203',
            ],
            [
                'name' => '73',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7036639218',
            ],
            [
                'name' => '74',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8106377097',
            ],
            [
                'name' => '75',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8099078019',
            ],
            [
                'name' => '76',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8066293047',
            ],
            [
                'name' => '77',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '810885441',
            ],
            [
                'name' => '78',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8060786885',
            ],
            [
                'name' => '79',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8147973819',
            ],
            [
                'name' => '80',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8138329470',
            ],
            [
                'name' => '81',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8139376055',
            ],
            [
                'name' => '82',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8165101596',
            ],
            [
                'name' => '83',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8166565784',
            ],
            [
                'name' => '84',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7038321143',
            ],
            [
                'name' => '85',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7010367284',
            ],
            [
                'name' => '86',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7033928359',
            ],
            [
                'name' => '87',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '9035836132',
            ],
            [
                'name' => '88',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7061936970',
            ],
            [
                'name' => '89',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8060666770',
            ],
            [
                'name' => '90',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8089667925',
            ],
            [
                'name' => '91',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8160533254',
            ],
            [
                'name' => '92',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8100073891',
            ],
            [
                'name' => '93',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8163187417',
            ],
            [
                'name' => '94',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7061965609',
            ],
            [
                'name' => '95',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8106140211',
            ],
            [
                'name' => '96',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8166236731',
            ],
            [
                'name' => '97',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8164227928',
            ],
            [
                'name' => '98',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8139220590',
            ],
            [
                'name' => '99',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8101668692',
            ],
            [
                'name' => '100',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8171037337',
            ],
            [
                'name' => '101',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8138957964',
            ],
            [
                'name' => '102',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7062735169',
            ],
            [
                'name' => '103',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8063460198',
            ],
            [
                'name' => '104',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '9055637107',
            ],
            [
                'name' => '105',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '9039120089',
            ],
            [
                'name' => '106',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8161564659',
            ],
            [
                'name' => '107',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8139520479',
            ],
            [
                'name' => '108',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8173194949',
            ],
            [
                'name' => '109',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7068502700',
            ],
            [
                'name' => '110',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8163576049',
            ],
            [
                'name' => '111',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8139122555',
            ],
            [
                'name' => '112',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8138393068',
            ],
            [
                'name' => '113',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8166924356',
            ],
            [
                'name' => '114',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '9030707561',
            ],
            [
                'name' => '115',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8062845148',
            ],
            [
                'name' => '116',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8140070524',
            ],
            [
                'name' => '117',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8163060676',
            ],
            [
                'name' => '118',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8104884510',
            ],
            [
                'name' => '119',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8066190308',
            ],
            [
                'name' => '120',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8134276692',
            ],
            [
                'name' => '121',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8167831975',
            ],
            [
                'name' => '122',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8133890921',
            ],
            [
                'name' => '123',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8169429839',
            ],
            [
                'name' => '124',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7036369685',
            ],
            [
                'name' => '125',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8060056935',
            ],
            [
                'name' => '126',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8082901564',
            ],
            [
                'name' => '127',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8132702356',
            ],
            [
                'name' => '128',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8090742214',
            ],
            [
                'name' => '129',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8100518502',
            ],
            [
                'name' => '130',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '9053267542',
            ],
            [
                'name' => '131',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8132962361',
            ],
            [
                'name' => '132',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8161999422',
            ],
            [
                'name' => '133',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '9067252265',
            ],
            [
                'name' => '134',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8165906106',
            ],
            [
                'name' => '135',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7030736633',
            ],
            [
                'name' => '136',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8162010074',
            ],
            [
                'name' => '137',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7036767319',
            ],
            [
                'name' => '138',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8102810229',
            ],
            [
                'name' => '139',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8163439521',
            ],
            [
                'name' => '140',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7060737565',
            ],
            [
                'name' => '141',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8068257936',
            ],
            [
                'name' => '142',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8060482404',
            ],
            [
                'name' => '143',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8142517846',
            ],
            [
                'name' => '144',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7033157618',
            ],
            [
                'name' => '145',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8143863689',
            ],
            [
                'name' => '146',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '903034477',
            ],
            [
                'name' => '147',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8094782096',
            ],
            [
                'name' => '148',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8033780394',
            ],
            [
                'name' => '149',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8169560365',
            ],
            [
                'name' => '150',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7069119847',
            ],
            [
                'name' => '151',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8164706626',
            ],
            [
                'name' => '152',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8098901284',
            ],
            [
                'name' => '153',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7068992952',
            ],
            [
                'name' => '154',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8137834079',
            ],
            [
                'name' => '155',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7032309229',
            ],
            [
                'name' => '156',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8177544287',
            ],
            [
                'name' => '157',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7062373862',
            ],
            [
                'name' => '158',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7052616079',
            ],
            [
                'name' => '159',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8122395570',
            ],
            [
                'name' => '160',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8132873922',
            ],
            [
                'name' => '161',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8034284482',
            ],
            [
                'name' => '162',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8166013009',
            ],
            [
                'name' => '163',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8093506625',
            ],
            [
                'name' => '164',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8167173641',
            ],
            [
                'name' => '165',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8149512420',
            ],
            [
                'name' => '166',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8062723471',
            ],
            [
                'name' => '167',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8162319146',
            ],
            [
                'name' => '168',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '7069248190',
            ],
            [
                'name' => '169',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8072139290',
            ],
            [
                'name' => '170',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '9038516909',
            ],
            [
                'name' => '171',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8102768532',
            ],
            [
                'name' => '172',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8103831802',
            ],
            [
                'name' => '173',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8106095060',
            ],
            [
                'name' => '174',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => '8177544287',
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
