<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2008_2009Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2008-2009'],
            ['name' => '2008-2009 Set']
        );

        $alumni = [
            [
                'name' => 'ABE GBEMISOLA',
                'email' => null,
                'phones' => null,
                'department' => 'MCB',
                'gender' => 'F',
                'birth_date' => '2000-01-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABEGUNDE KAYODE',
                'email' => null,
                'phones' => ['08062301328'],
                'department' => 'URP',
                'gender' => 'M',
                'birth_date' => '2000-12-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABEGUNDE O. TEMITOPE',
                'email' => null,
                'phones' => ['08032245117'],
                'department' => 'AGE',
                'gender' => 'M',
                'birth_date' => '2000-05-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABIODUN MODUPE GRACE',
                'email' => null,
                'phones' => ['08033575180'],
                'department' => 'MCB',
                'gender' => 'F',
                'birth_date' => '2000-12-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABOLUDE A. TAYO',
                'email' => null,
                'phones' => ['08052398631'],
                'department' => 'AGE',
                'gender' => 'M',
                'birth_date' => '2000-10-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBARA ADETUNJI S.',
                'email' => null,
                'phones' => ['08038518352'],
                'department' => 'IDD',
                'gender' => 'M',
                'birth_date' => '2000-07-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDOKUN OLUWASEYI',
                'email' => null,
                'phones' => ['08035592650', '08080890541'],
                'department' => 'MME',
                'gender' => null,
                'birth_date' => '2000-11-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEJOBI ADENIYI',
                'email' => null,
                'phones' => ['08034446784'],
                'department' => 'URP',
                'gender' => 'M',
                'birth_date' => '2000-09-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEJUBE O. STEVEN',
                'email' => null,
                'phones' => ['08060073300'],
                'department' => 'FWT',
                'gender' => 'M',
                'birth_date' => '2000-02-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKANYE IDOWU',
                'email' => null,
                'phones' => ['08077939722'],
                'department' => null,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKANYE P. ADEBISI',
                'email' => null,
                'phones' => ['08062737897', '08027573690'],
                'department' => 'ARC.',
                'gender' => 'M',
                'birth_date' => '2000-04-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELEKE SAMUEL ADEWALE',
                'email' => null,
                'phones' => ['08032399898', '08072096166'],
                'department' => 'ESM',
                'gender' => 'M',
                'birth_date' => '2000-07-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEMUWAGUN COMFORT',
                'email' => null,
                'phones' => ['08036042484'],
                'department' => 'ESM',
                'gender' => 'F',
                'birth_date' => '2000-02-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIYI OLUWATOYIN D.',
                'email' => null,
                'phones' => ['08030888291'],
                'department' => 'CSC',
                'gender' => 'F',
                'birth_date' => '2000-12-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEOLU TAIWO',
                'email' => null,
                'phones' => ['08024249569'],
                'department' => 'BCH',
                'gender' => 'F',
                'birth_date' => '2000-04-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEUSI OPEYEMI',
                'email' => null,
                'phones' => ['08062204693'],
                'department' => 'AEE',
                'gender' => 'F',
                'birth_date' => '2000-09-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEUSI SUNDAY',
                'email' => null,
                'phones' => ['08061678485'],
                'department' => 'CVE',
                'gender' => 'M',
                'birth_date' => '2000-04-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYINA AYOMIDE',
                'email' => null,
                'phones' => ['08062271451'],
                'department' => 'BIO',
                'gender' => 'F',
                'birth_date' => '2000-05-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFE BOLA A.',
                'email' => null,
                'phones' => ['07037837501'],
                'department' => 'MCB',
                'gender' => 'F',
                'birth_date' => '2000-03-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI DOLAPO',
                'email' => null,
                'phones' => ['08034883872'],
                'department' => 'CSC',
                'gender' => 'F',
                'birth_date' => '2000-04-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI ISSAC K.',
                'email' => null,
                'phones' => ['08026942347'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-07-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI OLALEKEN O.',
                'email' => null,
                'phones' => ['08034623952'],
                'department' => 'MNE',
                'gender' => 'M',
                'birth_date' => '2000-08-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJETOMOBI JACOB O.',
                'email' => null,
                'phones' => ['08033662091'],
                'department' => 'MNE',
                'gender' => 'M',
                'birth_date' => '2000-01-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJIMOKO YEMI',
                'email' => null,
                'phones' => ['08028379297'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-12-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBILE ADEKUNLE',
                'email' => null,
                'phones' => ['08030658483'],
                'department' => 'FST',
                'gender' => 'M',
                'birth_date' => '2000-05-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBINU BUKOLA',
                'email' => null,
                'phones' => ['07038625295'],
                'department' => 'MCB',
                'gender' => 'F',
                'birth_date' => '2000-10-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINGBOYE TEMITOPE',
                'email' => null,
                'phones' => ['08066360416'],
                'department' => 'ESM',
                'gender' => 'F',
                'birth_date' => '2000-05-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKIN-KOMOLAFE ROLAKE',
                'email' => null,
                'phones' => ['08033672783'],
                'department' => 'BCH',
                'gender' => 'F',
                'birth_date' => '2000-05-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOLA MOSES A.',
                'email' => null,
                'phones' => ['08038255937'],
                'department' => 'CVE',
                'gender' => 'M',
                'birth_date' => '2000-07-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSOROTAN DUNNI',
                'email' => null,
                'phones' => ['07031852563'],
                'department' => 'CSC',
                'gender' => 'F',
                'birth_date' => '2000-05-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINTADE PAUL',
                'email' => null,
                'phones' => ['08076057155'],
                'department' => 'IDD',
                'gender' => 'M',
                'birth_date' => '2000-04-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYEMI OLUWASEYI',
                'email' => null,
                'phones' => ['08059849292'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-08-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKOMOLEDE A. MOYO',
                'email' => null,
                'phones' => ['08034377884'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-01-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALONGE OLADIPO',
                'email' => null,
                'phones' => ['08038589616'],
                'department' => 'MME',
                'gender' => 'M',
                'birth_date' => '2000-04-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AMENAGILAWON LUCKY',
                'email' => null,
                'phones' => ['08068123362'],
                'department' => 'MEE',
                'gender' => 'M',
                'birth_date' => '2000-03-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AREMU OLUWAKEMI F.',
                'email' => null,
                'phones' => ['08084844108'],
                'department' => 'FWL',
                'gender' => 'F',
                'birth_date' => '2000-01-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASENAGUAN FIDELIS NOSA',
                'email' => null,
                'phones' => ['08069032404'],
                'department' => 'MEE',
                'gender' => 'M',
                'birth_date' => '2000-04-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ATING BASSEY F.',
                'email' => null,
                'phones' => ['08037998939'],
                'department' => 'MEE',
                'gender' => 'M',
                'birth_date' => '2000-09-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWONIYI AFOLABI P.',
                'email' => null,
                'phones' => ['08035368495'],
                'department' => 'FST',
                'gender' => 'M',
                'birth_date' => '2000-06-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOTALE ALO',
                'email' => null,
                'phones' => ['08035289288'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-03-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABALOLA O. PEACE',
                'email' => null,
                'phones' => ['08067111974', '07055394570'],
                'department' => 'BIO',
                'gender' => 'F',
                'birth_date' => '2000-11-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABALOLA OPEYEMI S.',
                'email' => null,
                'phones' => ['08067111974'],
                'department' => 'BIO',
                'gender' => 'F',
                'birth_date' => '2000-10-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BADA M. OLUWAFEMI',
                'email' => null,
                'phones' => ['08053222386'],
                'department' => 'ARC.',
                'gender' => 'M',
                'birth_date' => '2000-10-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BELLO AYODEJI',
                'email' => null,
                'phones' => ['08024799641'],
                'department' => 'CVE',
                'gender' => 'M',
                'birth_date' => '2000-08-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BONIRE OLAROTIMI O.',
                'email' => null,
                'phones' => ['08030809453'],
                'department' => 'AGE',
                'gender' => 'M',
                'birth_date' => '2000-07-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DARAMOLA OLATUNBOSUN',
                'email' => null,
                'phones' => ['08068496859'],
                'department' => 'ARC.',
                'gender' => 'M',
                'birth_date' => '2000-05-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EDADOQZOGWU GOODNESS',
                'email' => null,
                'phones' => ['08036190049'],
                'department' => 'PHY',
                'gender' => 'M',
                'birth_date' => '2000-08-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ELEGBEDE ABIODUN S.',
                'email' => null,
                'phones' => ['08025461700'],
                'department' => 'CVE',
                'gender' => 'M',
                'birth_date' => '2000-12-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ELUFOWOJU KEHINDE J.',
                'email' => null,
                'phones' => ['07038874737'],
                'department' => 'MCB',
                'gender' => null,
                'birth_date' => '2000-08-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EMOLA K. COURAGE',
                'email' => null,
                'phones' => ['08037643442'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-07-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FABIYI OLUWAGBENGA',
                'email' => null,
                'phones' => ['08022570609'],
                'department' => 'EEE',
                'gender' => 'M',
                'birth_date' => '2000-10-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAJIMITE OLAYINKA',
                'email' => null,
                'phones' => ['08029265121'],
                'department' => 'ESM',
                'gender' => 'M',
                'birth_date' => '2000-04-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALADE AYOADE',
                'email' => null,
                'phones' => ['08067219186'],
                'department' => 'CHE',
                'gender' => 'M',
                'birth_date' => '2000-11-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAPETU SEGUN AYO',
                'email' => null,
                'phones' => ['08060306201'],
                'department' => 'BIO',
                'gender' => 'M',
                'birth_date' => '2000-02-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FASAKIN A. ADEOYE',
                'email' => null,
                'phones' => ['08067515135'],
                'department' => null,
                'gender' => 'F',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FASOYI OLUWASOLA G.',
                'email' => null,
                'phones' => ['08032151784'],
                'department' => 'MET',
                'gender' => 'M',
                'birth_date' => '2000-02-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FATILE BUKOLA',
                'email' => null,
                'phones' => ['08025436073'],
                'department' => 'ARC.',
                'gender' => 'F',
                'birth_date' => '2000-06-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FATOKI ABIODUN EMMANUEL',
                'email' => null,
                'phones' => ['08034884350'],
                'department' => 'AGY',
                'gender' => null,
                'birth_date' => '2000-01-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FATORINDE SAMUEL AYO',
                'email' => null,
                'phones' => ['08066540760'],
                'department' => 'AGE',
                'gender' => 'M',
                'birth_date' => '2000-04-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAYEMIRO FOLASAYO O.',
                'email' => null,
                'phones' => ['08030412825'],
                'department' => 'URP',
                'gender' => 'M',
                'birth_date' => '2000-12-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IFEDAYO O.T',
                'email' => null,
                'phones' => ['80363911561'],
                'department' => 'CHE',
                'gender' => 'M',
                'birth_date' => '2000-04-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IKUMAPAYI OLUWASEGUN A.',
                'email' => null,
                'phones' => ['08026318582'],
                'department' => 'AEE',
                'gender' => 'M',
                'birth_date' => '2000-06-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ILESANMI OLUSEGUN',
                'email' => null,
                'phones' => ['08023644299', '08033440168'],
                'department' => 'EEE',
                'gender' => 'M',
                'birth_date' => '2000-09-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ILOBA GODSWILL',
                'email' => null,
                'phones' => ['08034224832'],
                'department' => 'AGE',
                'gender' => 'M',
                'birth_date' => '2000-12-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IMEDIEGWU EMMANUEL A.',
                'email' => null,
                'phones' => ['07032630969', '08027211202'],
                'department' => 'MEE',
                'gender' => 'M',
                'birth_date' => '2000-05-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KAYODE E.J',
                'email' => null,
                'phones' => ['08064839198'],
                'department' => 'MCB',
                'gender' => 'F',
                'birth_date' => '2000-03-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KOLAWOLE TOLULOPE',
                'email' => null,
                'phones' => ['08039214333'],
                'department' => 'MEE',
                'gender' => 'M',
                'birth_date' => '2000-02-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KOMOLAFE JULIET FISAYO',
                'email' => null,
                'phones' => ['08037994938'],
                'department' => 'MTS',
                'gender' => 'F',
                'birth_date' => '2000-03-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LADESUYI TEMILADE',
                'email' => null,
                'phones' => ['80056763676'],
                'department' => 'CSC',
                'gender' => 'F',
                'birth_date' => '2000-08-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LAWAL ADERONKE',
                'email' => null,
                'phones' => ['08064853078'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-04-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LAWAL O. BABATUNDE',
                'email' => null,
                'phones' => ['08065656461'],
                'department' => 'URP',
                'gender' => 'M',
                'birth_date' => '2000-02-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MERAYEBU SEGUN',
                'email' => null,
                'phones' => ['08027251470', '07039170757'],
                'department' => 'EEE',
                'gender' => 'M',
                'birth_date' => '2000-11-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MORAWO TOLULOPE',
                'email' => null,
                'phones' => ['08034986187'],
                'department' => 'BIO',
                'gender' => 'M',
                'birth_date' => '2000-05-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBIENWE JOYCE',
                'email' => null,
                'phones' => ['08067112371'],
                'department' => 'MET',
                'gender' => 'F',
                'birth_date' => '2000-12-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODEKUNLE A. ADEDOYIN',
                'email' => null,
                'phones' => ['08025482174'],
                'department' => 'AGE',
                'gender' => 'M',
                'birth_date' => '2000-03-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODETUNDE OLUYEMI O.',
                'email' => null,
                'phones' => ['08062508781'],
                'department' => 'CSC',
                'gender' => 'M',
                'birth_date' => '2000-07-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODEYEMI SEUN',
                'email' => null,
                'phones' => ['08038280064'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-12-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODEYEMI TOPE',
                'email' => null,
                'phones' => ['08067586444'],
                'department' => 'MTS',
                'gender' => 'M',
                'birth_date' => '2000-06-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGIDIAMA OGIHARE VICTOR',
                'email' => null,
                'phones' => ['08074624498'],
                'department' => 'MEE',
                'gender' => 'M',
                'birth_date' => '2000-11-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNBILE E. TEMITAYO',
                'email' => null,
                'phones' => ['08034979215'],
                'department' => 'APH',
                'gender' => 'F',
                'birth_date' => '2000-06-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDARE ENIOLA',
                'email' => null,
                'phones' => ['08052254063'],
                'department' => 'MNE',
                'gender' => 'M',
                'birth_date' => '2000-05-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLEYE ALABA DAMILOLA',
                'email' => null,
                'phones' => ['08062929972'],
                'department' => 'MCB',
                'gender' => 'M',
                'birth_date' => '2000-10-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLEYE TEMITOPE',
                'email' => null,
                'phones' => ['07038408031'],
                'department' => 'MCB',
                'gender' => 'F',
                'birth_date' => '2000-10-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNTIMEHIN ABIODUN S.',
                'email' => null,
                'phones' => ['08054135723', '08064463042'],
                'department' => 'ARC.',
                'gender' => 'M',
                'birth_date' => '2000-03-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNTIMEHIN TOPE',
                'email' => null,
                'phones' => ['08032432733'],
                'department' => 'MCB',
                'gender' => 'F',
                'birth_date' => '2000-03-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNYA BUSAYO A.',
                'email' => null,
                'phones' => ['08036994003', '07027408737'],
                'department' => 'CSC',
                'gender' => 'M',
                'birth_date' => '2000-06-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJIOKPUTA INNOCENT',
                'email' => null,
                'phones' => ['08059490401'],
                'department' => 'EEE',
                'gender' => 'M',
                'birth_date' => '2000-04-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO ABIOLA OPEYEMI',
                'email' => null,
                'phones' => ['08035902446'],
                'department' => 'AEE',
                'gender' => 'F',
                'birth_date' => '2000-08-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO ELIZABETH OLUWASEUN',
                'email' => null,
                'phones' => ['08032320463'],
                'department' => 'MEE',
                'gender' => 'F',
                'birth_date' => '2000-09-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO MOJISOLA C.',
                'email' => null,
                'phones' => ['08034899177'],
                'department' => 'BIO',
                'gender' => 'F',
                'birth_date' => '2000-09-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO O. HANNAH',
                'email' => null,
                'phones' => ['08026898517'],
                'department' => 'APH',
                'gender' => 'F',
                'birth_date' => '2000-03-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO OLADIPUPO',
                'email' => null,
                'phones' => ['08034935794'],
                'department' => 'PHY',
                'gender' => 'M',
                'birth_date' => '2000-01-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLABANJI DAYO',
                'email' => null,
                'phones' => ['08034200841'],
                'department' => 'CSP',
                'gender' => 'M',
                'birth_date' => '2000-02-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADEJO B.O',
                'email' => null,
                'phones' => ['08038255255'],
                'department' => 'MCB',
                'gender' => 'M',
                'birth_date' => '2000-05-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADOSU AKINOLA',
                'email' => null,
                'phones' => ['08034258142'],
                'department' => 'IDD',
                'gender' => 'M',
                'birth_date' => '2000-07-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAKUNLE A.K',
                'email' => null,
                'phones' => ['08066088163'],
                'department' => 'AEE',
                'gender' => 'F',
                'birth_date' => '2000-10-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLALEKAN BANKOLE',
                'email' => null,
                'phones' => ['08036028454'],
                'department' => 'FWT',
                'gender' => 'M',
                'birth_date' => '2000-07-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATEJU O.O',
                'email' => null,
                'phones' => ['08034985728'],
                'department' => 'MME',
                'gender' => 'M',
                'birth_date' => '2000-02-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATUNDE TOYIN',
                'email' => null,
                'phones' => ['08024062429'],
                'department' => 'ESM',
                'gender' => 'F',
                'birth_date' => '2000-05-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAWAWO VICTOR',
                'email' => null,
                'phones' => ['08035434937'],
                'department' => 'ARC.',
                'gender' => 'M',
                'birth_date' => '2000-03-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOFINSAWE B.G',
                'email' => null,
                'phones' => ['80366439795'],
                'department' => null,
                'gender' => 'F',
                'birth_date' => '2000-11-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOGUN HENRY',
                'email' => null,
                'phones' => ['08029162280'],
                'department' => 'PHY',
                'gender' => 'M',
                'birth_date' => '2000-03-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLONI GBEMI T.',
                'email' => null,
                'phones' => ['08032868545'],
                'department' => 'MEE',
                'gender' => 'M',
                'birth_date' => '2000-02-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNSOGBON OLUWASEUN',
                'email' => null,
                'phones' => ['08030724308'],
                'department' => 'BCH',
                'gender' => 'F',
                'birth_date' => '2000-07-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOYEDE OPEYEMI K.',
                'email' => null,
                'phones' => ['08035831642'],
                'department' => 'ARC.',
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUPONA KEMILOLA F.',
                'email' => null,
                'phones' => ['08033618750'],
                'department' => 'CHE',
                'gender' => 'F',
                'birth_date' => '2000-12-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOJU BLESSING R.',
                'email' => null,
                'phones' => ['08060178479'],
                'department' => 'FST',
                'gender' => 'F',
                'birth_date' => '2000-11-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOPARIOLA KUNMI',
                'email' => null,
                'phones' => ['80262399988', '0803921729'],
                'department' => 'AEE',
                'gender' => 'F',
                'birth_date' => '2000-08-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOPARIOLA MUYIWA',
                'email' => null,
                'phones' => ['08038002172'],
                'department' => 'URP',
                'gender' => 'M',
                'birth_date' => '2000-06-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTAYO OMOLOLA',
                'email' => null,
                'phones' => ['08025324072'],
                'department' => 'MET',
                'gender' => 'F',
                'birth_date' => '2000-03-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTEHINSE ADETOLA B.',
                'email' => null,
                'phones' => ['80773326424'],
                'department' => 'CHE',
                'gender' => 'M',
                'birth_date' => '2000-10-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTOLA O.D',
                'email' => null,
                'phones' => ['08060806393'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSAYANDE O. VICTORIA',
                'email' => null,
                'phones' => ['08032210661'],
                'department' => 'FWT',
                'gender' => 'F',
                'birth_date' => '2000-12-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOEYE E. SEYE',
                'email' => null,
                'phones' => ['08038664815'],
                'department' => 'MEE',
                'gender' => 'M',
                'birth_date' => '2000-01-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOLABI DOTUN',
                'email' => null,
                'phones' => ['08066649294'],
                'department' => 'FST',
                'gender' => 'M',
                'birth_date' => '2000-05-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOTADE DAMMY',
                'email' => null,
                'phones' => ['08027438347'],
                'department' => 'AEE',
                'gender' => 'M',
                'birth_date' => '2000-04-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYELEYE SUNDAY',
                'email' => null,
                'phones' => ['08035123539'],
                'department' => 'BCH',
                'gender' => 'M',
                'birth_date' => '2000-10-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYENEKAN JIDE',
                'email' => null,
                'phones' => ['08025598663'],
                'department' => 'EEE',
                'gender' => 'M',
                'birth_date' => '2000-11-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAKO KOLAWOLE D.',
                'email' => null,
                'phones' => ['08052334748'],
                'department' => 'CVE',
                'gender' => 'M',
                'birth_date' => '2000-12-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAMI OLUWAFEMI',
                'email' => null,
                'phones' => ['08027297123'],
                'department' => 'BIO',
                'gender' => 'M',
                'birth_date' => '2000-02-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SAPORE OVIRI',
                'email' => null,
                'phones' => ['08038488509'],
                'department' => 'MET',
                'gender' => 'M',
                'birth_date' => '2000-05-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SHODE OLUWASEYI',
                'email' => null,
                'phones' => ['08026694832'],
                'department' => 'ARC.',
                'gender' => 'M',
                'birth_date' => '2000-05-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SUNMONU FESTUS',
                'email' => null,
                'phones' => ['08061173738'],
                'department' => 'AGP',
                'gender' => 'M',
                'birth_date' => '2000-09-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TIEASE T.O',
                'email' => null,
                'phones' => ['08035145884'],
                'department' => 'CVE',
                'gender' => 'M',
                'birth_date' => '2000-01-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TOYE C.A',
                'email' => null,
                'phones' => ['08088097170'],
                'department' => 'MME',
                'gender' => 'M',
                'birth_date' => '2000-12-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'UNAKHUGBA GRACE',
                'email' => null,
                'phones' => ['08038479396'],
                'department' => 'CHE',
                'gender' => 'F',
                'birth_date' => '2000-07-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FADAMIRO AYOKUNLE',
                'email' => null,
                'phones' => ['08077788344'],
                'department' => 'EEE',
                'gender' => 'M',
                'birth_date' => '2000-01-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: " . count($alumni) . " records");
    }
}
