<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2005_2006Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2005-2006'],
            ['name' => '2005-2006 Set']
        );

        $alumni = [
            [
                'name' => 'ALAO M. OLAYEMI',
                'email' => null,
                'phones' => ['08054041088'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-03-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBOTOBA GBENGA',
                'email' => null,
                'phones' => ['08035678768'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-05-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MEGBUWANUN. A. A',
                'email' => null,
                'phones' => ['08029442293'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-02-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYENEYE OLABODE',
                'email' => null,
                'phones' => ['08035369018'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-11-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BANKOLE O. M',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-01-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKUNNIGA SEGUN',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-03-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINRINADE OPEYEMI',
                'email' => null,
                'phones' => ['08034397417'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-09-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ESENE E. E',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-02-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JIMOH SURAJUDEEN',
                'email' => null,
                'phones' => ['08035175590'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-11-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JAGBORO GERSHOM',
                'email' => null,
                'phones' => ['08038349738'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-09-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWODEYIN SANYA',
                'email' => null,
                'phones' => ['08037186170'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-08-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JUSTIN CHIKEZIE',
                'email' => null,
                'phones' => null,
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-05-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI MOMTUNDE',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-12-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MOMOH ALABA',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-06-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BOLARINWA BOSEDE',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-07-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAMI OLUFEMI',
                'email' => null,
                'phones' => null,
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-02-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FABOYEDE TOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-01-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAIYA TOLU',
                'email' => null,
                'phones' => ['08054150349'],
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-07-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BALOGUN TAYO',
                'email' => null,
                'phones' => null,
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-07-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OUAGBO ADESEGUNFUNMI',
                'email' => null,
                'phones' => ['08034384605'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-11-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDEJI SUNDAY',
                'email' => null,
                'phones' => null,
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-10-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESANWO B. ADEWUNMI',
                'email' => null,
                'phones' => null,
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-04-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODOFIN OLUWASEUN',
                'email' => null,
                'phones' => ['08034007112'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-11-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEPOJU MORADEKE',
                'email' => null,
                'phones' => ['08034902707'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-11-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IDOWU OYEYEMI',
                'email' => null,
                'phones' => null,
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-10-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALEJO OLAKUNLE',
                'email' => null,
                'phones' => null,
                'department_id' => 4,
                'gender' => 'M',
                'birth_date' => '2000-10-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEWUSI MICHAEL',
                'email' => null,
                'phones' => ['08054470323'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-12-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWUNMI ISAAC',
                'email' => null,
                'phones' => null,
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-10-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYETORO A. B',
                'email' => null,
                'phones' => ['08035307395'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-09-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMONIYI KOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-04-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDIPE AKKINTUNDE',
                'email' => null,
                'phones' => ['08035963873'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-04-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'THOMAS OLAROTIMI',
                'email' => null,
                'phones' => null,
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-05-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJALA YEMI',
                'email' => null,
                'phones' => null,
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-10-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LONGE MUYIWA',
                'email' => null,
                'phones' => null,
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-08-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FRANKLIN. C',
                'email' => null,
                'phones' => ['08038579079'],
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-01-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMISORE AFOLABI',
                'email' => null,
                'phones' => null,
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-09-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOTIMIRO OLUWATOSIN',
                'email' => null,
                'phones' => ['08038126521'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-10-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KUNLERE ADESOJI',
                'email' => null,
                'phones' => ['08034902014'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-04-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJO BAALE',
                'email' => null,
                'phones' => ['08035690292'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-11-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASAMU MICHAEL',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-03-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ESHO TOLA',
                'email' => null,
                'phones' => ['08033564863'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-11-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODOLE OLUGBENGA',
                'email' => null,
                'phones' => ['08034617764'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-12-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAJOMO ALABA',
                'email' => null,
                'phones' => ['08034677544'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-07-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASAFA GBENGA',
                'email' => null,
                'phones' => ['08035393846'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-07-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BANJOKO A. A',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-07-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'CHOGUDO NELSON',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-05-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABIOYE TAIWO. E',
                'email' => null,
                'phones' => ['08034347247'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-09-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJILEYE SEGUNM',
                'email' => null,
                'phones' => ['08034113375'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-02-12',
                'unit' => 'President\'s Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAMI OLUFEMI',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-07-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAWANDE OLUBUKOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => 'F',
                'birth_date' => '2000-11-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBIKI NDUDI',
                'email' => null,
                'phones' => ['08035662574'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-08-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AMODU OLUWASEGUN. V',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-02-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYINOLA ABIOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-02-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ESAN OLAYIWOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-01-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FADIMILEHIN OLAYEMI',
                'email' => null,
                'phones' => ['08028988126'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNFEMI ADEDAYO',
                'email' => null,
                'phones' => ['08030651545'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-06-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKAFOR P. C',
                'email' => null,
                'phones' => ['08043334562'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-05-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDIRAN A. TUNDE',
                'email' => null,
                'phones' => ['08036565342'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-08-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JEHREY A.',
                'email' => null,
                'phones' => ['08035623733'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-10-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI. A SUCCESS',
                'email' => null,
                'phones' => ['08034978775'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-06-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ESAN FOLAKEMI',
                'email' => null,
                'phones' => ['08035464271'],
                'department_id' => 34,
                'gender' => 'F',
                'birth_date' => '2000-06-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KAREEM DOLAPO',
                'email' => null,
                'phones' => ['08038046153'],
                'department_id' => 34,
                'gender' => 'F',
                'birth_date' => '2000-11-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ROTIBA DICKSON',
                'email' => null,
                'phones' => ['08036951219'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-09-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SANNI GABRIELLA',
                'email' => null,
                'phones' => null,
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABEGUNDE KAYODE',
                'email' => null,
                'phones' => ['08029183974'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-12-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DUROJAIYE EDWARD',
                'email' => null,
                'phones' => ['08035786392'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-01-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYINKA ADEOLA',
                'email' => null,
                'phones' => ['08035852092'],
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-07-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOWOSEGUN ADEBOLAM',
                'email' => null,
                'phones' => ['08033704059'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADAMS ADEOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => null,
                'birth_date' => '2000-06-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKANDE RASHIDAT',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-07-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: " . count($alumni) . " records");
    }
}
