<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2014_2015Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2014-2015'],
            ['name' => '2014-2015 Set']
        );

        $alumni = [
            [
                'name' => 'ADEYEMO HELEN',
                'email' => null,
                'phones' => ['08062963463'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-01-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTOSO ODUNAYO SILE',
                'email' => null,
                'phones' => ['07033735948'],
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-01-03',
                'unit' => 'Sanctuary Keeping Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALOBA MATTHEW',
                'email' => null,
                'phones' => ['07033047600'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-01-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINFOLARIN OLAWALE HENRY',
                'email' => null,
                'phones' => ['08137360157'],
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-01-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBOBOYE TAIWO S.',
                'email' => null,
                'phones' => ['07032819222'],
                'department_id' => 5,
                'gender' => 'F',
                'birth_date' => '2000-01-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADRE ODUOLA TOLUWALASE',
                'email' => null,
                'phones' => ['08135551903'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-01-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEWUMI OLUMIDE',
                'email' => null,
                'phones' => ['08163555438'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-01-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SOKOYA TEMITOPE O.',
                'email' => null,
                'phones' => ['08062916293'],
                'department_id' => 49,
                'gender' => 'F',
                'birth_date' => '2000-01-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAGBEMI DAMILARE',
                'email' => null,
                'phones' => ['07030418663'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-01-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARIGBEDE TIMILEHIN E.',
                'email' => null,
                'phones' => ['08132930847'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-01-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BANJO ADEDAYO MICHAEL',
                'email' => null,
                'phones' => ['07062441414'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-01-27',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGOROYE THOMPSON S.',
                'email' => null,
                'phones' => ['08136812258'],
                'department_id' => 35,
                'gender' => 'M',
                'birth_date' => '2000-01-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADABALE ADEMOLA T.',
                'email' => null,
                'phones' => ['07063697174'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-01-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLASUNKANMI A. OPEYEMI',
                'email' => null,
                'phones' => ['08162613753'],
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-01-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUYEMI TIMILEYIN MICHAEL',
                'email' => null,
                'phones' => ['09090882993'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-01-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKPAN ABRAHAM',
                'email' => null,
                'phones' => ['08183688518'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-02-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUYI ADEYINKA A.',
                'email' => null,
                'phones' => ['08022562500'],
                'department_id' => 49,
                'gender' => 'F',
                'birth_date' => '2000-02-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'POPOOLA OLUBUKOLA',
                'email' => null,
                'phones' => ['07061977376'],
                'department_id' => null,
                'gender' => 'F',
                'birth_date' => '2000-02-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASAFA OLUWAMAYOWA',
                'email' => null,
                'phones' => ['08160388818'],
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-02-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYEMI AKINKUNLE PAUL',
                'email' => null,
                'phones' => ['08066906437'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-02-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SONDE MARY',
                'email' => null,
                'phones' => ['07064356235'],
                'department_id' => 45,
                'gender' => 'F',
                'birth_date' => '2000-02-14',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSAWERE WINIFREDO.',
                'email' => null,
                'phones' => ['07038495334'],
                'department_id' => 32,
                'gender' => 'F',
                'birth_date' => '2000-02-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBAYO ABIMBOLA',
                'email' => null,
                'phones' => ['08136091134'],
                'department_id' => 52,
                'gender' => 'M',
                'birth_date' => '2000-02-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGORO TAIWO',
                'email' => null,
                'phones' => ['08063685885'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-02-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDARE WILLIAMS A',
                'email' => null,
                'phones' => ['08168846238'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-02-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUMI TAIWO ANTHONY',
                'email' => null,
                'phones' => ['08053778371'],
                'department_id' => 4,
                'gender' => 'M',
                'birth_date' => '2000-02-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDEJI OLUWASEYIFUNMI SARAH',
                'email' => null,
                'phones' => ['08067491716'],
                'department_id' => 38,
                'gender' => 'F',
                'birth_date' => '2000-02-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ILEVBAOJE IMONICHE',
                'email' => null,
                'phones' => ['08137510556'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-02-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DADA BLESSING O.',
                'email' => null,
                'phones' => ['08091507325'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-02-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAKARE OLANREWAJU V.',
                'email' => null,
                'phones' => ['08101802049'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-03-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALOYE ESTHER OLUWASEFUNMI',
                'email' => null,
                'phones' => ['07067809959'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-03-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI OMOLOLA OOREOFE',
                'email' => null,
                'phones' => ['07034373409'],
                'department_id' => 10,
                'gender' => 'F',
                'birth_date' => '2000-03-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEMO ATINUKE',
                'email' => null,
                'phones' => ['08139151504'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-03-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEWUSI EMMANUEL O.',
                'email' => null,
                'phones' => ['08103493750'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-03-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOGBEHIN OLOLADE O.',
                'email' => null,
                'phones' => ['08168819905'],
                'department_id' => 10,
                'gender' => 'F',
                'birth_date' => '2000-03-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKANLE OLADOTUN',
                'email' => null,
                'phones' => ['08138354528'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-03-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SOBOWALE OLANIYI',
                'email' => null,
                'phones' => ['07038899373'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-03-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAPEGBA FUNMILOLA',
                'email' => null,
                'phones' => ['08161570025'],
                'department_id' => 30,
                'gender' => 'F',
                'birth_date' => '2000-03-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADU OLUBUNMI O.',
                'email' => null,
                'phones' => ['08139484910'],
                'department_id' => 38,
                'gender' => 'F',
                'birth_date' => '2000-03-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNRO OLADIPUPO S.',
                'email' => null,
                'phones' => ['08061694927'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-03-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOPADE ADEBAYO SOLA',
                'email' => null,
                'phones' => ['07039390218'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-03-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUSANYA ADETAYO',
                'email' => null,
                'phones' => ['07061935632'],
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-03-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGBOLU BENJAMIN',
                'email' => null,
                'phones' => ['07032662092'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-03-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSIKU OLANREWAJU',
                'email' => null,
                'phones' => ['07060949661'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-03-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINDURO OMOLOLA',
                'email' => null,
                'phones' => ['07064444371'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-03-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODIA OAMEN MAXWELL',
                'email' => null,
                'phones' => ['08168431059'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-03-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEMI OPEYEMI',
                'email' => null,
                'phones' => ['07035520934'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-03-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBODE VICTOR',
                'email' => null,
                'phones' => ['08060053331'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-03-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI DAMILOLA ESTHER',
                'email' => null,
                'phones' => ['08133821032'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-03-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ELUWA IFEANYI',
                'email' => null,
                'phones' => ['08080888120'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-03-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASHIWAJU OLUFUNKE J.',
                'email' => null,
                'phones' => ['07031015679'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-03-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBANIMU AYODEJI B.',
                'email' => null,
                'phones' => ['07064393310'],
                'department_id' => 6,
                'gender' => 'M',
                'birth_date' => '2000-03-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ORESANYA ADEDAYO AYOKUNLE',
                'email' => null,
                'phones' => ['08135325303'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-03-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNNOWO OLUKAYODE TOLUWANI',
                'email' => null,
                'phones' => ['08083840470'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-03-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAGUNDOYE OLABISI',
                'email' => null,
                'phones' => ['08038990689'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-03-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI ISAIAH MIRACLE',
                'email' => null,
                'phones' => ['08163489607'],
                'department_id' => 4,
                'gender' => 'M',
                'birth_date' => '2000-04-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATUNDE OPEYEMI',
                'email' => null,
                'phones' => ['07069424890'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-04-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALO ANDREW TIMOTHY',
                'email' => null,
                'phones' => ['08038662113'],
                'department_id' => 49,
                'gender' => 'M',
                'birth_date' => '2000-04-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNTEGBE AYODEJI S.',
                'email' => null,
                'phones' => ['08165909394'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-04-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JAMES EMMANUEL',
                'email' => null,
                'phones' => ['07067760558'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-04-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOBUDE OSAYANDE BRIGHT',
                'email' => null,
                'phones' => ['08165656802'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-04-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEYE AYOTOMIDE',
                'email' => null,
                'phones' => ['08132128978'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-04-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OFOEDU GEOFFREY',
                'email' => null,
                'phones' => ['08165647728'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-04-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AZEEZ HAFSAT IDOWU',
                'email' => null,
                'phones' => ['08073236629'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-04-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSADOLOR COLLINS',
                'email' => null,
                'phones' => ['07010268269'],
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-04-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEMOLUTI ISAAC ADEGBOYEGA',
                'email' => null,
                'phones' => ['08133363857'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-04-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBISESAN OLOPADE IFEOLUWA',
                'email' => null,
                'phones' => ['07037901602'],
                'department_id' => 5,
                'gender' => 'F',
                'birth_date' => '2000-04-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'YUSUF KEHINDE',
                'email' => null,
                'phones' => ['08162482950'],
                'department_id' => 3,
                'gender' => 'F',
                'birth_date' => '2000-04-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWUMI DAMILOLA',
                'email' => null,
                'phones' => ['07039168537'],
                'department_id' => 6,
                'gender' => 'F',
                'birth_date' => '2000-04-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO AANUOLUWAPO',
                'email' => null,
                'phones' => ['08166576436'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-04-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI DAVID ABAYOMI',
                'email' => null,
                'phones' => ['08064334860'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-04-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDIJI AYOMIDE E.',
                'email' => null,
                'phones' => ['07087142133'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-04-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOPEGBA TOLUWASE',
                'email' => null,
                'phones' => ['08032741675'],
                'department_id' => 3,
                'gender' => 'M',
                'birth_date' => '2000-04-26',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JEGEDE OLAMIDE LAWRENCE',
                'email' => null,
                'phones' => ['08105162062'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-04-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYOTUNDE AYOOLA',
                'email' => null,
                'phones' => ['07033980855'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-05-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBEJOBI SEUN',
                'email' => null,
                'phones' => ['08139359239'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-05-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINLOYE PETER O.',
                'email' => null,
                'phones' => ['08138662883'],
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-05-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KOMOLAFE IBUKUNOLUWA',
                'email' => null,
                'phones' => ['07033583386'],
                'department_id' => 32,
                'gender' => 'F',
                'birth_date' => '2000-05-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBISI CLEMENT',
                'email' => null,
                'phones' => ['08067181870'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-05-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNYEMI BAYO',
                'email' => null,
                'phones' => ['08091560262'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-05-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'RAJI EMMANUEL',
                'email' => null,
                'phones' => ['08168846415'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-05-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIYI OPEYEMI O.',
                'email' => null,
                'phones' => ['08100048649'],
                'department_id' => 52,
                'gender' => 'M',
                'birth_date' => '2000-05-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNTOKUN JANET',
                'email' => null,
                'phones' => ['07067802507'],
                'department_id' => 32,
                'gender' => 'F',
                'birth_date' => '2000-05-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IWASOKUN ISAAC AKINYELE',
                'email' => null,
                'phones' => ['08102799922'],
                'department_id' => 4,
                'gender' => 'M',
                'birth_date' => '2000-05-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FANIYI MICHAEL OLAWOLE',
                'email' => null,
                'phones' => ['08026554422'],
                'department_id' => 29,
                'gender' => 'M',
                'birth_date' => '2000-05-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BANJO MOFESOLA PAUL',
                'email' => null,
                'phones' => ['08065856717'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-05-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOLOPE OLUWASEUN',
                'email' => null,
                'phones' => ['07035729644'],
                'department_id' => 35,
                'gender' => 'M',
                'birth_date' => '2000-05-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBOYE ADESOLA R.',
                'email' => null,
                'phones' => ['08133783310'],
                'department_id' => null,
                'gender' => null,
                'birth_date' => '2000-05-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOSUSI FUNMILOLA REBECCA',
                'email' => null,
                'phones' => ['08161785236'],
                'department_id' => 34,
                'gender' => 'F',
                'birth_date' => '2000-05-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAWUMI OLUWASEYI DAVID',
                'email' => null,
                'phones' => ['08164354053'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-05-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYOADE ADEMOLA O.',
                'email' => null,
                'phones' => ['07038938769'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-05-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAYEMI TOBI',
                'email' => null,
                'phones' => ['08174490816'],
                'department_id' => null,
                'gender' => null,
                'birth_date' => '2000-05-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSIDEKO OPEYEMI SAMUEL',
                'email' => null,
                'phones' => ['08101109376'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-05-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADU OLUWATIMILEHIN S.',
                'email' => null,
                'phones' => ['08066585994'],
                'department_id' => 3,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARIYO EMMANUEL O.',
                'email' => null,
                'phones' => ['07034778918'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => 'President\'s Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MAJOLAGBE OLUFEMI',
                'email' => null,
                'phones' => ['08065000583'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNJOBI A. OLUWASEUN',
                'email' => null,
                'phones' => ['08060210550'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-06-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BALOGUN DAMILOLA',
                'email' => null,
                'phones' => ['08034765665'],
                'department_id' => 29,
                'gender' => 'M',
                'birth_date' => '2000-06-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONIPEDE HANNAH O.',
                'email' => null,
                'phones' => ['07064234899'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-06-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAKARE TOLULOPE',
                'email' => null,
                'phones' => ['07032571962'],
                'department_id' => 38,
                'gender' => 'F',
                'birth_date' => '2000-06-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOYEMI BLESSING FOLUKE',
                'email' => null,
                'phones' => ['07066393533'],
                'department_id' => 52,
                'gender' => 'F',
                'birth_date' => '2000-06-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEFABI PEACE TAIWO',
                'email' => null,
                'phones' => ['08169576027'],
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-06-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'CHUKWUMA SANDRA SILVIA',
                'email' => null,
                'phones' => ['07033246611'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-06-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODESANYA BUSAYO',
                'email' => null,
                'phones' => ['08161129829'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-06-15',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBAFEMI OLUWATOBILOBA',
                'email' => null,
                'phones' => ['08135665084'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-06-15',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBAYO EMMANUEL',
                'email' => null,
                'phones' => ['07068779207'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-06-16',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AINA OLAYINKA JIMOH',
                'email' => null,
                'phones' => ['08066343021'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-06-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AIWA OLUWATIMILEHIN',
                'email' => null,
                'phones' => ['08066343021'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-06-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUMI ADEYINKA D.',
                'email' => null,
                'phones' => ['07035951063'],
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-06-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUDAIRO ABOLADE SAMUEL',
                'email' => null,
                'phones' => ['07032639427'],
                'department_id' => 6,
                'gender' => 'M',
                'birth_date' => '2000-06-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUMI DAVID ADEOLUWA',
                'email' => null,
                'phones' => ['08185637062'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-06-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MARINDOTI DAMILOLA M.',
                'email' => null,
                'phones' => ['07069791825'],
                'department_id' => 17,
                'gender' => 'F',
                'birth_date' => '2000-06-30',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNGBEMI NOAH',
                'email' => null,
                'phones' => ['08132673450'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-06-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAGBEMIGUN ADEYINKA OKEOWO',
                'email' => null,
                'phones' => ['07035072299'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-07-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWE SUNDAY FOLORUNSO',
                'email' => null,
                'phones' => ['08062198780'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-07-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DADA ADESOLA PHILIP',
                'email' => null,
                'phones' => ['08179673324'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-07-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI KAYODE D.',
                'email' => null,
                'phones' => ['08039204811'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-07-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWOLE OLUWAFISAYO A.',
                'email' => null,
                'phones' => ['07061125373'],
                'department_id' => 38,
                'gender' => 'F',
                'birth_date' => '2000-07-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'GBADAMOSI OPEYEMI E.',
                'email' => null,
                'phones' => ['08065880741'],
                'department_id' => 6,
                'gender' => 'M',
                'birth_date' => '2000-07-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MOSES BUSAYO T.',
                'email' => null,
                'phones' => ['08160694545'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-07-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMODARA OLUWASEUN',
                'email' => null,
                'phones' => ['08139737158'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-07-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TIAMIYU BABATUNDE ABASS',
                'email' => null,
                'phones' => ['08027563526'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-07-14',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJIBOLA BABATUNDE E.',
                'email' => null,
                'phones' => ['08163322468'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-07-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARO AKINTAYO',
                'email' => null,
                'phones' => ['08066513542'],
                'department_id' => 27,
                'gender' => 'M',
                'birth_date' => '2000-07-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MALOMO MODUPEOLA A.',
                'email' => null,
                'phones' => ['08033457399'],
                'department_id' => 49,
                'gender' => 'F',
                'birth_date' => '2000-07-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBUWADE OLUWASEUN MARY',
                'email' => null,
                'phones' => ['08038355233'],
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-07-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'RAWA OLUTAYO OLUSEYI',
                'email' => null,
                'phones' => ['08038525626'],
                'department_id' => 44,
                'gender' => 'F',
                'birth_date' => '2000-07-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWOLE TEMITOPE A.',
                'email' => null,
                'phones' => ['08066479385'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-07-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAKARE OLUWADAMILARE D.',
                'email' => null,
                'phones' => ['07035999423'],
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-08-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAFASAKIN OLUMIDE O.',
                'email' => null,
                'phones' => ['08167706881'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-08-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABALOLA BUSAYO A.',
                'email' => null,
                'phones' => ['08038253640'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-08-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOWE JANET OLAWUMI',
                'email' => null,
                'phones' => ['07033423849'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-08-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIRAN FOLAKEMI',
                'email' => null,
                'phones' => ['08066306905'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-08-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ILESANMI BOLANLE A.',
                'email' => null,
                'phones' => ['08065188402'],
                'department_id' => 6,
                'gender' => 'F',
                'birth_date' => '2000-08-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DOSUMU DAMILOLA A.',
                'email' => null,
                'phones' => ['08039418961'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-08-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEBADE TOPE',
                'email' => null,
                'phones' => ['08135624819'],
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-08-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYENI OLUSOLA A.',
                'email' => null,
                'phones' => ['07066548776'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-08-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOLABI AYODEJI',
                'email' => null,
                'phones' => ['08169569655'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-08-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYOOLA BIMPE CHRISTIANAH',
                'email' => null,
                'phones' => ['07031801280'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-08-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABALOLA ADEBISI',
                'email' => null,
                'phones' => ['08136136363'],
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-08-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOSEENI MICHAEL',
                'email' => null,
                'phones' => ['08137898794'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-08-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAGUNJU TOMISIN',
                'email' => null,
                'phones' => ['07062590884'],
                'department_id' => 6,
                'gender' => 'F',
                'birth_date' => '2000-08-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTAYO YEMISI FLORENCE',
                'email' => null,
                'phones' => ['08162636088'],
                'department_id' => 38,
                'gender' => 'F',
                'birth_date' => '2000-09-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUTUNJI TIMILEHIN B.',
                'email' => null,
                'phones' => ['08037620307'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-09-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESUYI TOLULOPE',
                'email' => null,
                'phones' => ['07031924606'],
                'department_id' => 49,
                'gender' => 'M',
                'birth_date' => '2000-09-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWOLE SAMUEL DAMILOLA',
                'email' => null,
                'phones' => ['07065398247'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-09-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSEOMWAKINA A. VICTOR',
                'email' => null,
                'phones' => ['07065092331'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-09-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABAJIDE OLUMIDE O.',
                'email' => null,
                'phones' => ['08165298533'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-09-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETULA YOMI V.',
                'email' => null,
                'phones' => ['07036616565'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-09-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOBOMI KEHINDE A.',
                'email' => null,
                'phones' => ['08067097801'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-09-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJEIGBE BABATUNDE DAVID',
                'email' => null,
                'phones' => ['08105422872'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-09-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONABANJO TAIWO A.',
                'email' => null,
                'phones' => ['08139444800'],
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-09-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARUNA PRECIOUS IFEOLUWA',
                'email' => null,
                'phones' => ['08162762096'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-09-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EMMANUEL CHRISTOPHER D.',
                'email' => null,
                'phones' => ['08035033514'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKEYODE RHODA',
                'email' => null,
                'phones' => ['08108510661'],
                'department_id' => 4,
                'gender' => 'F',
                'birth_date' => '2000-10-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBOOLA IBUKUNOLUWA I.',
                'email' => null,
                'phones' => ['08130975530'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-10-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AMUJO KOLADE SYLVESTER',
                'email' => null,
                'phones' => ['07034285881'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-10-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEBOKUN AJIBOLA',
                'email' => null,
                'phones' => ['08134366947'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-10-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWOLE OYEBOKUN AJIBOLA',
                'email' => null,
                'phones' => ['08134366947'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-10-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KAYODE OLUWABUSAYOMI',
                'email' => null,
                'phones' => ['08139140891'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-10-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IMOHIMI EMMANUEL E.',
                'email' => null,
                'phones' => ['08039472975'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-10-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SIKIRU SEMIU OLALEKAN',
                'email' => null,
                'phones' => ['08146875713'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-10-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNJIMI OBASEYI',
                'email' => null,
                'phones' => ['07038606265'],
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-10-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'UBABUKO IZUCHUKWU',
                'email' => null,
                'phones' => ['07031800171'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-10-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMODELE LYDIA P.',
                'email' => null,
                'phones' => ['07062739735'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-10-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYODEJI OLANREWAJU',
                'email' => null,
                'phones' => ['07062337439'],
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-10-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUMI OLUWATOSIN',
                'email' => null,
                'phones' => ['08164024128'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-10-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSEYE HENRY A.',
                'email' => null,
                'phones' => ['08062582672'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-10-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IFATUROTI OLUWATOBILOBA A.',
                'email' => null,
                'phones' => ['09032340060'],
                'department_id' => null,
                'gender' => 'F',
                'birth_date' => '2000-10-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALUA TEMITOPE O.',
                'email' => null,
                'phones' => ['07068912907'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-10-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSOLA OLUWATOMISIN A.',
                'email' => null,
                'phones' => ['08064254154'],
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-10-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO OLUSOLA TIMOTHY',
                'email' => null,
                'phones' => ['08167395197'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-10-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KUMAPAYI OLUWABUNMI',
                'email' => null,
                'phones' => ['08138355473'],
                'department_id' => 3,
                'gender' => 'F',
                'birth_date' => '2000-10-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLANREWAJU STELLA O.',
                'email' => null,
                'phones' => ['07030911116'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-10-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOLARA O. PHOEBE',
                'email' => null,
                'phones' => ['08106444077'],
                'department_id' => 5,
                'gender' => 'F',
                'birth_date' => '2000-10-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDOYIN OLUWAPELUMI',
                'email' => null,
                'phones' => ['08105559710'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBAYO HENRY',
                'email' => null,
                'phones' => ['08132561200'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-11-03',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAMI KAYODE S.',
                'email' => null,
                'phones' => ['07084418236'],
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-11-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIRAN TOSIN',
                'email' => null,
                'phones' => ['08037536366'],
                'department_id' => null,
                'gender' => null,
                'birth_date' => '2000-11-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNRONBI FRANCIS JOJUMADE',
                'email' => null,
                'phones' => ['08138821012'],
                'department_id' => 52,
                'gender' => 'M',
                'birth_date' => '2000-11-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAMINKI IFEOLUWA',
                'email' => null,
                'phones' => ['07065345766'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-11-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJIBOLA ABIOLA AHMED',
                'email' => null,
                'phones' => ['08182767903'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-11-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KOLAWOLE OPEYEMI IFEOLUWA',
                'email' => null,
                'phones' => ['07033961624'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-11-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAJOBI ADEBOWALE',
                'email' => null,
                'phones' => ['07065221986'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-11-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OTOKITI JOY',
                'email' => null,
                'phones' => ['07035104384'],
                'department_id' => 3,
                'gender' => 'F',
                'birth_date' => '2000-11-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESINA OPEOLUWA',
                'email' => null,
                'phones' => ['08139751464'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-11-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ILORI BOLUWATIFE GRACE',
                'email' => null,
                'phones' => ['08069640990'],
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-11-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LAWAL OLUWASEUN TEMIDIRE',
                'email' => null,
                'phones' => ['08060369407'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-11-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAMIDELE JULIAN',
                'email' => null,
                'phones' => ['08033807456'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-11-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IKEZI CHINEDU PRINCEWILL',
                'email' => null,
                'phones' => ['07061398228'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-12-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBISODUN BABATUNDE O.',
                'email' => null,
                'phones' => ['08135591459'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-12-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBOBOLA ADEDOLAPO',
                'email' => null,
                'phones' => ['07062449087'],
                'department_id' => 8,
                'gender' => 'F',
                'birth_date' => '2000-12-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BUSARI SEGUN DAMILARE',
                'email' => null,
                'phones' => ['08066517636'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-12-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBOBOLA ADEDOLAPO A.',
                'email' => null,
                'phones' => ['07062449087'],
                'department_id' => 8,
                'gender' => 'F',
                'birth_date' => '2000-12-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJABALUKU OLUBUKOLA JULIET',
                'email' => null,
                'phones' => ['08065389567'],
                'department_id' => 8,
                'gender' => 'F',
                'birth_date' => '2000-12-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MUSTAPHA MICHAEL O.',
                'email' => null,
                'phones' => ['08136647582'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-12-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEJUBE OLUWAKEMI',
                'email' => null,
                'phones' => ['07038747837'],
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-12-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAWOLE OLAOLUWA FELIX',
                'email' => null,
                'phones' => ['07065312405'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-12-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'COKER OLUWASEUN I',
                'email' => null,
                'phones' => ['08062573726'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-12-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAWU SUNDAY A.',
                'email' => null,
                'phones' => ['08060081790'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-12-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SIJUWADE ADETOPE C.',
                'email' => null,
                'phones' => ['08108008669'],
                'department_id' => 3,
                'gender' => 'F',
                'birth_date' => '2000-12-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYAGBIJA GRACE B.',
                'email' => null,
                'phones' => ['08066324067'],
                'department_id' => 34,
                'gender' => 'F',
                'birth_date' => '2000-12-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OPASANYA DAYO',
                'email' => null,
                'phones' => ['816922964'],
                'department_id' => null,
                'gender' => null,
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'UDOFIA ETINI A.',
                'email' => null,
                'phones' => ['08108688523'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBUWADE OLUWASEUN MARY',
                'email' => null,
                'phones' => ['08038355233'],
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-06-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: " . count($alumni) . " records");
    }
}
