<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2008_2009Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2008-2009'],
            ['name' => '2008-2009 Set']
        );

        $alumni = [
            [
                'name' => '1',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '2',
                'email' => null,
                'phones' => ['08062301328'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '3',
                'email' => null,
                'phones' => ['08032245117'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '4',
                'email' => null,
                'phones' => ['08033575180'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '5',
                'email' => null,
                'phones' => ['08052398631'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '6',
                'email' => null,
                'phones' => ['08038518352'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '7',
                'email' => null,
                'phones' => ['08035592650', '08080890541'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '8',
                'email' => null,
                'phones' => ['08034446784'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '9',
                'email' => null,
                'phones' => ['08060073300'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '10',
                'email' => null,
                'phones' => ['08077939722'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '11',
                'email' => null,
                'phones' => ['08062737897', '08027573690'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '12',
                'email' => null,
                'phones' => ['08032399898', '08072096166'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '13',
                'email' => null,
                'phones' => ['08036042484'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '14',
                'email' => null,
                'phones' => ['08030888291'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '15',
                'email' => null,
                'phones' => ['08024249569'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '16',
                'email' => null,
                'phones' => ['08062204693'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '17',
                'email' => null,
                'phones' => ['08061678485'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '18',
                'email' => null,
                'phones' => ['08062271451'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '19',
                'email' => null,
                'phones' => ['07037837501'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '20',
                'email' => null,
                'phones' => ['08034883872'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '21',
                'email' => null,
                'phones' => ['08026942347'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '22',
                'email' => null,
                'phones' => ['08034623952'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '23',
                'email' => null,
                'phones' => ['08033662091'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '24',
                'email' => null,
                'phones' => ['08028379297'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '25',
                'email' => null,
                'phones' => ['08030658483'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '26',
                'email' => null,
                'phones' => ['07038625295'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '27',
                'email' => null,
                'phones' => ['08066360416'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '28',
                'email' => null,
                'phones' => ['08033672783'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '29',
                'email' => null,
                'phones' => ['08038255937'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '30',
                'email' => null,
                'phones' => ['07031852563'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '31',
                'email' => null,
                'phones' => ['08076057155'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '32',
                'email' => null,
                'phones' => ['08059849292'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '33',
                'email' => null,
                'phones' => ['08034377884'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '34',
                'email' => null,
                'phones' => ['08038589616'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '35',
                'email' => null,
                'phones' => ['08068123362'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '36',
                'email' => null,
                'phones' => ['08084844108'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '37',
                'email' => null,
                'phones' => ['08069032404'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '38',
                'email' => null,
                'phones' => ['08037998939'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '39',
                'email' => null,
                'phones' => ['08035368495'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '40',
                'email' => null,
                'phones' => ['08035289288'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '41',
                'email' => null,
                'phones' => ['08067111974', '07055394570'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '42',
                'email' => null,
                'phones' => ['08067111974'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '43',
                'email' => null,
                'phones' => ['08053222386'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '44',
                'email' => null,
                'phones' => ['08024799641'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '45',
                'email' => null,
                'phones' => ['08030809453'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '46',
                'email' => null,
                'phones' => ['08068496859'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '47',
                'email' => null,
                'phones' => ['08036190049'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '48',
                'email' => null,
                'phones' => ['08025461700'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '49',
                'email' => null,
                'phones' => ['07038874737'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '50',
                'email' => null,
                'phones' => ['08037643442'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '51',
                'email' => null,
                'phones' => ['08022570609'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '52',
                'email' => null,
                'phones' => ['08029265121'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '53',
                'email' => null,
                'phones' => ['08067219186'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '54',
                'email' => null,
                'phones' => ['08060306201'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '55',
                'email' => null,
                'phones' => ['08067515135'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '56',
                'email' => null,
                'phones' => ['08032151784'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '57',
                'email' => null,
                'phones' => ['08025436073'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '58',
                'email' => null,
                'phones' => ['08034884350'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '59',
                'email' => null,
                'phones' => ['08066540760'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '60',
                'email' => null,
                'phones' => ['08030412825'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '61',
                'email' => null,
                'phones' => ['80363911561'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '62',
                'email' => null,
                'phones' => ['08026318582'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '63',
                'email' => null,
                'phones' => ['08023644299', '08033440168'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '64',
                'email' => null,
                'phones' => ['08034224832'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '65',
                'email' => null,
                'phones' => ['07032630969', '08027211202'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '66',
                'email' => null,
                'phones' => ['08064839198'],
                'department' => 'KAYODE E.J',
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '67',
                'email' => null,
                'phones' => ['08039214333'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '68',
                'email' => null,
                'phones' => ['08037994938'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '69',
                'email' => null,
                'phones' => ['80056763676'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '70',
                'email' => null,
                'phones' => ['08064853078'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '71',
                'email' => null,
                'phones' => ['08065656461'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '72',
                'email' => null,
                'phones' => ['08027251470', '07039170757'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '73',
                'email' => null,
                'phones' => ['08034986187'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '74',
                'email' => null,
                'phones' => ['08067112371'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '75',
                'email' => null,
                'phones' => ['08025482174'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '76',
                'email' => null,
                'phones' => ['08062508781'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '77',
                'email' => null,
                'phones' => ['08038280064'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '78',
                'email' => null,
                'phones' => ['08067586444'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '79',
                'email' => null,
                'phones' => ['08074624498'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '80',
                'email' => null,
                'phones' => ['08034979215'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '81',
                'email' => null,
                'phones' => ['08052254063'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '82',
                'email' => null,
                'phones' => ['08062929972'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '83',
                'email' => null,
                'phones' => ['07038408031'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '84',
                'email' => null,
                'phones' => ['08054135723', '08064463042'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '85',
                'email' => null,
                'phones' => ['08032432733'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '86',
                'email' => null,
                'phones' => ['08036994003', '07027408737'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '87',
                'email' => null,
                'phones' => ['08059490401'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '88',
                'email' => null,
                'phones' => ['08035902446'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '89',
                'email' => null,
                'phones' => ['08032320463'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '90',
                'email' => null,
                'phones' => ['08034899177'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '91',
                'email' => null,
                'phones' => ['08026898517'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '92',
                'email' => null,
                'phones' => ['08034935794'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '93',
                'email' => null,
                'phones' => ['08034200841'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '94',
                'email' => null,
                'phones' => ['08038255255'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '95',
                'email' => null,
                'phones' => ['08034258142'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '96',
                'email' => null,
                'phones' => ['08066088163'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '97',
                'email' => null,
                'phones' => ['08036028454'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '98',
                'email' => null,
                'phones' => ['08034985728'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '99',
                'email' => null,
                'phones' => ['08024062429'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '100',
                'email' => null,
                'phones' => ['08035434937'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '101',
                'email' => null,
                'phones' => ['80366439795'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '102',
                'email' => null,
                'phones' => ['08029162280'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '103',
                'email' => null,
                'phones' => ['08032868545'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '104',
                'email' => null,
                'phones' => ['08030724308'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '105',
                'email' => null,
                'phones' => ['08035831642'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '106',
                'email' => null,
                'phones' => ['08033618750'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '107',
                'email' => null,
                'phones' => ['08060178479'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '108',
                'email' => null,
                'phones' => ['80262399988', '0803921729'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '109',
                'email' => null,
                'phones' => ['08038002172'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '110',
                'email' => null,
                'phones' => ['08025324072'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '111',
                'email' => null,
                'phones' => ['80773326424'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '112',
                'email' => null,
                'phones' => ['08060806393'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '113',
                'email' => null,
                'phones' => ['08032210661'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '114',
                'email' => null,
                'phones' => ['08038664815'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '115',
                'email' => null,
                'phones' => ['08066649294'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '116',
                'email' => null,
                'phones' => ['08027438347'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '117',
                'email' => null,
                'phones' => ['08035123539'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '118',
                'email' => null,
                'phones' => ['08025598663', '808473488'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '119',
                'email' => null,
                'phones' => ['08052334748'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '120',
                'email' => null,
                'phones' => ['08027297123'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '121',
                'email' => null,
                'phones' => ['08038488509'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '122',
                'email' => null,
                'phones' => ['08026694832'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '123',
                'email' => null,
                'phones' => ['08061173738'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '124',
                'email' => null,
                'phones' => ['08035145884'],
                'department' => 'TIEASE T.O',
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '125',
                'email' => null,
                'phones' => ['08088097170'],
                'department' => 'TOYE C.A',
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '126',
                'email' => null,
                'phones' => ['08038479396'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '127',
                'email' => null,
                'phones' => ['08077788344'],
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
