<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2004_2005Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2004-2005'],
            ['name' => '2004-2005 Set']
        );

        $alumni = [
            [
                'name' => '1',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '2',
                'email' => null,
                'phones' => null,
                'department' => 'AKPE REMMY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '3',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '4',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '5',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '6',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '7',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '8',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '9',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '10',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '11',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '12',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '13',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '14',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '15',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '16',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '17',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '18',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '19',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '20',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '21',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '22',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '23',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '24',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '25',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '26',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '27',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '28',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '29',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '30',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
            [
                'name' => '31',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '32',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '33',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '34',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '35',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '36',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '37',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '38',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'M',
            ],
            [
                'name' => '39',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => 'F',
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
