<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2005_2006Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2005-2006'],
            ['name' => '2005-2006 Set']
        );

        $alumni = [
            [
                'name' => 'ALAO M. OLAYEMI',
                'email' => null,
                'phones' => ['08054041088'],
                'department' => 'AEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBOTOBA GBENGA',
                'email' => null,
                'phones' => ['08035678768'],
                'department' => 'AEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MEGBUWANUN. A. A',
                'email' => null,
                'phones' => ['08029442293'],
                'department' => 'AGE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYENEYE OLABODE',
                'email' => null,
                'phones' => ['08035369018'],
                'department' => 'AGE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BANKOLE O. M',
                'email' => null,
                'phones' => null,
                'department' => 'AGP',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKUNNIGA SEGUN',
                'email' => null,
                'phones' => null,
                'department' => 'AGP',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINRINADE OPEYEMI',
                'email' => null,
                'phones' => ['08034397417'],
                'department' => 'AGP',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ESENE E. E',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JIMOH SURAJUDEEN',
                'email' => null,
                'phones' => ['08035175590'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JAGBORO GERSHOM',
                'email' => null,
                'phones' => ['08038349738'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWODEYIN SANYA',
                'email' => null,
                'phones' => ['08037186170'],
                'department' => 'ARC',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JUSTIN CHIKEZIE',
                'email' => null,
                'phones' => null,
                'department' => 'ARC',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI MOMTUNDE',
                'email' => null,
                'phones' => null,
                'department' => 'BCH',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MOMOH ALABA',
                'email' => null,
                'phones' => null,
                'department' => 'BCH',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BOLARINWA BOSEDE',
                'email' => null,
                'phones' => null,
                'department' => 'BCH',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAMI OLUFEMI',
                'email' => null,
                'phones' => null,
                'department' => 'BIO',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FABOYEDE TOLA',
                'email' => null,
                'phones' => null,
                'department' => 'CHE',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAIYA TOLU',
                'email' => null,
                'phones' => ['08054150349'],
                'department' => 'CHE',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BALOGUN TAYO',
                'email' => null,
                'phones' => null,
                'department' => 'CHE',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OUAGBO ADESEGUNFUNMI',
                'email' => null,
                'phones' => ['08034384605'],
                'department' => 'CHE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDEJI SUNDAY',
                'email' => null,
                'phones' => null,
                'department' => 'CHE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESANWO B. ADEWUNMI',
                'email' => null,
                'phones' => null,
                'department' => 'CSC',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODOFIN OLUWASEUN',
                'email' => null,
                'phones' => ['08034007112'],
                'department' => 'CSC',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEPOJU MORADEKE',
                'email' => null,
                'phones' => ['08034902707'],
                'department' => 'CSC',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IDOWU OYEYEMI',
                'email' => null,
                'phones' => null,
                'department' => 'CSC',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALEJO OLAKUNLE',
                'email' => null,
                'phones' => null,
                'department' => 'CSP',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEWUSI MICHAEL',
                'email' => null,
                'phones' => ['08054470323'],
                'department' => 'CVE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWUNMI ISAAC',
                'email' => null,
                'phones' => null,
                'department' => 'CVE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYETORO A. B',
                'email' => null,
                'phones' => ['08035307395'],
                'department' => 'CVE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMONIYI KOLA',
                'email' => null,
                'phones' => null,
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDIPE AKKINTUNDE',
                'email' => null,
                'phones' => ['08035963873'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'THOMAS OLAROTIMI',
                'email' => null,
                'phones' => null,
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJALA YEMI',
                'email' => null,
                'phones' => null,
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LONGE MUYIWA',
                'email' => null,
                'phones' => null,
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FRANKLIN. C',
                'email' => null,
                'phones' => ['08038579079'],
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMISORE AFOLABI',
                'email' => null,
                'phones' => null,
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOTIMIRO OLUWATOSIN',
                'email' => null,
                'phones' => ['08038126521'],
                'department' => 'FST',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KUNLERE ADESOJI',
                'email' => null,
                'phones' => ['08034902014'],
                'department' => 'FWL',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJO BAALE',
                'email' => null,
                'phones' => ['08035690292'],
                'department' => 'IDD',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASAMU MICHAEL',
                'email' => null,
                'phones' => null,
                'department' => 'MCB',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ESHO TOLA',
                'email' => null,
                'phones' => ['08033564863'],
                'department' => 'MCB',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODOLE OLUGBENGA',
                'email' => null,
                'phones' => ['08034617764'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAJOMO ALABA',
                'email' => null,
                'phones' => ['08034677544'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASAFA GBENGA',
                'email' => null,
                'phones' => ['08035393846'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BANJOKO A. A',
                'email' => null,
                'phones' => null,
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'CHOGUDO NELSON',
                'email' => null,
                'phones' => null,
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABIOYE TAIWO. E',
                'email' => null,
                'phones' => ['08034347247'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJILEYE SEGUNM',
                'email' => null,
                'phones' => ['08034113375'],
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAMI OLUFEMI',
                'email' => null,
                'phones' => null,
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAWANDE OLUBUKOLA',
                'email' => null,
                'phones' => null,
                'department' => 'MME',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBIKI NDUDI',
                'email' => null,
                'phones' => ['08035662574'],
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AMODU OLUWASEGUN. V',
                'email' => null,
                'phones' => null,
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYINOLA ABIOLA',
                'email' => null,
                'phones' => null,
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ESAN OLAYIWOLA',
                'email' => null,
                'phones' => null,
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FADIMILEHIN OLAYEMI',
                'email' => null,
                'phones' => ['08028988126'],
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNFEMI ADEDAYO',
                'email' => null,
                'phones' => ['08030651545'],
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKAFOR P. C',
                'email' => null,
                'phones' => ['08043334562'],
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDIRAN A. TUNDE',
                'email' => null,
                'phones' => ['08036565342'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JEHREY A.',
                'email' => null,
                'phones' => ['08035623733'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI. A SUCCESS',
                'email' => null,
                'phones' => ['08034978775'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ESAN FOLAKEMI',
                'email' => null,
                'phones' => ['08035464271'],
                'department' => 'QSV',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KAREEM DOLAPO',
                'email' => null,
                'phones' => ['08038046153'],
                'department' => 'QSV',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ROTIBA DICKSON',
                'email' => null,
                'phones' => ['08036951219'],
                'department' => 'QSV',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SANNI GABRIELLA',
                'email' => null,
                'phones' => null,
                'department' => 'QSV',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABEGUNDE KAYODE',
                'email' => null,
                'phones' => ['08029183974'],
                'department' => 'URP',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DUROJAIYE EDWARD',
                'email' => null,
                'phones' => ['08035786392'],
                'department' => 'URP',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYINKA ADEOLA',
                'email' => null,
                'phones' => ['08035852092'],
                'department' => 'URP',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOWOSEGUN ADEBOLAM',
                'email' => null,
                'phones' => ['08033704059'],
                'department' => 'URP',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADAMS ADEOLA',
                'email' => null,
                'phones' => null,
                'department' => 'MCB',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKANDE RASHIDAT',
                'email' => null,
                'phones' => null,
                'department' => 'BCH',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
