<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2003_2004Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2003-2004'],
            ['name' => '2003-2004 Set']
        );

        $alumni = [
            [
                'name' => 'ABOABA OLANREWAJU',
                'email' => null,
                'phones' => null,
                'department' => 'AGP',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABODUNDE DOLAPO',
                'email' => null,
                'phones' => null,
                'department' => 'IMC',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADE-ODUMBONI ADELEKE',
                'email' => null,
                'phones' => null,
                'department' => 'APH',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBAYO BANKOLE',
                'email' => null,
                'phones' => null,
                'department' => 'FWL',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBOYEGA MAYOKUN',
                'email' => null,
                'phones' => null,
                'department' => 'BIO',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIRAN PETER',
                'email' => null,
                'phones' => null,
                'department' => 'AGP',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESIDA ABIODUN',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETAYO BABATUNDE',
                'email' => null,
                'phones' => null,
                'department' => 'EEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUMI FOLASADE',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEYE FESTUS',
                'email' => null,
                'phones' => null,
                'department' => 'MEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFOLALU ADENIRAN',
                'email' => null,
                'phones' => null,
                'department' => 'MEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AINA ABAYOMI',
                'email' => null,
                'phones' => null,
                'department' => 'CVE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI ADENIYI',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJENIFUJA KELVIN',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJUMOBI OLUMAYOWA',
                'email' => null,
                'phones' => null,
                'department' => 'MME',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKANO OLAKUNLE',
                'email' => null,
                'phones' => null,
                'department' => 'IMC',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOLA BOLANLE',
                'email' => null,
                'phones' => null,
                'department' => 'BCH',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOLA FRANK',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOLA TEMIDAYO',
                'email' => null,
                'phones' => null,
                'department' => 'BIO',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALEXANDER ADESHINA',
                'email' => null,
                'phones' => null,
                'department' => 'CHE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALIU OLUWATOYIN',
                'email' => null,
                'phones' => null,
                'department' => 'CVE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALONGE JOSEPHINE',
                'email' => null,
                'phones' => null,
                'department' => 'BIO',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARINDE FUNSHO',
                'email' => null,
                'phones' => null,
                'department' => 'MNE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOFISOYE B.O',
                'email' => null,
                'phones' => null,
                'department' => 'AEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BADA ABOSEDE',
                'email' => null,
                'phones' => null,
                'department' => 'CVE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'CLARKE OKAH W.E',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EGBOBI K.O',
                'email' => null,
                'phones' => null,
                'department' => 'MEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EJIOFOR NKIRUKA',
                'email' => null,
                'phones' => null,
                'department' => 'FST',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ELEHINTE YEMISI',
                'email' => null,
                'phones' => null,
                'department' => 'BIO',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAKOREDE ADESOJI',
                'email' => null,
                'phones' => null,
                'department' => 'IMC',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALEYE TAYO',
                'email' => null,
                'phones' => null,
                'department' => 'PHY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IBINI OLUMIDE',
                'email' => null,
                'phones' => null,
                'department' => 'MEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ILAYA ANDREW',
                'email' => null,
                'phones' => null,
                'department' => 'MET',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ISARINDE ISIAH',
                'email' => null,
                'phones' => null,
                'department' => 'MNE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ISIMIJOLA OLUWATOYIN',
                'email' => null,
                'phones' => null,
                'department' => 'EEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IWAYE CHRISTIANAH',
                'email' => null,
                'phones' => null,
                'department' => 'IMC',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KAYODE TEMITOPE',
                'email' => null,
                'phones' => null,
                'department' => 'AGE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LERAMO PETER',
                'email' => null,
                'phones' => null,
                'department' => 'PHY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'NATHANIEL SEGUN',
                'email' => null,
                'phones' => null,
                'department' => 'MNE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNBANJO YOMI',
                'email' => null,
                'phones' => null,
                'department' => 'AGE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNGBMILA TOKUNBO',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLANA ADEBOYE',
                'email' => null,
                'phones' => null,
                'department' => 'BIO',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNTOLA SEUN',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNYE AYOYEMI',
                'email' => null,
                'phones' => null,
                'department' => 'MNE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO EZEIKEL',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO WURAOLA',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJOADE OLUWASEYI',
                'email' => null,
                'phones' => null,
                'department' => 'MME',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKUWOBI ADEWALE',
                'email' => null,
                'phones' => null,
                'department' => 'MME',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLA MONISOLA',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLALUDE IFEDAYO',
                'email' => null,
                'phones' => null,
                'department' => 'AEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLASUKANMI OLATUNJI',
                'email' => null,
                'phones' => null,
                'department' => 'PHY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATUNJI MODUPE',
                'email' => null,
                'phones' => null,
                'department' => 'FST',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLANIPEKUN PHILIP',
                'email' => null,
                'phones' => null,
                'department' => 'ARC',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOWOLEREKUN SAMSON',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWADARE DOMINIC',
                'email' => null,
                'phones' => null,
                'department' => 'QSV',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOLE OLANREWAJU',
                'email' => null,
                'phones' => null,
                'department' => 'CVE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOSUYI DEJI',
                'email' => null,
                'phones' => null,
                'department' => 'MEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONILEOWO ARIYO',
                'email' => null,
                'phones' => null,
                'department' => 'EEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEDUNTAN GBENGA',
                'email' => null,
                'phones' => null,
                'department' => 'CHE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYENUGA OLUFEMI',
                'email' => null,
                'phones' => null,
                'department' => 'IMC',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'QUADRI MODUPE',
                'email' => null,
                'phones' => null,
                'department' => 'FST',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ROMILUYI ADESUYI',
                'email' => null,
                'phones' => null,
                'department' => 'CSP',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SHEYA ROBINSON',
                'email' => null,
                'phones' => null,
                'department' => 'PHY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TAIWO ADEYINKA',
                'email' => null,
                'phones' => null,
                'department' => 'MME',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TEIBO JOHN',
                'email' => null,
                'phones' => null,
                'department' => 'AGY',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSUNMOYE FRANKLIN',
                'email' => null,
                'phones' => null,
                'department' => 'MEE',
                'gender' => null,
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
