<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2015_2016Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2015-2016'],
            ['name' => '2015-2016 Set']
        );

        $alumni = [
            [
                'name' => 'Adesida Bolaji',
                'email' => null,
                'phones' => ['08063924106'],
                'department' => 'URP',
                'gender' => 'F',
                'state' => null,
                'address' => 'Monalisa lodge',
            ],
            [
                'name' => 'Emekpo Zeal .E',
                'email' => null,
                'phones' => ['08108802174'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'One Tree Hill',
            ],
            [
                'name' => 'Ojo Taiwo',
                'email' => null,
                'phones' => ['08164628577'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogunsola Tolulope',
                'email' => null,
                'phones' => ['08064045791'],
                'department' => 'RSG',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola Hostl',
            ],
            [
                'name' => 'Ojo Kehinde',
                'email' => null,
                'phones' => ['08067320061'],
                'department' => 'ARE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Abundant life hstl',
            ],
            [
                'name' => 'Oladogba Babatunde',
                'email' => null,
                'phones' => ['08064045791'],
                'department' => 'ARC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Titanic lodge',
            ],
            [
                'name' => 'Ayodele Idowu',
                'email' => null,
                'phones' => ['07036848188'],
                'department' => 'ESM',
                'gender' => 'F',
                'state' => null,
                'address' => 'annex 2 rm 118',
            ],
            [
                'name' => 'Benneth Joel',
                'email' => null,
                'phones' => ['08130623743'],
                'department' => 'MST',
                'gender' => 'M',
                'state' => null,
                'address' => 'Castle of mercy apatapiti',
            ],
            [
                'name' => 'Oke Femi Folorunso',
                'email' => null,
                'phones' => ['08093680944'],
                'department' => 'QSV',
                'gender' => 'M',
                'state' => null,
                'address' => 'Redemption way',
            ],
            [
                'name' => 'Dada Samuel Kayode',
                'email' => null,
                'phones' => ['07062780007'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => 'BDDKEM lodge',
            ],
            [
                'name' => 'Shittu Odunayo Joshua',
                'email' => null,
                'phones' => ['08030885620'],
                'department' => 'MCB',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Idogho Oaajite Franklyn',
                'email' => null,
                'phones' => ['08063863089'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Royal estate',
            ],
            [
                'name' => 'Daramola Ayomikun',
                'email' => null,
                'phones' => ['08165656034'],
                'department' => 'ARC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Adeniyi hall',
            ],
            [
                'name' => 'Mordi Ebenezar',
                'email' => null,
                'phones' => ['08136494375'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => 'opposite sir alade',
            ],
            [
                'name' => 'Awoyemi Glory Tolulope',
                'email' => null,
                'phones' => ['07063973244'],
                'department' => 'CHE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Adetunji Korede',
                'email' => null,
                'phones' => ['08122890420'],
                'department' => 'ARE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Onabowale Onabode Elijah',
                'email' => null,
                'phones' => ['08066974472'],
                'department' => 'IDD',
                'gender' => 'M',
                'state' => null,
                'address' => 'Embassy lodge',
            ],
            [
                'name' => 'Adidoye Tolulope',
                'email' => null,
                'phones' => ['07033981304'],
                'department' => 'STAT',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel rm143',
            ],
            [
                'name' => 'Olajide Anuoluwapo',
                'email' => null,
                'phones' => ['07083120030'],
                'department' => 'URP',
                'gender' => 'F',
                'state' => null,
                'address' => 'Peeble of mercy',
            ],
            [
                'name' => 'Adu Oluwadamilola',
                'email' => null,
                'phones' => ['08035593853'],
                'department' => 'ARE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Adsonic',
            ],
            [
                'name' => 'Abioye Abraham oyewumi',
                'email' => null,
                'phones' => ['07058274253'],
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogunmola Ayodele',
                'email' => null,
                'phones' => ['08093773571'],
                'department' => 'BIO',
                'gender' => 'M',
                'state' => null,
                'address' => 'Royal Palace',
            ],
            [
                'name' => 'Owolabi Bukola',
                'email' => null,
                'phones' => ['07039318643'],
                'department' => 'BIO',
                'gender' => 'M',
                'state' => null,
                'address' => 'Stateline junction',
            ],
            [
                'name' => 'Fatukasi Olamigoke',
                'email' => null,
                'phones' => ['07031870111'],
                'department' => 'PMT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Cassava hostel',
            ],
            [
                'name' => 'Adebisi Olabisi',
                'email' => null,
                'phones' => ['08136303298'],
                'department' => 'MCB',
                'gender' => 'F',
                'state' => null,
                'address' => 'Redemption manson',
            ],
            [
                'name' => 'Ijato Oluwagbenga',
                'email' => null,
                'phones' => ['07038024834'],
                'department' => 'MCB',
                'gender' => 'M',
                'state' => null,
                'address' => 'Adeniyi hostel',
            ],
            [
                'name' => 'Ogunmola Oluwadamilola .o',
                'email' => null,
                'phones' => ['07066316400'],
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => 'Shanghai lodge aba',
            ],
            [
                'name' => 'Ogundipe Olufemi. R',
                'email' => null,
                'phones' => ['08034950520'],
                'department' => 'ARE',
                'gender' => 'M',
                'state' => null,
                'address' => 'One  united',
            ],
            [
                'name' => 'Akinwalie Oluwasanmi',
                'email' => null,
                'phones' => ['08166221075'],
                'department' => 'MTS',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adebayo Adewale John',
                'email' => null,
                'phones' => ['08138586973'],
                'department' => 'FST',
                'gender' => 'M',
                'state' => null,
                'address' => 'Road block area',
            ],
            [
                'name' => 'Ayeni Akolade Samuel',
                'email' => null,
                'phones' => ['07034388257'],
                'department' => 'CSC',
                'gender' => 'M',
                'state' => null,
                'address' => 'rm111 Akindeko',
            ],
            [
                'name' => 'Ogunleye oluwabukola',
                'email' => null,
                'phones' => ['07036746667'],
                'department' => 'FAT',
                'gender' => 'F',
                'state' => null,
                'address' => 'Bsd unity lodge aba',
            ],
            [
                'name' => 'Olasanayo Tobi',
                'email' => null,
                'phones' => ['07033613404'],
                'department' => 'EWM',
                'gender' => 'F',
                'state' => null,
                'address' => 'Redemption Sec',
            ],
            [
                'name' => 'Olorunmola Isaac',
                'email' => null,
                'phones' => ['07063260915'],
                'department' => 'ARC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Beside best lodge',
            ],
            [
                'name' => 'Akpobasa Martins',
                'email' => null,
                'phones' => ['08100050519'],
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => 'Off campus',
            ],
            [
                'name' => 'Olubowale Ajoke',
                'email' => null,
                'phones' => ['08067302546'],
                'department' => 'URP',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jibowu annext 2, 102',
            ],
            [
                'name' => 'Adeoye Oreitan Mary',
                'email' => null,
                'phones' => ['08079189623'],
                'department' => 'MCB',
                'gender' => 'F',
                'state' => null,
                'address' => 'Aso rock lodge futa junction',
            ],
            [
                'name' => 'Ademola Banke',
                'email' => null,
                'phones' => ['07066168481'],
                'department' => 'CHE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Royal villa',
            ],
            [
                'name' => 'Orisawumi Abiola',
                'email' => null,
                'phones' => ['07088220822'],
                'department' => 'QSV',
                'gender' => 'M',
                'state' => null,
                'address' => 'Vip lodge south gate',
            ],
            [
                'name' => 'Ilesanmi Kayode',
                'email' => null,
                'phones' => ['07032040649'],
                'department' => 'BCH',
                'gender' => 'M',
                'state' => null,
                'address' => 'Students headquarters stateli',
            ],
            [
                'name' => 'Mulero Samuel',
                'email' => null,
                'phones' => ['07038293548'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Shanghai lodge aba',
            ],
            [
                'name' => 'Adedayo Timileyin',
                'email' => null,
                'phones' => ['20150303', '000000'],
                'department' => 'FST',
                'gender' => 'M',
                'state' => null,
                'address' => 'Apatapiti',
            ],
            [
                'name' => 'Falola Temitope',
                'email' => null,
                'phones' => ['08183381444'],
                'department' => 'CHE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Singapore lodge',
            ],
            [
                'name' => 'Ikpotokin Osalumhense',
                'email' => null,
                'phones' => ['07063665467'],
                'department' => 'CVE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Ebunoluwa hostel stateline',
            ],
            [
                'name' => 'Jimoh Adewumi Dorcas',
                'email' => null,
                'phones' => ['07062665138'],
                'department' => 'FAT',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostl 136',
            ],
            [
                'name' => 'Adeniyi Samuel',
                'email' => null,
                'phones' => ['08071160862'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akindeko hostel',
            ],
            [
                'name' => 'Odunlade Emmanuel',
                'email' => null,
                'phones' => ['08162485698'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Lord strength villa',
            ],
            [
                'name' => 'Farotimi Ayobami',
                'email' => null,
                'phones' => ['08161117359'],
                'department' => 'MCB',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Bakare Temitope',
                'email' => null,
                'phones' => ['07034777447'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Evergreen lodge',
            ],
            [
                'name' => 'Oluwole Hellen Oluwatosin',
                'email' => null,
                'phones' => ['07031364805'],
                'department' => 'CSC',
                'gender' => 'F',
                'state' => null,
                'address' => 'Hitterland logde',
            ],
            [
                'name' => 'Akinpelu Abiola',
                'email' => null,
                'phones' => ['07034206847'],
                'department' => 'UPR',
                'gender' => 'M',
                'state' => null,
                'address' => 'Rm104 Akindeko hostel',
            ],
            [
                'name' => 'Olaiya Sunday Temitope',
                'email' => null,
                'phones' => ['07062737144'],
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => 'Opp accf Jesu palace',
            ],
            [
                'name' => 'Alexander Joshua',
                'email' => null,
                'phones' => ['08069026081'],
                'department' => 'MET',
                'gender' => 'M',
                'state' => null,
                'address' => 'Mega villa',
            ],
            [
                'name' => 'Kayode Oluwaseun',
                'email' => null,
                'phones' => ['08131128739'],
                'department' => 'ARE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Mercy lodge',
            ],
            [
                'name' => 'Adedeji Samson Adebanjo',
                'email' => null,
                'phones' => ['08130117715'],
                'department' => 'BCH',
                'gender' => 'M',
                'state' => null,
                'address' => 'Best lodge',
            ],
            [
                'name' => 'Boma Blessing',
                'email' => null,
                'phones' => ['08166057718'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Omodoroni Ajibola Isaac',
                'email' => null,
                'phones' => ['08189458281'],
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => 'No40 olko street',
            ],
            [
                'name' => 'Jacob Abosede Jesutofunmi',
                'email' => null,
                'phones' => ['07063238084'],
                'department' => 'ARE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jibowu annex 2 rm116',
            ],
            [
                'name' => 'Ishola Mariam',
                'email' => null,
                'phones' => ['08166333825'],
                'department' => 'BIO',
                'gender' => 'F',
                'state' => null,
                'address' => 'Stateline rd opp Thomas crwn',
            ],
            [
                'name' => 'Adeyinka Adetunji',
                'email' => null,
                'phones' => ['08029627613'],
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Cassava hostel',
            ],
            [
                'name' => 'Obembe Taiwo',
                'email' => null,
                'phones' => ['08166901700'],
                'department' => 'STAT',
                'gender' => 'F',
                'state' => null,
                'address' => 'Behind rescue lodge',
            ],
            [
                'name' => 'Bolarinde Oluwanifemi',
                'email' => null,
                'phones' => ['08101107154'],
                'department' => 'FWT',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jibowu annex 2',
            ],
            [
                'name' => 'Adegun Tolulope',
                'email' => null,
                'phones' => ['07038917284'],
                'department' => 'FST',
                'gender' => 'F',
                'state' => null,
                'address' => 'Marrb lodge bsd accf',
            ],
            [
                'name' => 'Buoro Ruth',
                'email' => null,
                'phones' => ['08031156827'],
                'department' => 'PHY',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Adekeye Sanmi Owoseni',
                'email' => null,
                'phones' => ['08067537068'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Jaak hostel',
            ],
            [
                'name' => 'Adelanwa Adeniyi',
                'email' => null,
                'phones' => ['08062880085'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akindeko hall',
            ],
            [
                'name' => 'Olaseini Opiola',
                'email' => null,
                'phones' => ['08188517572'],
                'department' => 'AGE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Adeniyi Hall',
            ],
            [
                'name' => 'Akindito Babatunde',
                'email' => null,
                'phones' => ['07032945789'],
                'department' => 'RSG',
                'gender' => 'M',
                'state' => null,
                'address' => 'Woleph extention',
            ],
            [
                'name' => 'Akinbi Oluwagbemisola',
                'email' => null,
                'phones' => ['08130300348'],
                'department' => 'CSP',
                'gender' => 'F',
                'state' => null,
                'address' => 'Off campus',
            ],
            [
                'name' => 'Afolabi Tolulope',
                'email' => null,
                'phones' => ['08105391218'],
                'department' => 'FWT',
                'gender' => 'F',
                'state' => null,
                'address' => 'Aba transformer',
            ],
            [
                'name' => 'Oyebamiji Ibunkun F',
                'email' => null,
                'phones' => ['08138580315'],
                'department' => 'ARC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Fine touch lodge peace avnue',
            ],
            [
                'name' => 'Olawumi Elizabeth',
                'email' => null,
                'phones' => ['07065157779'],
                'department' => 'CSP',
                'gender' => 'F',
                'state' => null,
                'address' => 'Redemption manson',
            ],
            [
                'name' => 'Alarape Adebimpe Tomilola',
                'email' => null,
                'phones' => ['07031670931'],
                'department' => 'FST',
                'gender' => 'F',
                'state' => null,
                'address' => 'Embassy lodge',
            ],
            [
                'name' => 'Shittu Oluwaseun',
                'email' => null,
                'phones' => ['08062603641'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akinola villa apatapiti',
            ],
            [
                'name' => 'Owolabi Josiah Ayomide',
                'email' => null,
                'phones' => ['08068785855'],
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => 'Off campus',
            ],
            [
                'name' => 'God\'s Favour Ezinwane',
                'email' => null,
                'phones' => ['08162787697'],
                'department' => 'APH',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Banjoko Gbenga',
                'email' => null,
                'phones' => ['08136496628'],
                'department' => 'ARC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Westend Lodge',
            ],
            [
                'name' => 'Abolarin Olawuyi',
                'email' => null,
                'phones' => ['07030063142'],
                'department' => 'EEE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Fine touch lodge peace avnue',
            ],
            [
                'name' => 'Ajo Oluwafemi',
                'email' => null,
                'phones' => ['07061935087'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Tallest hostel',
            ],
            [
                'name' => 'Umeh Peter Abidemi',
                'email' => null,
                'phones' => ['07060971948'],
                'department' => 'BUILDING',
                'gender' => 'M',
                'state' => null,
                'address' => 'Firsth upstairs aba',
            ],
            [
                'name' => 'Siyanbola Oladapo Joshua',
                'email' => null,
                'phones' => ['08069698690'],
                'department' => 'CSC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Rescue hostel',
            ],
            [
                'name' => 'Akinbulomo Oluwatosin',
                'email' => null,
                'phones' => ['08161298649'],
                'department' => 'FST',
                'gender' => 'F',
                'state' => null,
                'address' => 'Annex 2',
            ],
            [
                'name' => 'Adebola Sunday. S',
                'email' => null,
                'phones' => ['08140710442'],
                'department' => 'AGE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Mercy lodge',
            ],
            [
                'name' => 'Adekoya Eniola M',
                'email' => null,
                'phones' => ['08069681239'],
                'department' => 'QSV',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajayi Abosede Elizabeth',
                'email' => null,
                'phones' => ['07037549214'],
                'department' => 'CHE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Along Akad',
            ],
            [
                'name' => 'Andrew Nkem Fidelia',
                'email' => null,
                'phones' => ['07031802179'],
                'department' => 'MTS',
                'gender' => 'F',
                'state' => null,
                'address' => 'Shanghai lodge aba',
            ],
            [
                'name' => 'Ikpoba Cosmos Daniel',
                'email' => null,
                'phones' => ['08160701687'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Bsd success gate villa apatapiti',
            ],
            [
                'name' => 'Ogundele Oluwatosin',
                'email' => null,
                'phones' => ['07068411476'],
                'department' => 'AEC',
                'gender' => 'F',
                'state' => null,
                'address' => 'Rehoboth estate,abba',
            ],
            [
                'name' => 'Agbidi Emmanuel Ifeanyi',
                'email' => null,
                'phones' => ['07036314250'],
                'department' => 'MET',
                'gender' => 'M',
                'state' => null,
                'address' => 'God\'s own lodge beside fsf',
            ],
            [
                'name' => 'Agboola Mercy Owolola',
                'email' => null,
                'phones' => ['08066392235'],
                'department' => 'AGY',
                'gender' => 'F',
                'state' => null,
                'address' => 'main jibowu blck b rm309',
            ],
            [
                'name' => 'Semudara Moses',
                'email' => null,
                'phones' => ['07068907366'],
                'department' => 'URP',
                'gender' => 'M',
                'state' => null,
                'address' => 'Buga lodge',
            ],
            [
                'name' => 'Omolola Olanrewaju Patrick',
                'email' => null,
                'phones' => ['08067406486'],
                'department' => 'ARE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Arizonal quarter',
            ],
            [
                'name' => 'Aluko Tomilola',
                'email' => null,
                'phones' => ['07033661876'],
                'department' => 'FWT',
                'gender' => 'F',
                'state' => null,
                'address' => 'Succes gate villa apatapiti',
            ],
            [
                'name' => 'Daramola Olumide',
                'email' => null,
                'phones' => ['08176169218'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Dominion planet',
            ],
            [
                'name' => 'Kupohuyi Mobalaji .D',
                'email' => null,
                'phones' => ['08155003100'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Shanghai lodge aba',
            ],
            [
                'name' => 'Arogundade Olawande',
                'email' => null,
                'phones' => ['07066482105'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => '1st upstairs Aba',
            ],
            [
                'name' => 'Akinyuwa Mosunmola',
                'email' => null,
                'phones' => ['08165982290'],
                'department' => 'CSP',
                'gender' => 'F',
                'state' => null,
                'address' => 'Marrb lodge bsd accf',
            ],
            [
                'name' => 'Odudimu Oluwasegun Sam',
                'email' => null,
                'phones' => ['07063656451'],
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => 'No46 oloko street off singapor',
            ],
            [
                'name' => 'Olonisakin Akinbode',
                'email' => null,
                'phones' => ['08060888344'],
                'department' => 'BIO',
                'gender' => null,
                'state' => null,
                'address' => 'Shanghai lodge aba',
            ],
            [
                'name' => 'Oladunjoye Joshua. O',
                'email' => null,
                'phones' => ['08133174024'],
                'department' => 'CSC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Futa junction',
            ],
            [
                'name' => 'Akanji Oladipupo',
                'email' => null,
                'phones' => ['08160355277'],
                'department' => 'EMT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Royal estate annex2 off akad',
            ],
            [
                'name' => 'Abaira Kemi',
                'email' => null,
                'phones' => ['08060279520'],
                'department' => 'FST',
                'gender' => 'M',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Adeyina Fayoke Comfort',
                'email' => null,
                'phones' => ['08034783099'],
                'department' => 'FAT',
                'gender' => 'F',
                'state' => null,
                'address' => 'F&S hostel redemption road',
            ],
            [
                'name' => 'Otiko Temitope Idowu',
                'email' => null,
                'phones' => ['07064265406'],
                'department' => 'ARE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Eden lodge',
            ],
            [
                'name' => 'Oke Titus Oluwalowo',
                'email' => null,
                'phones' => ['08138553329'],
                'department' => 'MET',
                'gender' => 'M',
                'state' => null,
                'address' => 'Ebunoluwa hostel stateline',
            ],
            [
                'name' => 'Osewa Dare Joshua',
                'email' => null,
                'phones' => ['08160613889'],
                'department' => 'URP',
                'gender' => null,
                'state' => null,
                'address' => 'Oluseye villa bay duck',
            ],
            [
                'name' => 'Apolola Ayoola',
                'email' => null,
                'phones' => ['08169562051'],
                'department' => 'URP',
                'gender' => 'M',
                'state' => null,
                'address' => 'BODKEM',
            ],
            [
                'name' => 'Akinwumi Akintunde.M',
                'email' => null,
                'phones' => ['08181900484'],
                'department' => 'CVE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Off campus',
            ],
            [
                'name' => 'Aremu Adedoyin',
                'email' => null,
                'phones' => ['07034354876'],
                'department' => 'CSC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Elohim hostel',
            ],
            [
                'name' => 'Owoseni Elijah',
                'email' => null,
                'phones' => ['07067838466'],
                'department' => 'RSG',
                'gender' => 'M',
                'state' => null,
                'address' => 'Orita obele G3',
            ],
            [
                'name' => 'Adekunle Adedayo',
                'email' => null,
                'phones' => ['07067376228'],
                'department' => 'MTS',
                'gender' => 'M',
                'state' => null,
                'address' => 'Peace hostel',
            ],
            [
                'name' => 'Celestine Sunday Ben',
                'email' => null,
                'phones' => ['08161166400'],
                'department' => 'CSC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Blck c Akindeko rm11',
            ],
            [
                'name' => 'Awe Oluwapelumi Dare',
                'email' => null,
                'phones' => ['08136060839'],
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => 'Divine favour lodge apatapiti',
            ],
            [
                'name' => 'Adeniji Samuel.A',
                'email' => null,
                'phones' => ['08160896683'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => '1st upstairs Aba',
            ],
            [
                'name' => 'Oladele David',
                'email' => null,
                'phones' => ['07030840438'],
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => 'Oluseye villa bay duck',
            ],
            [
                'name' => 'Anaba Kenneth',
                'email' => null,
                'phones' => ['08132350440'],
                'department' => 'ARC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Compton Lodge',
            ],
            [
                'name' => 'Lasisi Adedayo',
                'email' => null,
                'phones' => ['07068392412'],
                'department' => 'QSV',
                'gender' => 'F',
                'state' => null,
                'address' => 'Opp energy filling station akad',
            ],
            [
                'name' => 'Onigbiende Gbenga Daniel',
                'email' => null,
                'phones' => ['08064626803'],
                'department' => 'AGE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Equity lodge',
            ],
            [
                'name' => 'Osineko Temitope',
                'email' => null,
                'phones' => ['08167197776'],
                'department' => 'QSV',
                'gender' => 'M',
                'state' => null,
                'address' => 'Adeniyi hall',
            ],
            [
                'name' => 'Aiyeyemitan Micheal',
                'email' => null,
                'phones' => ['08031890576'],
                'department' => 'AGE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Singapore lodge',
            ],
            [
                'name' => 'Victor Emehukwu',
                'email' => null,
                'phones' => ['07066128967'],
                'department' => 'APH',
                'gender' => 'M',
                'state' => null,
                'address' => 'Singapore lodge',
            ],
            [
                'name' => 'Olawale Oluwaseyi.o',
                'email' => null,
                'phones' => ['08081179199'],
                'department' => 'CSC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Adeniyi hostel',
            ],
            [
                'name' => 'Ekwueme Judith Adaku',
                'email' => null,
                'phones' => ['08065446944'],
                'department' => 'EWM',
                'gender' => 'F',
                'state' => null,
                'address' => 'Gold finger along queens hostl',
            ],
            [
                'name' => 'Adewumi Yetunde',
                'email' => null,
                'phones' => ['08066217150'],
                'department' => 'PHY',
                'gender' => 'F',
                'state' => null,
                'address' => 'F&S hostel redemption road',
            ],
            [
                'name' => 'Samuel Oluwatobiloba.T',
                'email' => null,
                'phones' => ['08090646875'],
                'department' => 'CSC',
                'gender' => 'F',
                'state' => null,
                'address' => 'Off campus',
            ],
            [
                'name' => 'Oyewumi Tolulope',
                'email' => null,
                'phones' => ['07031897044'],
                'department' => 'BCH',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jibowu',
            ],
            [
                'name' => 'Ajayi Olalekan',
                'email' => null,
                'phones' => ['07089554900'],
                'department' => 'EWM',
                'gender' => 'M',
                'state' => null,
                'address' => 'Road block area',
            ],
            [
                'name' => 'Mustapha Mariam',
                'email' => null,
                'phones' => ['07062709101'],
                'department' => 'EWM',
                'gender' => 'F',
                'state' => null,
                'address' => 'Ibula sow',
            ],
            [
                'name' => 'Okoduwa Omonefe Onyx',
                'email' => null,
                'phones' => ['07067150307'],
                'department' => 'CHE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajayi Ibunkunoluwa .M',
                'email' => null,
                'phones' => ['07039550180'],
                'department' => 'QSV',
                'gender' => 'F',
                'state' => null,
                'address' => 'North gate before deeper life',
            ],
            [
                'name' => 'Aofolaju Damilola',
                'email' => null,
                'phones' => ['08167452213'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akindeko Hall',
            ],
            [
                'name' => 'Onyeamal Tochi',
                'email' => null,
                'phones' => ['08066005995'],
                'department' => 'AGP',
                'gender' => 'M',
                'state' => null,
                'address' => 'pavilion',
            ],
            [
                'name' => 'Fagunloye Toba',
                'email' => null,
                'phones' => ['08166205146'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Evergreen lodge',
            ],
            [
                'name' => 'Adeleke Akinwumi Sanya',
                'email' => null,
                'phones' => ['08062278052'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => 'One Tree Hill',
            ],
            [
                'name' => 'Awoliyi Oladipupo',
                'email' => null,
                'phones' => ['08175524737'],
                'department' => 'AGE',
                'gender' => null,
                'state' => null,
                'address' => 'PY lodge',
            ],
            [
                'name' => 'Sallaudeen Sodiq Tunde',
                'email' => null,
                'phones' => ['08101033763'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Gods will lodge',
            ],
            [
                'name' => 'Akinnurogu Philip',
                'email' => null,
                'phones' => ['08100272069'],
                'department' => 'MTS',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Lawrence Samuel',
                'email' => null,
                'phones' => ['08025679034'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akindeko hostel',
            ],
            [
                'name' => 'Eso Ifeoluwa',
                'email' => null,
                'phones' => ['07032990716'],
                'department' => 'AEC',
                'gender' => 'F',
                'state' => null,
                'address' => 'Peculiar people lodge',
            ],
            [
                'name' => 'Ojetunde Esther',
                'email' => null,
                'phones' => ['08135684768'],
                'department' => 'FST',
                'gender' => 'F',
                'state' => null,
                'address' => 'Marrb lodge bsd accf',
            ],
            [
                'name' => 'Fabiyi Temidayo Samson',
                'email' => null,
                'phones' => ['08169166098'],
                'department' => 'AGP',
                'gender' => 'M',
                'state' => null,
                'address' => 'Vip lodge south gate',
            ],
            [
                'name' => 'Okewale Joshua',
                'email' => null,
                'phones' => ['08165707173'],
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => 'Amusement logde',
            ],
            [
                'name' => 'Olajide Oyindamola',
                'email' => null,
                'phones' => ['08074407150'],
                'department' => 'MCB',
                'gender' => 'F',
                'state' => null,
                'address' => 'Bsd unity lodge aba',
            ],
            [
                'name' => 'Adetola Bosede',
                'email' => null,
                'phones' => ['08108461434'],
                'department' => 'FST',
                'gender' => 'F',
                'state' => null,
                'address' => 'Medavam lodge',
            ],
            [
                'name' => 'Fasakin Temitope',
                'email' => null,
                'phones' => ['08106444753'],
                'department' => 'MCB',
                'gender' => 'F',
                'state' => null,
                'address' => 'Lydia street',
            ],
            [
                'name' => 'Ogunyomi Olasunkanmi',
                'email' => null,
                'phones' => ['08136703707'],
                'department' => 'RSG',
                'gender' => 'M',
                'state' => null,
                'address' => 'Koko lodge',
            ],
            [
                'name' => 'Fapouda Funmilayo',
                'email' => null,
                'phones' => ['07066514676'],
                'department' => 'FST',
                'gender' => 'F',
                'state' => null,
                'address' => 'Main jibowu rm154',
            ],
            [
                'name' => 'Okiki Israel',
                'email' => null,
                'phones' => ['08137492557'],
                'department' => 'ARC',
                'gender' => 'M',
                'state' => null,
                'address' => 'sepc lodge south gate',
            ],
            [
                'name' => 'Okon Faith',
                'email' => null,
                'phones' => ['08160067106'],
                'department' => 'FWT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Justice villa',
            ],
            [
                'name' => 'Isijola Oluwabunmi funmi',
                'email' => null,
                'phones' => ['08062975083'],
                'department' => 'MNE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jibowu annex 1 rm 119',
            ],
            [
                'name' => 'Adeseun Dorcas',
                'email' => null,
                'phones' => ['08054934829'],
                'department' => 'CSP',
                'gender' => 'F',
                'state' => null,
                'address' => 'God\'s own lodge beside fsf',
            ],
            [
                'name' => 'Ojo Seun Tosin',
                'email' => null,
                'phones' => ['08038598852'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'vera lodge off bola internatnal.',
            ],
            [
                'name' => 'Ajayi Ibunkunoluwa .D',
                'email' => null,
                'phones' => ['08096006591'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Ketaam lodge apatapiti',
            ],
            [
                'name' => 'Adebayo Temitope',
                'email' => null,
                'phones' => ['07036318798'],
                'department' => 'AGE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Willy bright opp rcf',
            ],
            [
                'name' => 'Jaiyeoba Oluwafemi. E',
                'email' => null,
                'phones' => ['20150717', '000000'],
                'department' => 'CVE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Abiola hostel',
            ],
            [
                'name' => 'Ijogun Oluwaseyi',
                'email' => null,
                'phones' => ['08138222671'],
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => 'RCF sectariate',
            ],
            [
                'name' => 'Abiola Olumide',
                'email' => null,
                'phones' => ['08186736997'],
                'department' => 'MTS',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adedapo Ifetayo Stephen',
                'email' => null,
                'phones' => ['08165959657'],
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => 'Favour of God villa roadblock',
            ],
            [
                'name' => 'Adegboyegun Oluwafemi',
                'email' => null,
                'phones' => ['08064708030'],
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => 'Abiola hostel',
            ],
            [
                'name' => 'Adefehinti Oluwole',
                'email' => null,
                'phones' => ['07064392727'],
                'department' => 'TMT',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinsulure Opeyemi',
                'email' => null,
                'phones' => ['08162787647'],
                'department' => 'APH',
                'gender' => 'M',
                'state' => null,
                'address' => 'His grace pavillon',
            ],
            [
                'name' => 'Adejun Tolulope Esther',
                'email' => null,
                'phones' => ['07038917284'],
                'department' => 'FST',
                'gender' => 'F',
                'state' => null,
                'address' => 'Marrb lodge bsd accf',
            ],
            [
                'name' => 'John Julius Oluwaleke',
                'email' => null,
                'phones' => ['07037532525'],
                'department' => 'AGP',
                'gender' => 'M',
                'state' => null,
                'address' => 'Divine lodge',
            ],
            [
                'name' => 'Awoma Segun Victor',
                'email' => null,
                'phones' => ['08134850188'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Jesus Palace',
            ],
            [
                'name' => 'Ogungbemi Paul .O',
                'email' => null,
                'phones' => ['08168338204'],
                'department' => 'FST',
                'gender' => 'M',
                'state' => null,
                'address' => 'Orita obele 2nd avenue',
            ],
            [
                'name' => 'Ogunleye Adeola',
                'email' => null,
                'phones' => ['08161139374'],
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akindeko hostl',
            ],
            [
                'name' => 'Olagbegi Segun Dayo',
                'email' => null,
                'phones' => ['08162371557'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Babanumi Oyindamola',
                'email' => null,
                'phones' => ['08167135714'],
                'department' => 'MNE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jibowu annex 1',
            ],
            [
                'name' => 'Jimoh Oluwaseun',
                'email' => null,
                'phones' => ['08137842587'],
                'department' => 'BIO',
                'gender' => 'M',
                'state' => null,
                'address' => 'Casor see',
            ],
            [
                'name' => 'Adewumi Oluwayemisi',
                'email' => null,
                'phones' => ['08162878230'],
                'department' => 'MCB',
                'gender' => 'F',
                'state' => null,
                'address' => 'Eden lodge',
            ],
            [
                'name' => 'Olajumoke Babatunde',
                'email' => null,
                'phones' => ['08167317707'],
                'department' => 'FWT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akindeko hostel block D',
            ],
            [
                'name' => 'Arowolo Funmilayo',
                'email' => null,
                'phones' => ['08162814711'],
                'department' => 'EWM',
                'gender' => 'F',
                'state' => null,
                'address' => 'Airforce 1',
            ],
            [
                'name' => 'Majaro Adedoyin Oreoluwa',
                'email' => null,
                'phones' => ['08059542406'],
                'department' => 'ARE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Off campus',
            ],
            [
                'name' => 'Shodipe Opeyemi Michael',
                'email' => null,
                'phones' => ['08167321676'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Opp energy filling station akad',
            ],
            [
                'name' => 'Bakare Moses',
                'email' => null,
                'phones' => ['08103611121'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Abiola hostel',
            ],
            [
                'name' => 'Ayeye Mojisola Omotayo',
                'email' => null,
                'phones' => ['08101839016'],
                'department' => 'CHE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Amusan Abiola',
                'email' => null,
                'phones' => ['08160897061'],
                'department' => 'STAT',
                'gender' => 'M',
                'state' => null,
                'address' => 'okala',
            ],
            [
                'name' => 'Onyenbuchi Eugene Onyeka',
                'email' => null,
                'phones' => ['08189422633'],
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => 'Lydia street',
            ],
            [
                'name' => 'Ofueu Sylvester',
                'email' => null,
                'phones' => ['08055529373'],
                'department' => 'CSC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Super lodge',
            ],
            [
                'name' => 'Abegunde Oluwaseun',
                'email' => null,
                'phones' => ['07033813601'],
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => 'God\'s will villa',
            ],
            [
                'name' => 'Afolabi Samuel',
                'email' => null,
                'phones' => ['07069114368'],
                'department' => 'MTS',
                'gender' => 'M',
                'state' => 'Kano',
                'address' => 'kanolink hostel',
            ],
            [
                'name' => 'Akinmusere Adewale',
                'email' => null,
                'phones' => ['08090772907'],
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Rescue hostel',
            ],
            [
                'name' => 'Olowonogba Temple of God',
                'email' => null,
                'phones' => ['08188155288'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Royal eagle',
            ],
            [
                'name' => 'Ogunlana Oluwaniyi',
                'email' => null,
                'phones' => ['08067386701'],
                'department' => 'QSV',
                'gender' => 'M',
                'state' => null,
                'address' => 'Off campus',
            ],
            [
                'name' => 'Awoyale Oluwafemi',
                'email' => null,
                'phones' => ['08164289247'],
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akindeko',
            ],
            [
                'name' => 'Abimbola Sunday Bukola',
                'email' => null,
                'phones' => ['08122251584'],
                'department' => 'PMT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Apatapiti',
            ],
            [
                'name' => 'Damisa Issac',
                'email' => null,
                'phones' => ['20130824', '000000'],
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => 'Gold finger along queens hostl',
            ],
            [
                'name' => 'Idowu Yemisi Mary',
                'email' => null,
                'phones' => ['08063835265'],
                'department' => 'PMT',
                'gender' => 'F',
                'state' => null,
                'address' => 'room19 capital hill',
            ],
            [
                'name' => 'Akinola Oluwafemi',
                'email' => null,
                'phones' => ['08133897744'],
                'department' => 'CSP',
                'gender' => 'M',
                'state' => null,
                'address' => 'Succes hostel',
            ],
            [
                'name' => 'Idhiarhi Evelyn Miyen',
                'email' => null,
                'phones' => ['08062890455'],
                'department' => 'MCB',
                'gender' => 'F',
                'state' => null,
                'address' => 'Annex b',
            ],
            [
                'name' => 'Obi Cypress Chijindu',
                'email' => null,
                'phones' => ['08182255426'],
                'department' => 'PMT',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinola Stephen Muyiwa',
                'email' => null,
                'phones' => ['08138599875'],
                'department' => 'MTS',
                'gender' => null,
                'state' => null,
                'address' => 'Abiola/demmama lodge',
            ],
            [
                'name' => 'Akintaro Abigel Abosede',
                'email' => null,
                'phones' => ['08101109534'],
                'department' => 'BCH',
                'gender' => 'F',
                'state' => null,
                'address' => 'Victory villa Aba',
            ],
            [
                'name' => 'Kayode Abimbola',
                'email' => null,
                'phones' => ['08160871337'],
                'department' => 'ARE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Camelot lodge',
            ],
            [
                'name' => 'Omoya Joshua Abimbola',
                'email' => null,
                'phones' => ['08036399734'],
                'department' => 'FST',
                'gender' => 'M',
                'state' => null,
                'address' => 'Rescue hostel',
            ],
            [
                'name' => 'Ajadi Omolola',
                'email' => null,
                'phones' => ['08164371029'],
                'department' => 'CHE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Fine touch lodge peace avnue',
            ],
            [
                'name' => 'Alade Bolajo Blessing',
                'email' => null,
                'phones' => ['08065680109'],
                'department' => 'ARE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Annex 1',
            ],
            [
                'name' => 'Ariyo Damilola',
                'email' => null,
                'phones' => ['07068813749'],
                'department' => 'FST',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Okafor Ayodele',
                'email' => null,
                'phones' => ['08139608549'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Succes hostel',
            ],
            [
                'name' => 'Ogundimu Olubunmi Peter',
                'email' => null,
                'phones' => ['07055384369'],
                'department' => 'MNE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Eden lodge',
            ],
            [
                'name' => 'Okpenyi Hope',
                'email' => null,
                'phones' => ['08166809362'],
                'department' => 'EWM',
                'gender' => 'F',
                'state' => null,
                'address' => 'Camelot lodge',
            ],
            [
                'name' => 'Ogunleye Victor Iyanuoluwa',
                'email' => null,
                'phones' => ['08160176476'],
                'department' => 'CHE',
                'gender' => 'M',
                'state' => null,
                'address' => 'One Tree Hill',
            ],
            [
                'name' => 'Olutade Damilola O',
                'email' => null,
                'phones' => ['08132587287'],
                'department' => 'AGY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Rm107 akindeko hostel',
            ],
            [
                'name' => 'Ogunleye Ayobami',
                'email' => null,
                'phones' => ['08161568382'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Ibironke lodge rm1',
            ],
            [
                'name' => 'Fagbemi Olalekan Ayobami',
                'email' => null,
                'phones' => ['07085316501'],
                'department' => 'MME',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Okegbemi Ebunlomo',
                'email' => null,
                'phones' => ['07069204015'],
                'department' => 'URP',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olawumi.A.oladipo',
                'email' => null,
                'phones' => ['08102381846'],
                'department' => 'MST',
                'gender' => 'M',
                'state' => null,
                'address' => 'Lydia street',
            ],
            [
                'name' => 'Akingboye Olatunde E',
                'email' => null,
                'phones' => ['07032307609'],
                'department' => 'EWM',
                'gender' => 'M',
                'state' => null,
                'address' => 'Apatapiti',
            ],
            [
                'name' => 'Adefioye Idowu',
                'email' => null,
                'phones' => ['20150926', '000000'],
                'department' => 'MCB',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Folorunso Oluwatosin',
                'email' => null,
                'phones' => ['08105071355'],
                'department' => 'SVG',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jibowu',
            ],
            [
                'name' => 'Ajayi Aanuoluwapo',
                'email' => null,
                'phones' => ['08138840725'],
                'department' => 'PMT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Futa north gate',
            ],
            [
                'name' => 'Adebayo Stephen',
                'email' => null,
                'phones' => ['08064205142'],
                'department' => 'CVE',
                'gender' => 'M',
                'state' => null,
                'address' => 'His grace pavillon',
            ],
            [
                'name' => 'Izuagie Emanuella',
                'email' => null,
                'phones' => ['07068591788'],
                'department' => 'EMT',
                'gender' => 'F',
                'state' => null,
                'address' => 'Divine grace lodge',
            ],
            [
                'name' => 'Ajisola Olabisi Temiloluwa',
                'email' => null,
                'phones' => ['07030210645'],
                'department' => 'AGY',
                'gender' => 'F',
                'state' => null,
                'address' => 'Marrb lodge bsd accf',
            ],
            [
                'name' => 'Thomas Adebusayo',
                'email' => null,
                'phones' => ['07039720135'],
                'department' => 'QSV',
                'gender' => 'M',
                'state' => null,
                'address' => 'vera lodge off bola internatnal.',
            ],
            [
                'name' => 'Olukunle Babatunde',
                'email' => null,
                'phones' => ['07067861218'],
                'department' => 'MEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Destiny lodge',
            ],
            [
                'name' => 'Aye Solomon',
                'email' => null,
                'phones' => ['08036815088'],
                'department' => 'IDD',
                'gender' => 'M',
                'state' => null,
                'address' => 'Unique lodge',
            ],
            [
                'name' => 'Ogunode Ayodeji O',
                'email' => null,
                'phones' => ['08063870248'],
                'department' => 'QSV',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akad area',
            ],
            [
                'name' => 'Samuel Oluwakemi',
                'email' => null,
                'phones' => ['08130251699'],
                'department' => 'APH',
                'gender' => 'F',
                'state' => null,
                'address' => 'Modauam hostel',
            ],
            [
                'name' => 'Ajose Olamilakan Samuel',
                'email' => null,
                'phones' => ['08066159580'],
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => 'Abiola hostel',
            ],
            [
                'name' => 'Kikiowo Bukunmi',
                'email' => null,
                'phones' => ['08062283692'],
                'department' => 'AGP',
                'gender' => 'M',
                'state' => null,
                'address' => 'Royal estate off akad',
            ],
            [
                'name' => 'Ajayi Abimbola Esther',
                'email' => null,
                'phones' => ['08103226371'],
                'department' => 'IDD',
                'gender' => 'F',
                'state' => null,
                'address' => 'Ibironke lodge',
            ],
            [
                'name' => 'Oluwayomi Oluwafunso',
                'email' => null,
                'phones' => ['08101881001'],
                'department' => 'BCH',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Daniel Kolapo Emmanuel',
                'email' => null,
                'phones' => ['08167921052'],
                'department' => 'IDD',
                'gender' => 'M',
                'state' => null,
                'address' => 'Adeniyi hostel rm108',
            ],
            [
                'name' => 'Farayibi Ayomide Adeboye',
                'email' => null,
                'phones' => ['07069334789'],
                'department' => 'TMT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akindeko hostel',
            ],
            [
                'name' => 'Ibrahim Zainab Modupe',
                'email' => null,
                'phones' => ['07033101369'],
                'department' => 'ARE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Ibironke lodge',
            ],
            [
                'name' => 'Oyekan Damilola',
                'email' => null,
                'phones' => ['08034045535'],
                'department' => 'MTS',
                'gender' => 'M',
                'state' => null,
                'address' => 'Fara Fara\'s hostel',
            ],
            [
                'name' => 'Oyeleye Timileyin Femi',
                'email' => null,
                'phones' => ['08165233705'],
                'department' => 'ARC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Succes hostel',
            ],
            [
                'name' => 'Ayoade Aderinsola',
                'email' => null,
                'phones' => ['07068372066'],
                'department' => 'ARE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Asawole Oludayo',
                'email' => null,
                'phones' => ['07062934040'],
                'department' => 'ARE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Lydia junction',
            ],
            [
                'name' => 'Adekola John Adebayo',
                'email' => null,
                'phones' => ['08130610957'],
                'department' => 'EEE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Futa junction',
            ],
            [
                'name' => 'Daramola Tolu',
                'email' => null,
                'phones' => ['08132808685'],
                'department' => 'STAT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Dorllars lodge aba',
            ],
            [
                'name' => 'Adekunle Mary Oluwatosin',
                'email' => null,
                'phones' => ['08136499768'],
                'department' => 'APH',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Akinyemi Olabode Felix',
                'email' => null,
                'phones' => ['08064540969'],
                'department' => 'STAT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Adeniyi hostel',
            ],
            [
                'name' => 'Ogannote Oyindamola',
                'email' => null,
                'phones' => ['08093683481'],
                'department' => 'BIO',
                'gender' => 'F',
                'state' => null,
                'address' => 'Bodkem',
            ],
            [
                'name' => 'Omikunle Paul Ayomide',
                'email' => null,
                'phones' => ['08096706456'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adefaye Wumi Toyin',
                'email' => null,
                'phones' => ['08064951329'],
                'department' => 'FST',
                'gender' => 'F',
                'state' => null,
                'address' => 'Alpha suite',
            ],
            [
                'name' => 'Bamidele Adedoyin',
                'email' => null,
                'phones' => ['07032308935'],
                'department' => 'BIO',
                'gender' => 'M',
                'state' => null,
                'address' => 'Apatapiti',
            ],
            [
                'name' => 'Ikusika Isaac',
                'email' => null,
                'phones' => ['08067164723'],
                'department' => 'URP',
                'gender' => 'M',
                'state' => null,
                'address' => 'frnt of sunny Ade\'s house',
            ],
            [
                'name' => 'Fatukasi Oluwaseun',
                'email' => null,
                'phones' => ['08068290060'],
                'department' => 'PMT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Justice villa',
            ],
            [
                'name' => 'Owoseni Grace.O',
                'email' => null,
                'phones' => ['08136156105'],
                'department' => 'AGP',
                'gender' => 'F',
                'state' => null,
                'address' => 'Off campus',
            ],
            [
                'name' => 'Awoyemi Olajide .o',
                'email' => null,
                'phones' => ['07033540876'],
                'department' => 'BCH',
                'gender' => 'M',
                'state' => null,
                'address' => 'Singapore lodge',
            ],
            [
                'name' => 'Awosika Tolani',
                'email' => null,
                'phones' => ['07064337147'],
                'department' => 'PHY',
                'gender' => 'F',
                'state' => null,
                'address' => 'Ketaam lodge apatapiti',
            ],
            [
                'name' => 'Fajana Oluwatosin',
                'email' => null,
                'phones' => ['08169472549'],
                'department' => 'STAT',
                'gender' => null,
                'state' => null,
                'address' => 'Royal Palace',
            ],
            [
                'name' => 'Odumuyiwa Ayobami',
                'email' => null,
                'phones' => ['08135627361'],
                'department' => null,
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinshipe Olusola T',
                'email' => null,
                'phones' => ['07066057255'],
                'department' => 'ESM',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Obayomi Ayoola Emmanuel',
                'email' => null,
                'phones' => ['07068444309'],
                'department' => 'AGP',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akindeko hostel',
            ],
            [
                'name' => 'Adefehinti Oluwasegun',
                'email' => null,
                'phones' => ['07030412234'],
                'department' => 'AGE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Lydia street off futa south gate',
            ],
            [
                'name' => 'Atugege  Matthew',
                'email' => null,
                'phones' => ['07060803405'],
                'department' => 'MTS',
                'gender' => 'M',
                'state' => null,
                'address' => 'Off campus',
            ],
            [
                'name' => 'Oladipupo Abdulwaifab',
                'email' => null,
                'phones' => ['08121463899'],
                'department' => 'TMT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Uncorruptable seed lodge',
            ],
            [
                'name' => 'Adeleke kehinde Gboyega',
                'email' => null,
                'phones' => ['20131121', '000000'],
                'department' => 'MSC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Energy lodge',
            ],
            [
                'name' => 'Oladimeji Akintomide',
                'email' => null,
                'phones' => ['08033469989'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Celebrity lodge aba',
            ],
            [
                'name' => 'Bamidele Busola',
                'email' => null,
                'phones' => ['07066516324'],
                'department' => 'ARE',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola',
            ],
            [
                'name' => 'Olaniyan Wumi Dorcas',
                'email' => null,
                'phones' => ['07062448977'],
                'department' => 'ARC',
                'gender' => 'F',
                'state' => null,
                'address' => 'Rm145 Jadesola hostel',
            ],
            [
                'name' => 'Ademiluyi Yetunde',
                'email' => null,
                'phones' => ['08136212882'],
                'department' => 'BCH',
                'gender' => 'F',
                'state' => null,
                'address' => 'Peace residnc bsd resque jctn',
            ],
            [
                'name' => 'Bajulaye Olakunle Solomon',
                'email' => null,
                'phones' => ['20131202', '000000'],
                'department' => 'MTS',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oludimu Oluwafemi',
                'email' => null,
                'phones' => ['08067752564'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Da bak Hostel',
            ],
            [
                'name' => 'Ayodele Isaac',
                'email' => null,
                'phones' => ['08038054379'],
                'department' => 'AGP',
                'gender' => 'M',
                'state' => null,
                'address' => 'Akindeko hostel',
            ],
            [
                'name' => 'Omole Tosin Elizabeth',
                'email' => null,
                'phones' => ['07038175499'],
                'department' => 'MCB',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adewale Oluwatobi',
                'email' => null,
                'phones' => ['08030811931'],
                'department' => 'STAT',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ekure Blessing O',
                'email' => null,
                'phones' => ['08036288238'],
                'department' => 'MME',
                'gender' => 'F',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Essien Rebecca Imaobong',
                'email' => null,
                'phones' => ['08169725321'],
                'department' => 'BCH',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jibowu hostel',
            ],
            [
                'name' => 'Adamu Oluwarinu Bunmi',
                'email' => null,
                'phones' => ['07086730412'],
                'department' => 'CSP',
                'gender' => 'F',
                'state' => null,
                'address' => 'Annex 1 rm 103',
            ],
            [
                'name' => 'Alli Oluwatomisin',
                'email' => null,
                'phones' => ['08181116576'],
                'department' => 'URP',
                'gender' => 'M',
                'state' => null,
                'address' => 'Succes hostel',
            ],
            [
                'name' => 'Nwaege Joshua',
                'email' => null,
                'phones' => ['07067641775'],
                'department' => 'AGE',
                'gender' => 'M',
                'state' => null,
                'address' => 'Thousand lodge alejololwo',
            ],
            [
                'name' => 'Babarinde Oluwatosin',
                'email' => null,
                'phones' => ['07038328624'],
                'department' => 'BUILDING',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Akinrinlola Temitope Mercy',
                'email' => null,
                'phones' => ['08179007915'],
                'department' => 'CSC',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Bamigbade Tobi Emmanuel',
                'email' => null,
                'phones' => ['08134188667'],
                'department' => 'QSV',
                'gender' => 'M',
                'state' => null,
                'address' => 'Executive lodge',
            ],
            [
                'name' => 'Emmanuel Emechete M',
                'email' => null,
                'phones' => ['07069120910'],
                'department' => 'MET',
                'gender' => 'M',
                'state' => 'Oyo',
                'address' => 'Felaoyo zone',
            ],
            [
                'name' => 'Idowu Joshua',
                'email' => null,
                'phones' => ['08068387381'],
                'department' => 'AGP',
                'gender' => 'M',
                'state' => null,
                'address' => 'F&S hostel redemption road',
            ],
            [
                'name' => 'Olayoriju Emmanuel',
                'email' => null,
                'phones' => ['08132388687'],
                'department' => 'EMT',
                'gender' => 'M',
                'state' => null,
                'address' => 'Jack villa',
            ],
            [
                'name' => 'Ajibike Abiodun M',
                'email' => null,
                'phones' => ['08068551731'],
                'department' => 'AEC',
                'gender' => 'M',
                'state' => null,
                'address' => 'Blk3 rm319 abiola hall',
            ],
            [
                'name' => 'Okurumeh Eguono',
                'email' => null,
                'phones' => ['08062903582'],
                'department' => 'MCB',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jibowu',
            ],
            [
                'name' => 'Omomofe Emmanuel. O',
                'email' => null,
                'phones' => ['07061030582'],
                'department' => 'ESM',
                'gender' => 'M',
                'state' => null,
                'address' => 'No46 oloko street off singapor',
            ],
            [
                'name' => 'Adediran Mercy',
                'email' => null,
                'phones' => ['08101802062'],
                'department' => 'AEC',
                'gender' => 'F',
                'state' => null,
                'address' => 'Jadesola hostel',
            ],
            [
                'name' => 'Fadodun Gabriel',
                'email' => null,
                'phones' => ['07038877586'],
                'department' => 'PHY',
                'gender' => 'M',
                'state' => null,
                'address' => 'Gren lodge rm9 alng DLC camp',
            ],
            [
                'name' => 'Doamesi Oluwole Vinyo',
                'email' => null,
                'phones' => ['08085113300'],
                'department' => 'MET',
                'gender' => 'M',
                'state' => null,
                'address' => 'Abiola hostel',
            ],
            [
                'name' => 'Omoyele Adeola Adesina',
                'email' => null,
                'phones' => ['07065865141'],
                'department' => 'URP',
                'gender' => 'M',
                'state' => null,
                'address' => 'Peace lodge bsd rcf sectariat',
            ],
            [
                'name' => 'Busari Oluwadamilare',
                'email' => null,
                'phones' => ['08132308576'],
                'department' => 'AGE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adetuyi k',
                'email' => null,
                'phones' => ['08186172096'],
                'department' => 'ARE',
                'gender' => 'M',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akerette Oluwabunmi',
                'email' => null,
                'phones' => ['07033986930'],
                'department' => 'QSV',
                'gender' => 'F',
                'state' => null,
                'address' => 'Senators lodge beside',
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
