<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class FutaStaffSeeder extends Seeder
{
    /**
     * Seed FUTA Staff and Akure Alumni from Excel file.
     * Source: Futa and Akure Alumni 2.xlsx
     */
    public function run(): void
    {
        $alumni = [
            [
                'name' => 'AYOOLA ADEOLA O.',
                'email' => 'ADEOLAAYOOLA90@YAHOO.COM',
                'phones' => ['07031175344'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'address' => 'FUTA NORTH GATE',
                'birth_date' => '2021-09-09',
                'year' => '2014-2015',
            ],
            [
                'name' => 'ADEOTI BLESSING',
                'email' => 'BADEOTI@FUTA.EDU.NG',
                'phones' => ['07035646648'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => null,
                'birth_date' => '2021-07-03',
                'year' => '2011-2012',
            ],
            [
                'name' => 'AJAYI KEHINDE OLUYEMI',
                'email' => 'OOLUYHEMIKEHINDE@YAHOO.COM',
                'phones' => ['07038990588'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'V.P/MCB FUTA',
                'birth_date' => '2021-02-17',
                'year' => '2012-2013',
            ],
            [
                'name' => 'IRAOYA AUSTINE',
                'email' => 'IRAOYAAUSTINE@GMAIL.COM',
                'phones' => ['08060831308'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => null,
                'birth_date' => '2021-08-02',
                'year' => '2013-2014',
            ],
            [
                'name' => 'OKIKI ISREAL',
                'email' => 'DESTOK@YAHOO.COM',
                'phones' => ['08137492557'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => '2021-07-07',
                'year' => '2016-2017',
            ],
            [
                'name' => 'OLUDAIRO ABOLADE',
                'email' => 'OLUDAIROABOLADE@GMAIL.COM',
                'phones' => ['07032639427'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => '2021-07-21',
                'year' => '2015-2016',
            ],
            [
                'name' => 'ISHOLA MARIAM',
                'email' => 'BIOLOLY@GMAIL.COM',
                'phones' => ['08166333825'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => '2021-03-29',
                'year' => '2016-2017',
            ],
            [
                'name' => 'MARINDOTI DAMILOLA',
                'email' => 'DAMIME4R@YAHOO.COM',
                'phones' => ['07069791825'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => '2021-06-30',
                'year' => '2015-2016',
            ],
            [
                'name' => 'OJO OLASUNKANMI',
                'email' => 'OOJO@FUTA.EDU.NG',
                'phones' => ['08060522011'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'CCE, ACCOUNTS FUTA',
                'birth_date' => '2021-03-02',
                'year' => '2002-2003',
            ],
            [
                'name' => 'OLUKUNLE OLUWATOYIN F.',
                'email' => 'OFOLUKUNLE@GMAIL.COM',
                'phones' => ['08131520638'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'DEPT OF MCB FUTA',
                'birth_date' => '2021-10-02',
                'year' => '1992-1993',
            ],
            [
                'name' => 'PHILLIP OGUNTUNDE',
                'email' => 'POGUNTUNDE@YAHOO.COM',
                'phones' => ['08163056010'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'CERAD FUTA',
                'birth_date' => '1900-01-12',
                'year' => '1996-1997',
            ],
            [
                'name' => 'DADA BOLUWATIFE',
                'email' => 'BOLUDADA77@GMAIL.COM',
                'phones' => ['08038048353'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => '2021-11-27',
                'year' => '2008-2009',
            ],
            [
                'name' => 'AYODELE ADEOLU E.',
                'email' => 'ERASHCALC@YAHOO.COM',
                'phones' => ['08030829136'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'DEPT OF PHYSICS FUTA AKURE',
                'birth_date' => '2021-05-28',
                'year' => '2002-2003',
            ],
            [
                'name' => 'AYODEJI OYASINA',
                'email' => 'AYODEJIOYASINA@YAHOO.COM',
                'phones' => ['08062434137'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'DEPT OF EST MGT FUTA',
                'birth_date' => '2021-10-27',
                'year' => '2014-2015',
            ],
            [
                'name' => 'PROF. MICHAEL O. ALATISE',
                'email' => 'MICALATISE@YAHOO.COM',
                'phones' => ['08033709379'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => null,
                'birth_date' => '2021-03-06',
                'year' => null,
            ],
            [
                'name' => 'ADEDOKUN AYOSUMBO O.',
                'email' => 'AYOADEDOKUN@GMAIL.COM',
                'phones' => ['07060467228'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => '2021-04-26',
                'year' => '2012-2013',
            ],
            [
                'name' => 'AKINPELU EMMANUEL',
                'email' => 'EAKINPELU@GMAIL.COM',
                'phones' => ['08036165652'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => '2021-08-16',
                'year' => '2014-2015',
            ],
            [
                'name' => 'AYODEJI ADEYEMI O.',
                'email' => 'YEMAYODEJI@YAHOO.COM',
                'phones' => ['08062207116'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => '2021-11-02',
                'year' => '2011-2012',
            ],
            [
                'name' => 'AJIBADE TEMITOPE',
                'email' => 'TFOTUN@FUTA.EDU.NG',
                'phones' => ['08026486252'],
                'gender' => null,
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => null,
                'year' => '2014-2015',
            ],
            [
                'name' => 'OGUNSUYI JOY',
                'email' => 'OLORUNFEMIJOY@GMAIL.COM',
                'phones' => ['08183650210'],
                'gender' => null,
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => null,
                'year' => '2014-2015',
            ],
            [
                'name' => 'SUNDAY OLUWASEUN',
                'email' => 'SSEGUN@GMAIL.COM',
                'phones' => ['07063662133'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA AKURE',
                'birth_date' => '2021-09-24',
                'year' => '2011-2012',
            ],
            [
                'name' => 'TAIWO ANUOLUWAPO S.',
                'email' => 'SAMUELTAIWOANU@YAHOO.COM',
                'phones' => ['07063283214'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'FUTA',
                'birth_date' => '2021-03-18',
                'year' => '2014-2015',
            ],
            [
                'name' => 'FASUHANMI OLUWAGBEMIGA S.',
                'email' => 'TALKTOSAMGBENGA22@GMAIL.COM',
                'phones' => ['08067817868'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'BCH/FUTA',
                'birth_date' => '2021-02-22',
                'year' => '2002-2003',
            ],
            [
                'name' => 'OGUNSUYI OPEYEMI',
                'email' => 'OBOGUNSUYI@FUTA.EDU.NG',
                'phones' => ['08067619381'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'DEPT. OF BIOMED TECH FUTA',
                'birth_date' => '2021-03-17',
                'year' => '2012-2013',
            ],
            [
                'name' => 'Bro Alex',
                'email' => null,
                'phones' => ['08037748191'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => null,
                'birth_date' => null,
                'year' => null,
            ],
            [
                'name' => 'Dr. (Mrs) Oladele',
                'email' => null,
                'phones' => ['08153033333'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'BCH/FUTA',
                'birth_date' => null,
                'year' => null,
            ],
            [
                'name' => 'Prof Alese',
                'email' => null,
                'phones' => ['08034540465'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'CSC/FUTA',
                'birth_date' => null,
                'year' => null,
            ],
            [
                'name' => 'Dr. Babadoye',
                'email' => null,
                'phones' => ['08082791819'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => null,
                'birth_date' => null,
                'year' => null,
            ],
            [
                'name' => 'Dr. Fasimirin',
                'email' => null,
                'phones' => ['08057107176'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => null,
                'birth_date' => null,
                'year' => null,
            ],
            [
                'name' => 'Prof Falayi',
                'email' => null,
                'phones' => ['08033944486'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => null,
                'birth_date' => null,
                'year' => null,
            ],
            [
                'name' => 'TAIWO, ANUOLUWAPO SAMUEL',
                'email' => null,
                'phones' => ['07063283214'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => 'Department of Metallurgical and Materials Engineering, FUTA.',
                'birth_date' => null,
                'year' => '2014-2015',
            ],
            [
                'name' => 'PROF. BADEJO',
                'email' => 'badejoaa1@yahoo.com',
                'phones' => ['81018020340'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => true,
                'current_employer' => null,
                'birth_date' => null,
                'year' => null,
            ],
            [
                'name' => 'ADEOTI JOY O.',
                'email' => 'JOYFADAMONT@GMAIL.COM',
                'phones' => ['07062045167'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-10-11',
                'year' => '2014-2015',
            ],
            [
                'name' => 'ENYICHUKWU VICTOR C.',
                'email' => 'VICTORENYICHUKWU@GMAIL.COM',
                'phones' => ['07066128967'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-06-03',
                'year' => '2007-2008',
            ],
            [
                'name' => 'AMUJO KOLADE S.',
                'email' => 'KOLADEAMUJO@GMAIL.COM',
                'phones' => ['07034285881'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-10-10',
                'year' => '2015-2016',
            ],
            [
                'name' => 'ADEDOKUN AYOBAMI O.',
                'email' => 'AYOADEDOKUN@HOTMAIL.COM',
                'phones' => ['08068118888'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-06-18',
                'year' => '2014-2015',
            ],
            [
                'name' => 'OMOTOSHO ODUNAYO',
                'email' => 'ODUNSTATA@YAHOO.COM',
                'phones' => ['07033735948'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-01-03',
                'year' => '2015-2016',
            ],
            [
                'name' => 'KOLADE OLABO F IFEOLUWA',
                'email' => 'IFEKOLADEOLUBO@GMAIL.COM',
                'phones' => ['08035614378'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-10-21',
                'year' => '2007-2008',
            ],
            [
                'name' => 'EVANG (MRS) OLAOYE FUNMILAYO',
                'email' => null,
                'phones' => ['07032058016'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => 'EMILOJU STR., FUTA',
                'birth_date' => '2021-05-05',
                'year' => '2002-2003',
            ],
            [
                'name' => 'PASTOR FAGBEMIGUN OLORUNFEMI C.',
                'email' => 'ROMOKEFEMI2014@GMAIL.COM',
                'phones' => ['08039415726'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => null,
            ],
            [
                'name' => 'MRS SANTOS ALIMI DUNNI',
                'email' => 'DUNNIAKINS55@YAHOO.COM',
                'phones' => ['07031852563'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-05-05',
                'year' => '2009-2010',
            ],
            [
                'name' => 'ADETULA YOMI V.',
                'email' => 'SERENCETCH@GMAIL.COM',
                'phones' => ['07036686565'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-09-17',
                'year' => '2015-2016',
            ],
            [
                'name' => 'AKINTAYO SUNLOLA',
                'email' => 'AKINTAYOSUNLOLA@YAHOO.COM',
                'phones' => ['08033919206'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-07-13',
                'year' => '1992-1993',
            ],
            [
                'name' => 'EMATHS O. ABIODUN',
                'email' => 'EMATHS20@GMAIL.COM',
                'phones' => ['08029050068'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => 'FUTA',
                'birth_date' => '2021-12-25',
                'year' => '2012-2013',
            ],
            [
                'name' => 'AYOOLA KAYODE',
                'email' => 'KAYOOLA202@GMAIL.COM',
                'phones' => ['08034595551'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-08-28',
                'year' => '2014-2015',
            ],
            [
                'name' => 'OLADELE DAVID O.',
                'email' => 'DAVIDCOURAGE405@GMAIL.COM',
                'phones' => ['07038336986'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-05-17',
                'year' => '2017-2018',
            ],
            [
                'name' => 'PROF. OLAWALE J. OLAKUNLE',
                'email' => 'WOLEOLUKUNLE@YAHOO.COM',
                'phones' => ['08132741068'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => 'PEACE AVENUE FUTA SOUTH GATE AKURE',
                'birth_date' => '2021-12-22',
                'year' => '1990-1991',
            ],
            [
                'name' => 'ORESANYA AYOKUNLE A.',
                'email' => 'AYOREX2703@GMAIL.COM',
                'phones' => ['08135325303'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => 'WEST END OFF FUTA SOUTH GATE AKURE',
                'birth_date' => '2021-03-27',
                'year' => '2015-2016',
            ],
            [
                'name' => 'ASEMOMEN RAYMOND',
                'email' => 'HAGIBUSINESS@GMAIL.COM',
                'phones' => ['08133645678'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-10-12',
                'year' => '2014-2015',
            ],
            [
                'name' => 'OLALEKAN BANKOLE',
                'email' => 'PINNACLE.CONCEPT@YAHOO.COM',
                'phones' => ['08036028454'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-07-28',
                'year' => '2009-2010',
            ],
            [
                'name' => 'ADEBAYO ABIMBOLA',
                'email' => 'EMPERORBIM@GMAIL.COM',
                'phones' => ['09073631362'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-02-17',
                'year' => '2015-2016',
            ],
            [
                'name' => 'AJAYI ODUNAYO M.',
                'email' => 'ODUNAYO242@GMAIL.COM',
                'phones' => ['08060949137'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => '9 EJIGBO STR, OFF FUTA SOUTH GATE',
                'birth_date' => '2021-03-24',
                'year' => '2012-2013',
            ],
            [
                'name' => 'AJAYI AYODELE O.',
                'email' => 'AYODELE0324@GMAIL.COM',
                'phones' => ['07030846493'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => '9 EJIGBO STR, OFF FUTA SOUTH GATE',
                'birth_date' => '2021-01-02',
                'year' => null,
            ],
            [
                'name' => 'JAIYEOLA GABRIEL',
                'email' => null,
                'phones' => ['08139470481'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-02-27',
                'year' => '2012-2013',
            ],
            [
                'name' => 'OLA SALAWU B.B.',
                'email' => 'OLASALAWUBUKOLA@GMAIL.COM',
                'phones' => ['08032250309'],
                'gender' => null,
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => '2000-2001',
            ],
            [
                'name' => 'UDOKWU FRANCIS',
                'email' => 'FRANCISUDOKWU@GMAIL.COM',
                'phones' => ['08060248131'],
                'gender' => null,
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => '2014-2015',
            ],
            [
                'name' => 'ADEBAYO TITILAYO',
                'email' => 'AKI4YINKA@YAHOO.COM',
                'phones' => ['07032270344'],
                'gender' => null,
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => '1999-2000',
            ],
            [
                'name' => 'OLAGUNJU TOMISIN O.',
                'email' => 'OLUWATOSINOLAGUNJU17@GMAIL.COM',
                'phones' => ['07062590884'],
                'gender' => null,
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => '2015-2016',
            ],
            [
                'name' => 'OLUKUNLE O.J',
                'email' => 'OLAWALE_OLAKUNLE@YAHOO.COM',
                'phones' => ['08132741068'],
                'gender' => null,
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => 'FUTA NORTH GATE, AKURE',
                'birth_date' => null,
                'year' => '1990-1991',
            ],
            [
                'name' => 'ADEBAYO TITTILAYO',
                'email' => 'GODGRACE@GMAIL.COM',
                'phones' => ['07032270344'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-06-20',
                'year' => '1991-1992',
            ],
            [
                'name' => 'OLADAPO OLUWAROTIMI S.',
                'email' => null,
                'phones' => ['08061529845'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => 'GREEN ROOF RCP FUTA',
                'birth_date' => '2021-04-19',
                'year' => '2014-2015',
            ],
            [
                'name' => 'ABIODUN KEHINDE S.',
                'email' => 'KEHINDESAMSON24@GMAIL.COM',
                'phones' => ['07065122367'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-10-10',
                'year' => '2015-2016',
            ],
            [
                'name' => 'ADENIYI OLUWADAMILOLA MERCY',
                'email' => 'MERCYADENIYI@GMAIL.COM',
                'phones' => ['08060880517'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => '2021-04-20',
                'year' => '2012-2013',
            ],
            [
                'name' => 'Wale Adeyemo',
                'email' => null,
                'phones' => ['07060737565'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => '2017-2018',
            ],
            [
                'name' => 'Mrs Edward',
                'email' => null,
                'phones' => ['08066641757'],
                'gender' => 'F',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => null,
            ],
            [
                'name' => 'Ademoluti Isaac',
                'email' => null,
                'phones' => ['08165295689'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => '2015-2016',
            ],
            [
                'name' => 'Akindoyo Felix Akinola',
                'email' => null,
                'phones' => ['08130561055'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => '2012-2013',
            ],
            [
                'name' => 'Shittu Oluwaseun Andrew',
                'email' => null,
                'phones' => ['08104281382'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => '7, Ofuya Close, FUTA Road, Akure, Ondo Sta',
                'birth_date' => null,
                'year' => '2017-2018',
            ],
            [
                'name' => 'Olaleye Israel',
                'email' => null,
                'phones' => ['08162072200'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => '2017-2018',
            ],
            [
                'name' => 'Abidakun Ifedayo Ayomide',
                'email' => null,
                'phones' => ['09051240140'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => null,
                'birth_date' => null,
                'year' => '2017-2018',
            ],
            [
                'name' => 'Gideon Opeyemi',
                'email' => null,
                'phones' => ['08167347972'],
                'gender' => 'M',
                'state' => 'Ondo',
                'is_futa_staff' => false,
                'current_employer' => 'Apatapiti, Futa South gate, Akure.',
                'birth_date' => null,
                'year' => '2017-2018',
            ],
        ];


        $updated = 0;
        $created = 0;

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            $year = $data['year'] ?? null;
            unset($data['year']);

            // Find existing alumnus by email or name
            $alumnus = null;
            if (!empty($data['email'])) {
                $alumnus = Alumnus::where('email', $data['email'])->first();
            }
            if (!$alumnus) {
                $alumnus = Alumnus::where('name', $data['name'])->first();
            }

            if ($alumnus) {
                // Update with new data
                $updateData = [];
                if (($data['email'] ?? null) && empty($alumnus->email)) {
                    $updateData['email'] = $data['email'];
                }
                if (($data['gender'] ?? null) && empty($alumnus->gender)) {
                    $updateData['gender'] = $data['gender'];
                }
                if (($data['state'] ?? null) && empty($alumnus->state)) {
                    $updateData['state'] = $data['state'];
                }
                if ($data['phones'] ?? null) {
                    $existingPhones = $alumnus->phones ?? [];
                    $newPhones = array_unique(array_merge($existingPhones, $data['phones']));
                    if (count($newPhones) > count($existingPhones)) {
                        $updateData['phones'] = $newPhones;
                    }
                }
                if ($data['is_futa_staff']) {
                    $updateData['is_futa_staff'] = true;
                }
                if (($data['current_employer'] ?? null) && empty($alumnus->current_employer)) {
                    $updateData['current_employer'] = $data['current_employer'];
                }
                if (!empty($updateData)) {
                    $alumnus->update($updateData);
                    $updated++;
                }
            } else {
                // Create new record
                if ($year) {
                    $tenure = Tenure::where('year', $year)->first();
                    if ($tenure) {
                        $data['tenure_id'] = $tenure->id;
                    }
                }
                Alumnus::create($data);
                $created++;
            }
        }

        $this->command->info("FUTA Staff Seeder: Updated {$updated}, Created {$created} records");
    }
}
