<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use App\Models\Department;
use Illuminate\Database\Seeder;

class HeirsOfPromiseSeeder extends Seeder
{
    /**
     * Seed Heirs of Promise (2021-2022) alumni from CSV.
     * Source: Heirs of Promise e-Database (1).csv
     */
    public function run(): void
    {
        // Get the 2021-2022 tenure
        $tenure = Tenure::where('year', '2021-2022')->first();
        
        $alumni = [
            [
                'name' => 'Olabayiwa Olayemi',
                'phones' => ['08101848624'],
                'gender' => 'M',
                'address' => 'Ogba, Ikeja Lagos State.',
                'department' => 'Agricultural Engineering',
                'birth_date' => '2000-04-23',
            ],
            [
                'name' => 'Michael Oluokun Oluwabamise',
                'phones' => ['08160509312'],
                'gender' => 'M',
                'address' => 'Mercy Hostel, Futa South Gate',
                'department' => 'Civil Engineering',
                'birth_date' => '2000-07-17',
            ],
            [
                'name' => 'Ogunrinde Blessing Omodasola',
                'phones' => ['08052402949'],
                'gender' => 'F',
                'address' => 'Federal Housing Estate igba Ondo state',
                'department' => 'Biology',
                'birth_date' => '2000-04-24',
            ],
            [
                'name' => 'Adeleye Kehinde Elizabeth',
                'phones' => ['08143267170'],
                'gender' => 'F',
                'address' => '1, Alaba Layout, Stateline',
                'department' => 'Microbiology',
                'birth_date' => '2000-02-19',
            ],
            [
                'name' => 'Favour ofure idiagbonya',
                'phones' => ['08147737360'],
                'gender' => 'F',
                'address' => 'Jibowu hostel, block 3, room 319',
                'department' => 'Agricultural extension and communication',
                'birth_date' => '2000-01-03',
            ],
            [
                'name' => 'Oladejo Oluwatayo',
                'phones' => ['07038222109'],
                'gender' => 'M',
                'address' => 'Jack lodge opposite rcf futa South gate',
                'department' => 'Biomedical Technology',
                'birth_date' => '2000-01-31',
            ],
            [
                'name' => 'Daniel Ifeoluwa Loveth',
                'phones' => ['07032328958'],
                'gender' => 'F',
                'address' => 'Grace pavilion, south gate, Akure',
                'department' => 'Crop, Soil and Pest Management',
                'birth_date' => '2000-08-28',
            ],
            [
                'name' => 'Ayodele Oluwatobi Daniel',
                'phones' => ['08106576187'],
                'gender' => 'M',
                'address' => 'FUTA South gate',
                'department' => 'Building',
                'birth_date' => '2000-06-15',
            ],
            [
                'name' => 'Aduloju Iyanuoluwa Victoria',
                'phones' => ['07062574137'],
                'gender' => 'F',
                'address' => 'Adsonic lodge RM 18 opposite fortunate canteen along caccf auditorium southgate',
                'department' => 'Information technology',
                'birth_date' => '2000-06-14',
            ],
            [
                'name' => 'Ogunkeyede Blessing Oyindamola',
                'phones' => ['09067791167'],
                'gender' => 'F',
                'address' => 'Embassy Street opposite Saint semion Anglican Church',
                'department' => 'Food Science and Technology',
                'birth_date' => '2000-02-21',
            ],
            [
                'name' => 'Joel Adeleye',
                'phones' => ['08137960011'],
                'gender' => 'M',
                'address' => 'Lagos',
                'department' => 'CSP',
                'birth_date' => '2000-02-23',
            ],
            [
                'name' => 'Adebayo Ademola',
                'phones' => ['08132423413'],
                'gender' => 'M',
                'address' => 'FUTA South gate',
                'department' => 'Industrial and production engineering',
                'birth_date' => '2000-12-27',
            ],
            [
                'name' => 'Falana Emmanuel',
                'phones' => ['08144894047'],
                'gender' => 'M',
                'address' => 'Akindeko',
                'department' => 'Agricultural engineering',
                'birth_date' => '2000-08-16',
            ],
            [
                'name' => 'Emmanuel Adelusi',
                'phones' => ['08137357554'],
                'gender' => 'M',
                'address' => '6mRWPwe7vGW6CsmXyZCukDi19tFJ9eJv1qghCsuJi7bE',
                'department' => 'Entrepreneurship(Graduate)',
                'birth_date' => '2000-06-01',
            ],
            [
                'name' => 'Victor Adeniji',
                'phones' => ['08065488247'],
                'gender' => 'M',
                'address' => 'Apatapiti southgate!',
                'department' => 'Agricultural and Environmental Engineering',
                'birth_date' => '2000-05-19',
            ],
            [
                'name' => 'Perfect Oyagwa',
                'phones' => ['09037006432'],
                'gender' => 'M',
                'address' => 'FUTA Southgate',
                'department' => 'Civil and environmental engineering',
                'birth_date' => '2000-04-23',
            ],
            [
                'name' => 'Omotoyinbo Oluwadunsin',
                'phones' => ['08189986402'],
                'gender' => 'M',
                'address' => 'Ejigbo street, South gate',
                'department' => 'Information Technology',
                'birth_date' => '2000-12-20',
            ],
            [
                'name' => 'Oke Popoola Oluwapamilerin',
                'phones' => ['08162164519'],
                'gender' => 'M',
                'address' => 'Opp Bennyrose Hotel, Southgate',
                'department' => 'Agric. Extension and Comm. Tech.',
                'birth_date' => '2000-01-20',
            ],
            [
                'name' => 'Adeyeye Faith Oluwafunmilayo',
                'phones' => ['08166266144'],
                'gender' => 'F',
                'address' => 'Rehoboth estate, futa Southgate, Akure, Ondo state.',
                'department' => 'Crop soil and pest management',
                'birth_date' => '2000-03-10',
            ],
            [
                'name' => 'Adejumo Oluwapelumi',
                'phones' => ['08174905128'],
                'gender' => 'F',
                'address' => 'Hilltop estate, aboru, iyana ipaja, Lagos',
                'department' => 'Accounting',
                'birth_date' => '2000-01-28',
            ],
            [
                'name' => 'Adebayo Glory',
                'phones' => ['07061242851'],
                'gender' => 'F',
                'address' => 'Main Jibowu, 121',
                'department' => 'SVG',
                'birth_date' => '2000-09-15',
            ],
            [
                'name' => 'Osinaike Gbemileke Iseoluwa',
                'phones' => ['08130233274'],
                'gender' => 'M',
                'address' => 'Rcf secretariat',
                'department' => 'Information Technology',
                'birth_date' => '2000-08-16',
            ],
            [
                'name' => 'Jobi',
                'phones' => ['07030856797'],
                'gender' => 'F',
                'address' => 'Lagos',
                'department' => 'Cyber security',
                'birth_date' => '2000-08-21',
            ],
            [
                'name' => 'Akinsowon Prudence',
                'phones' => ['07066864363'],
                'gender' => 'F',
                'address' => 'Home address: Abuja/Lagos',
                'department' => 'Biology',
                'birth_date' => '2000-06-25',
            ],
            [
                'name' => 'Pirisola Faith Oluwasemilore',
                'phones' => ['08181361797'],
                'gender' => 'F',
                'address' => 'Community villa beside rcf secretariat FUTA SOUTH GATE, AKURE',
                'department' => 'Agricultural and resources economics (ARE)',
                'birth_date' => '2000-06-03',
            ],
            [
                'name' => 'OLUWADUSI, SAMUEL AKINWALE',
                'phones' => ['07031108160'],
                'gender' => 'M',
                'address' => null,
                'department' => 'Crop, Soil and Peat Management (CSP)',
                'birth_date' => '2000-08-13',
            ],
            [
                'name' => 'Ajayi Oluwapelumi Esther',
                'phones' => ['08184203831', '09076241817'],
                'gender' => 'F',
                'address' => '8, Akindiya close, ota,Ogun state',
                'department' => 'Accounting',
                'birth_date' => '2000-01-31',
            ],
            [
                'name' => 'Adeyemi ayodele Daniel',
                'phones' => ['08144358551'],
                'gender' => 'M',
                'address' => 'akindeko hostel, block c room 118',
                'department' => 'Meteorology and climate science',
                'birth_date' => '2000-09-15',
            ],
            [
                'name' => 'Ojo Oluwapelumi',
                'phones' => ['09034959344'],
                'gender' => 'M',
                'address' => 'New hostel',
                'department' => 'Project Management Technology',
                'birth_date' => '2000-05-15',
            ],
            [
                'name' => 'Aruna Rachael Abisola',
                'phones' => ['09060940552'],
                'gender' => 'F',
                'address' => 'Grace lodge, Embassy Junction, FUTA Southgate.',
                'department' => 'Crop, Soil and Pest Management',
                'birth_date' => '2000-02-07',
            ],
            [
                'name' => 'Oyewole Emmanuel',
                'phones' => ['08135453620'],
                'gender' => 'M',
                'address' => 'RCF Secretariat',
                'department' => 'Information Technology',
                'birth_date' => '2000-11-17',
            ],
            [
                'name' => 'Daniel Tolu Stephen',
                'phones' => ['09033494261'],
                'gender' => 'M',
                'address' => 'RCFFuta Secretariat',
                'department' => 'Surveying and Geoinformatics',
                'birth_date' => '2000-05-13',
            ],
            [
                'name' => 'Fawehinmi kayode olaoluwa',
                'phones' => ['08068443860'],
                'gender' => 'M',
                'address' => 'Rehoboth lodge apatapiti',
                'department' => 'Animal production and health',
                'birth_date' => '2000-06-16',
            ],
            [
                'name' => 'Osobu Oluwasemiloore Grace Adefaramade',
                'phones' => ['09037411226'],
                'gender' => 'F',
                'address' => 'South Gate 
In front of Why me lodge',
                'department' => 'Meteorology and climate science',
                'birth_date' => '2000-04-19',
            ],
            [
                'name' => 'Mayaki Bukonla Rebecca',
                'phones' => ['08178398581'],
                'gender' => 'F',
                'address' => 'Lagos or Akure.',
                'department' => 'Food Science and Technology',
                'birth_date' => '2000-02-23',
            ],
            [
                'name' => 'Adepoju Ronke Mercy',
                'phones' => ['08143611894'],
                'gender' => 'F',
                'address' => 'Futa South Gate Akure',
                'department' => 'Statistics',
                'birth_date' => '2000-08-11',
            ],
            [
                'name' => 'Adeogun Joshua Fiyinfoluwa',
                'phones' => ['07039662533'],
                'gender' => 'M',
                'address' => 'Jubilee Hostel, South Gate',
                'department' => 'Civil engineering',
                'birth_date' => '2000-07-23',
            ],
            [
                'name' => 'Adekanola Israel k',
                'phones' => ['08054368197'],
                'gender' => 'M',
                'address' => 'Northgate',
                'department' => 'Physics Electronics',
                'birth_date' => '2000-01-01',
            ],
            [
                'name' => 'Oloruntola Gbolabowale Moyinoluwa',
                'phones' => ['09032788398'],
                'gender' => 'F',
                'address' => 'Jadesola Hostel',
                'department' => 'Meteorology and Climate Science',
                'birth_date' => '2000-10-10',
            ],
            [
                'name' => 'Afuye Itunu Esther',
                'phones' => ['08085081566'],
                'gender' => 'F',
                'address' => 'Royal deluxe Lodge, opposite Christian centre, Futa North gate, Akure, Ondo state',
                'department' => 'Agricultural Extension and Communication Technology',
                'birth_date' => '2000-02-22',
            ],
            [
                'name' => 'OYINLOYE GRACE ODUNAYO',
                'phones' => ['08165086717'],
                'gender' => 'F',
                'address' => 'Rm. 3 Shaba Lodge, Apatapiti. Futa southgate. Akure.',
                'department' => 'MICROBIOLOGY',
                'birth_date' => '2000-12-21',
            ],
            [
                'name' => 'Adeleke Oluwasegun',
                'phones' => ['+2348101727574'],
                'gender' => 'M',
                'address' => 'Embassy junction, FUTA South Gate, Akure',
                'department' => 'Civil Engineering',
                'birth_date' => '2000-06-29',
            ],
            [
                'name' => 'Chidiebere Alex Chijioke',
                'phones' => ['07061770261'],
                'gender' => 'M',
                'address' => '3a, ifesowapo lane Agiliti estate, mile 12 lagos',
                'department' => 'Economics',
                'birth_date' => '2000-04-29',
            ],
            [
                'name' => 'Awolusi victor',
                'phones' => ['08107132641'],
                'gender' => 'M',
                'address' => 'Akindeko Hall',
                'department' => 'Meteorology and climate science',
                'birth_date' => '2000-02-07',
            ],
            [
                'name' => 'Iwasokun samuel',
                'phones' => ['08123645142'],
                'gender' => 'M',
                'address' => 'Gbagobi street adeleye Ogun state',
                'department' => 'Computer science',
                'birth_date' => '2000-02-11',
            ],
            [
                'name' => 'Osho Victor Timilehin',
                'phones' => ['08134674187'],
                'gender' => 'M',
                'address' => 'Alejolowo, along Futa Northgate, Akure.',
                'department' => 'Food Science and Technology',
                'birth_date' => '2000-04-11',
            ],
            [
                'name' => 'Glory Ajayi',
                'phones' => ['08091778540'],
                'gender' => 'F',
                'address' => 'Lagos, Nigeria',
                'department' => 'Accounting',
                'birth_date' => '2000-01-09',
            ],
            [
                'name' => 'Oluwadamilola Adebanjo',
                'phones' => ['09036373662'],
                'gender' => 'F',
                'address' => '25, prince Aderemi street, abaranje, ikotun, lagos',
                'department' => 'Accounting',
                'birth_date' => '2000-08-19',
            ],
            [
                'name' => 'Olafare Mary Dolapo',
                'phones' => ['08133879330'],
                'gender' => 'F',
                'address' => 'Futaascoops hostel',
                'department' => 'Building',
                'birth_date' => '2000-04-25',
            ],
            [
                'name' => 'Omoboyede olajide oyeniyi',
                'phones' => ['08165022116'],
                'gender' => 'M',
                'address' => 'Power line area Akad..akure',
                'department' => 'FWT',
                'birth_date' => '2000-03-21',
            ],
            [
                'name' => 'Eniola Peter Babalola',
                'phones' => ['08148510756'],
                'gender' => 'M',
                'address' => 'Opposite P AND B LODGE, ABBA FUTA SOUTHGATE',
                'department' => 'Crop, Soil and Pest Management',
                'birth_date' => '2000-04-14',
            ],
            [
                'name' => 'Famokunro Isaac Olatunde',
                'phones' => ['08139108571'],
                'gender' => 'M',
                'address' => 'Dominion Planet Southgate',
                'department' => 'Information Technology',
                'birth_date' => '2000-07-28',
            ],
            [
                'name' => 'Fajembola Temiloluwa',
                'phones' => ['08142589506'],
                'gender' => 'M',
                'address' => 'Apatapiti south gate',
                'department' => 'Ecotourism and Wildlife Management',
                'birth_date' => '2000-12-16',
            ],
            [
                'name' => 'Oloye Oluwatooni Joshua',
                'phones' => ['08109501851'],
                'gender' => 'M',
                'address' => 'Blueroof lodge, North gate, FUTA',
                'department' => 'Electrical and Electronics Engineering',
                'birth_date' => '2000-05-06',
            ],
            [
                'name' => 'Babalola Ayomide John',
                'phones' => ['08167845079'],
                'gender' => 'M',
                'address' => 'Abiola Hostel',
                'department' => 'Cyber Security Science',
                'birth_date' => '2000-10-15',
            ],
            [
                'name' => 'Arifo Opeyemi',
                'phones' => ['08089206847'],
                'gender' => 'F',
                'address' => '20,Tinubu street, Ketu Lagos',
                'department' => 'Cyber security',
                'birth_date' => '2000-03-02',
            ],
            [
                'name' => 'Ojo Oluwaseyi Deborah',
                'phones' => ['09033767919'],
                'gender' => 'F',
                'address' => 'Araromi, Akure',
                'department' => 'Food science and technology',
                'birth_date' => '2000-06-06',
            ],
            [
                'name' => 'Adebiyi Ayobami Mercy',
                'phones' => ['07062837564'],
                'gender' => 'F',
                'address' => 'No 31, peace avenue, Oluyole estate extension, Ibadan',
                'department' => 'Human anatomy',
                'birth_date' => '2000-12-03',
            ],
            [
                'name' => 'Amole Oluwaferanmi',
                'phones' => ['+2348141270590'],
                'gender' => 'M',
                'address' => 'Ref roof beside RCF FUTA',
                'department' => 'Applied Geophysics',
                'birth_date' => '2000-04-26',
            ],
            [
                'name' => 'Ojo eniola patience',
                'phones' => ['08147832003'],
                'gender' => 'F',
                'address' => 'No 2, badges Street, ibadan',
                'department' => 'Accounting',
                'birth_date' => '2000-08-28',
            ],
            [
                'name' => 'Oluwasola Taiwo Florence',
                'phones' => ['0903935530'],
                'gender' => 'F',
                'address' => 'God\'s mercy villa,Futa southgate',
                'department' => 'Information technology',
                'birth_date' => '2000-03-12',
            ],
            [
                'name' => 'Adesuji Adedotun Amos',
                'phones' => ['08145471362'],
                'gender' => 'M',
                'address' => 'Ravena Lodge',
                'department' => 'Mechanical engineering',
                'birth_date' => '2000-09-12',
            ],
            [
                'name' => 'Adedipe Opeoluwa Louis',
                'phones' => ['07066904249'],
                'gender' => 'F',
                'address' => '107,3rd avenue, Daniel estate,Ota,Ogun state',
                'department' => 'Physics Electronic',
                'birth_date' => '2000-12-09',
            ],
            [
                'name' => 'Babatude Damilare',
                'phones' => ['08121130019'],
                'gender' => 'M',
                'address' => 'Easy Life Lodge, Alejolowo Bus-Stop, FUTA North-gate.',
                'department' => 'Crop, Soil and Pest Management',
                'birth_date' => '2000-01-19',
            ],
            [
                'name' => 'Obadero Omowunmi Esther',
                'phones' => ['07036247081'],
                'gender' => 'F',
                'address' => 'Apatapiti, Futa South gate.',
                'department' => 'Statistics',
                'birth_date' => '2000-07-05',
            ],
            [
                'name' => 'OGUNBOWALE ADURAGBEMI B',
                'phones' => ['08173584969'],
                'gender' => 'M',
                'address' => 'Behind Advance breed college, sagamu Ogun state',
                'department' => 'AGRICULTURAL AND ENVIRONMENTAL ENGINEERING',
                'birth_date' => '2000-03-11',
            ],
            [
                'name' => 'Oluseyi Daniel Oke',
                'phones' => ['08131941406'],
                'gender' => 'M',
                'address' => 'Futa north gate water street',
                'department' => 'Biochemistry',
                'birth_date' => '2000-07-20',
            ],
            [
                'name' => 'Omonlekhomhen Esther',
                'phones' => ['08166997503'],
                'gender' => 'F',
                'address' => '21 Michael Ale, Lydia Street, bennyrose area, futa South',
                'department' => 'Urban and Regional Planning',
                'birth_date' => '2000-06-27',
            ],
            [
                'name' => 'Bello Morayo',
                'phones' => ['08163421674'],
                'gender' => 'M',
                'address' => 'Woleph Lodge, FUTA South Gate, Akure',
                'department' => 'CVE',
                'birth_date' => '2000-08-03',
            ],
            [
                'name' => 'ADEYEMO TUNDE. H',
                'phones' => ['08106391194'],
                'gender' => 'M',
                'address' => 'Rcf secretariat',
                'department' => 'Statistics',
                'birth_date' => '2000-04-14',
            ],
            [
                'name' => 'Ayodele-Makun Bunmi',
                'phones' => ['08100407209'],
                'gender' => 'F',
                'address' => 'Rehoboth Lodge , South gate',
                'department' => 'Meteorology and Climate Science',
                'birth_date' => '2000-03-27',
            ],
            [
                'name' => 'Obaloyo Oluwadunsin',
                'phones' => ['09064155398'],
                'gender' => 'F',
                'address' => 'New female hostel',
                'department' => 'Architecture',
                'birth_date' => '2000-11-09',
            ],
            [
                'name' => 'Falomo Opeyemi Emmanuel',
                'phones' => ['09067298176'],
                'gender' => 'M',
                'address' => 'Futa junction',
                'department' => 'Cyber security',
                'birth_date' => '2000-05-26',
            ],
            [
                'name' => 'Omoniyi Odunayo',
                'phones' => ['08166846966'],
                'gender' => 'F',
                'address' => 'Futa south gate',
                'department' => 'Mathematical Science',
                'birth_date' => '2000-12-18',
            ],
            [
                'name' => 'Oladimeji Emmanuel',
                'phones' => ['08141661558'],
                'gender' => 'M',
                'address' => 'RCF FUTA Secretariat',
                'department' => 'Mining Engineering',
                'birth_date' => '2000-01-12',
            ],
            [
                'name' => 'Oguntoye Heritage Bisola',
                'phones' => ['07016163006'],
                'gender' => 'F',
                'address' => '25, Sule rali str igando Lagos',
                'department' => 'Crop, soil and pest management',
                'birth_date' => '2000-07-25',
            ],
            [
                'name' => 'Adanlawo olajide',
                'phones' => ['08171723880'],
                'gender' => 'M',
                'address' => 'Parvilion lodge (South Gate)',
                'department' => 'Marine science',
                'birth_date' => '2000-03-19',
            ],
            [
                'name' => 'FALEGBE PETER',
                'phones' => ['08140513793'],
                'gender' => 'M',
                'address' => 'Futa Southgate Akure Ondo State',
                'department' => 'Mechanical engineering',
                'birth_date' => '2000-06-30',
            ],
            [
                'name' => 'Ukongim',
                'phones' => ['07031598098'],
                'gender' => 'F',
                'address' => 'Life spring primary school, futa.',
                'department' => 'Mining Engineering',
                'birth_date' => '2000-05-03',
            ],
            [
                'name' => 'ADEKEHINBO TOYIN',
                'phones' => ['08140707876', '07051648588'],
                'gender' => 'F',
                'address' => 'OKUTA ELERINLA ESTATE, ILESA GARAGE',
                'department' => 'ECOTOURISM AND WILDLIFE MANAGEMENT',
                'birth_date' => '2000-03-30',
            ],
            [
                'name' => 'Adade Grace Morire',
                'phones' => ['09090313210'],
                'gender' => 'F',
                'address' => 'Futa South gate',
                'department' => 'Biochemistry',
                'birth_date' => '2000-06-08',
            ],
            [
                'name' => 'Gharoro joy',
                'phones' => ['08103735089'],
                'gender' => 'F',
                'address' => 'Futa southgate Apatapitti',
                'department' => 'Animal production and health',
                'birth_date' => '2000-05-25',
            ],
            [
                'name' => 'Jejelowo Olamide',
                'phones' => ['08109788650', '08067571259'],
                'gender' => 'F',
                'address' => 'FUTA South Gate',
                'department' => 'Food Science and Technology',
                'birth_date' => '2000-06-20',
            ],
            [
                'name' => 'Falana boluwatife Adedamola',
                'phones' => ['08087713768'],
                'gender' => 'M',
                'address' => '28, babjifr winsala street Akute ogun state.',
                'department' => 'Physics electronics',
                'birth_date' => '2000-01-04',
            ],
            [
                'name' => 'Lawal Joseph Abiodun',
                'phones' => ['09074857652'],
                'gender' => 'M',
                'address' => 'Red roof, beside rcf',
                'department' => 'Metallurgical and materials engineering',
                'birth_date' => '2000-12-29',
            ],
            [
                'name' => 'Ibukunoluwa Oyekunle',
                'phones' => ['081356210817'],
                'gender' => 'M',
                'address' => 'Mushin, Lagos State',
                'department' => 'Meteorology and Climate Science',
                'birth_date' => '2000-02-06',
            ],
            [
                'name' => 'Osobu Oluwasemiloore Grace',
                'phones' => ['09037411226'],
                'gender' => 'F',
                'address' => 'South Gate 
In front of why lodge',
                'department' => 'Meteorology and climate science',
                'birth_date' => '2000-04-19',
            ],
            [
                'name' => 'Eniola Micheal',
                'phones' => ['08168829410'],
                'gender' => 'M',
                'address' => 'South gate',
                'department' => 'Applied geology',
                'birth_date' => '2000-06-21',
            ],
            [
                'name' => 'Awoleye Bolaji',
                'phones' => ['07089118693'],
                'gender' => 'M',
                'address' => 'Red roof opposite acad filling station south gate',
                'department' => 'Computer science',
                'birth_date' => '2000-02-07',
            ],
            [
                'name' => 'Romiluyi Ayooluwa Peace',
                'phones' => ['08132479955'],
                'gender' => 'M',
                'address' => 'Peculiar people’s lodge, Stateline Southgate',
                'department' => 'Meteorology and climate science',
                'birth_date' => '2000-09-17',
            ],
            [
                'name' => 'Olusegun Ayomiposi Emmanuel',
                'phones' => ['08143146136'],
                'gender' => 'M',
                'address' => 'Akindeko  (Male hostel)',
                'department' => 'Meteorology and climate science',
                'birth_date' => '2000-12-01',
            ],
            [
                'name' => 'Olufemi timilehin Abigail',
                'phones' => ['08125792539'],
                'gender' => 'F',
                'address' => 'Peace avenue',
                'department' => 'Statistics',
                'birth_date' => '2000-08-02',
            ],
            [
                'name' => 'Kukoyi Zainab Oluwagbemisola',
                'phones' => ['09034330716'],
                'gender' => 'F',
                'address' => 'Happiness lodge,rotsam Bridge,along peace avenue, Southgate',
                'department' => 'Statistics',
                'birth_date' => '2000-08-04',
            ],
            [
                'name' => 'Adeyemi Ayodele Daniel',
                'phones' => ['08144358551'],
                'gender' => 'M',
                'address' => 'Akindeko block c room 118',
                'department' => 'Meteorology and climate science',
                'birth_date' => '2000-09-15',
            ],
            [
                'name' => 'Temitope Obisesan',
                'phones' => ['08069626476'],
                'gender' => 'M',
                'address' => 'Room K6, Ravena, Southgate',
                'department' => 'Applied Geophysics',
                'birth_date' => '2000-10-06',
            ],
            [
                'name' => 'Agbemuko Peace Ebunoluwa',
                'phones' => ['08188661246'],
                'gender' => 'F',
                'address' => 'Rcf Secretariat',
                'department' => 'Physics electronics',
                'birth_date' => '2000-05-07',
            ],
            [
                'name' => 'OWOLABI HENRY FOLAJIMI',
                'phones' => ['09036654414'],
                'gender' => 'M',
                'address' => 'Stateline road',
                'department' => 'Crop soil and pest management',
                'birth_date' => '2000-12-08',
            ],
            [
                'name' => 'DANIEL TOLU STEPHEN',
                'phones' => ['09033494261'],
                'gender' => 'M',
                'address' => 'Rcf Secretariat',
                'department' => 'Surveying and Geoinformatics',
                'birth_date' => '2000-05-13',
            ],
            [
                'name' => 'Akinwole Moses',
                'phones' => ['08185642076'],
                'gender' => 'M',
                'address' => 'Jubelee hostel beside shalom southgate',
                'department' => 'CHEMISTRY',
                'birth_date' => '2000-02-02',
            ],
            [
                'name' => 'Oluwatayo Oladejo',
                'phones' => ['07038222109'],
                'gender' => 'M',
                'address' => 'Jack lodge opp rcf futa Southgate',
                'department' => 'Biomedical Technology',
                'birth_date' => '2000-01-31',
            ],
            [
                'name' => 'Aina Samson Oluwabunmi',
                'phones' => ['08137545597'],
                'gender' => 'M',
                'address' => 'FUTA south gate, opposite his grace pavilion',
                'department' => 'Ecotourism and Wildlife Management',
                'birth_date' => '2000-09-22',
            ],
            [
                'name' => 'Jeremiah Olatunbosun',
                'phones' => ['09030594813'],
                'gender' => 'M',
                'address' => 'FUTA, Akure',
                'department' => 'Mechanical Department',
                'birth_date' => '2000-01-20',
            ],
            [
                'name' => 'Esanoluwa Victor Oluwaseun',
                'phones' => ['08129677184'],
                'gender' => 'M',
                'address' => 'Red roof, Acad, Futa, Akure.',
                'department' => 'Computer Science',
                'birth_date' => '2000-05-13',
            ],
            [
                'name' => 'OLAKANMI OLUWATOBI',
                'phones' => ['08137313000'],
                'gender' => 'M',
                'address' => 'Akindeko hall of residence',
                'department' => 'BIOMEDICAL TECHNOLOGY',
                'birth_date' => '2000-09-30',
            ],
            [
                'name' => 'Tadobo Opeyemi',
                'phones' => ['08067582899'],
                'gender' => 'F',
                'address' => 'Jadesola hostel',
                'department' => 'Building',
                'birth_date' => '2000-11-15',
            ],
            [
                'name' => 'Arinola Addo Daniel',
                'phones' => ['08133977784'],
                'gender' => 'M',
                'address' => 'Akure',
                'department' => 'Computer Engineering',
                'birth_date' => '2000-09-26',
            ],
            [
                'name' => 'Jesuferanmi Omoniyi',
                'phones' => ['07082147611'],
                'gender' => 'M',
                'address' => 'South Gate',
                'department' => 'Computer Science',
                'birth_date' => '2000-06-23',
            ],
            [
                'name' => 'Akande Tunmise',
                'phones' => ['08162342533'],
                'gender' => 'M',
                'address' => 'Futa South Gate',
                'department' => 'Agricultural Engineering',
                'birth_date' => '2000-12-06',
            ],
            [
                'name' => 'IDOKO SILAS SALEM',
                'phones' => ['09059449450'],
                'gender' => 'M',
                'address' => 'New Castle lodge',
                'department' => 'Ecotourism And wildlife management',
                'birth_date' => '2000-06-23',
            ],
            [
                'name' => 'AJAYI VICTOR TOLULOPE',
                'phones' => ['08082662108'],
                'gender' => 'M',
                'address' => 'Adeniyi hostel',
                'department' => 'Physics electronics',
                'birth_date' => '2000-01-17',
            ],
            [
                'name' => 'Oluremi Abraham',
                'phones' => ['08106004991'],
                'gender' => 'M',
                'address' => 'Stateline',
                'department' => 'Metallurgical and materials engineering',
                'birth_date' => '2000-05-25',
            ],
            [
                'name' => 'Esther Okikioluwa Odetola',
                'phones' => ['08168185195'],
                'gender' => 'F',
                'address' => 'Apatapiti, FUTA South gate',
                'department' => 'Biology',
                'birth_date' => '2000-04-11',
            ],
            [
                'name' => 'Adetunlese Adedeji',
                'phones' => ['08142980887'],
                'gender' => 'M',
                'address' => '18, Owolabi Street, Agodo Egbe, Ikotun, Lagos State.',
                'department' => 'Mechanical engineering',
                'birth_date' => '2000-11-19',
            ],
            [
                'name' => 'Richard akpama',
                'phones' => ['08176277181'],
                'gender' => 'M',
                'address' => 'Abundant grace road block',
                'department' => 'Crop soil and pest',
                'birth_date' => '2000-08-25',
            ],
            [
                'name' => 'Ologunye Enoch Temidayo',
                'phones' => ['08103308416'],
                'gender' => 'M',
                'address' => 'Singapore hostel south gate',
                'department' => 'Surveying And Geoinformatics',
                'birth_date' => '2000-03-25',
            ],
            [
                'name' => 'Olatunji Tosin Ezekiel',
                'phones' => ['07013061936'],
                'gender' => 'M',
                'address' => 'South Gate',
                'department' => 'Physics electronics',
                'birth_date' => '2000-01-16',
            ],
            [
                'name' => 'Osuntogun olanrewaju',
                'phones' => ['08034840791'],
                'gender' => 'M',
                'address' => 'Southgate',
                'department' => 'Agricultural and environmental engineering',
                'birth_date' => '2000-05-12',
            ],
            [
                'name' => 'Afuye Itunu  Esther',
                'phones' => ['08085081566'],
                'gender' => 'F',
                'address' => 'Royal deluxe Lodge,Futa North gate, Akure',
                'department' => 'Agricultural extension and communication technology',
                'birth_date' => '2000-02-22',
            ],
            [
                'name' => 'AWODIYA JOSHUA',
                'phones' => ['08149360717'],
                'gender' => 'M',
                'address' => 'SOUTH GATE AREA, HALLELUJAH HOSTEL',
                'department' => 'ECOTOURISM AND WILDLIFE MANAGEMENT',
                'birth_date' => '2000-01-09',
            ],
            [
                'name' => 'Dawodu Olamide',
                'phones' => ['08173163125'],
                'gender' => 'F',
                'address' => 'FUTA, Southgate',
                'department' => 'Crop science and pest management',
                'birth_date' => '2000-05-19',
            ],
            [
                'name' => 'Adeniyi Jesuferanmi Emmanuel',
                'phones' => ['09039669960'],
                'gender' => 'M',
                'address' => 'Apatapiti FUTA south gate',
                'department' => 'Statistics',
                'birth_date' => '2000-07-28',
            ],
            [
                'name' => 'Ilori Peter',
                'phones' => ['08174008237'],
                'gender' => 'M',
                'address' => '10,Adewole street,Eyin ogbe,Adamo,Ikorodu,Lagos State',
                'department' => 'Applied geophysics',
                'birth_date' => '2000-06-01',
            ],
            [
                'name' => 'Akinrinde Oluwaseun Oluwaseyi',
                'phones' => ['08094994804'],
                'gender' => 'M',
                'address' => 'No. 12,enitan Street,family Estate,obantoko,abeokuta,ogun state.',
                'department' => 'Mechanical Engineering',
                'birth_date' => '2000-11-25',
            ],
            [
                'name' => 'Sanni olubunmi Tolulope',
                'phones' => ['07063931935'],
                'gender' => 'F',
                'address' => 'West gate, street after capricon',
                'department' => 'Fisheries and aquaculture',
                'birth_date' => '2000-09-19',
            ],
            [
                'name' => 'Ojetunde Divine-blessing',
                'phones' => ['08107048156'],
                'gender' => 'F',
                'address' => 'South Gate',
                'department' => 'Microbiology',
                'birth_date' => '2000-02-19',
            ],
            [
                'name' => 'Odofin Oluwatimilehin Olanike',
                'phones' => ['08143157614'],
                'gender' => 'F',
                'address' => 'Room 102, Jibowu annex 2',
                'department' => 'Animal production and health',
                'birth_date' => '2000-04-06',
            ],
            [
                'name' => 'Bando David oluwasegun',
                'phones' => ['08145763020'],
                'gender' => 'M',
                'address' => 'Rcf futa Secretariat',
                'department' => 'ARE',
                'birth_date' => '2000-10-12',
            ],
            [
                'name' => 'Fayose Emmanuel',
                'phones' => ['08021363191'],
                'gender' => 'M',
                'address' => 'North Gate',
                'department' => 'Civil Engineering',
                'birth_date' => '2000-05-15',
            ],
            [
                'name' => 'Oyinlola Opeyemi Rachael',
                'phones' => ['08120106262'],
                'gender' => 'F',
                'address' => 'Stateline FUTA',
                'department' => 'Agricultural extension and communication technology',
                'birth_date' => '2000-11-02',
            ],
            [
                'name' => 'Temitope Mogboluwaga Joy',
                'phones' => ['08145417567'],
                'gender' => 'F',
                'address' => 'Rcf Secretariat',
                'department' => 'Computer Science',
                'birth_date' => '2000-04-23',
            ],
            [
                'name' => 'Esho Damilola Elizabeth',
                'phones' => ['07065076309'],
                'gender' => 'M',
                'address' => 'Opposite deeper life church apatapiti',
                'department' => 'Crop soil and pest management',
                'birth_date' => '2000-09-15',
            ],
            [
                'name' => 'Adewola Adeshola James',
                'phones' => ['09060883008'],
                'gender' => 'M',
                'address' => 'Futa south gate',
                'department' => 'Agricultural Engineering',
                'birth_date' => '2000-01-23',
            ],
            [
                'name' => 'Bamidele inioluwa',
                'phones' => ['08103245119'],
                'gender' => 'F',
                'address' => '29 Abuja lane abusoro Akure',
                'department' => 'Food science and technology',
                'birth_date' => '2000-09-29',
            ],
            [
                'name' => 'BADERINWA PELUMI EMMANUEL',
                'phones' => ['09032040036'],
                'gender' => 'M',
                'address' => 'Beside simple eateries, south gate FUTA',
                'department' => 'Food science and technology',
                'birth_date' => '2000-11-27',
            ],
            [
                'name' => 'OLORUNTOBA BOLATITO DEBORAH',
                'phones' => ['07062933490'],
                'gender' => 'F',
                'address' => 'RCF FUTA SECRETARIAT',
                'department' => 'FORESTRY AND WOOD TECHNOLOGY',
                'birth_date' => '2000-08-24',
            ],
            [
                'name' => 'Adebayo Oluwafikayomi Samuel',
                'phones' => ['07087181547'],
                'gender' => 'M',
                'address' => 'Ogba, Lagos state',
                'department' => 'Architecture',
                'birth_date' => '2000-01-15',
            ],
            [
                'name' => 'OMOTUNDE OLUWATOBILOBA .O',
                'phones' => ['09020915309'],
                'gender' => 'M',
                'address' => 'Red Roof ACAD, Southgate, FUTA',
                'department' => 'COMPUTER ENGINEERING',
                'birth_date' => '2000-03-16',
            ],
            [
                'name' => 'Great Donatus',
                'phones' => ['08164044692'],
                'gender' => 'M',
                'address' => 'Aba Bridge',
                'department' => 'Information Technology',
                'birth_date' => '2000-07-12',
            ],
            [
                'name' => 'Gbadebo Samuel',
                'phones' => ['08173511756'],
                'gender' => 'M',
                'address' => 'South gate',
                'department' => 'Computer science',
                'birth_date' => '2000-03-09',
            ],
            [
                'name' => 'OYEBANJI OMOLADE ADEOLA',
                'phones' => ['07015415368'],
                'gender' => 'F',
                'address' => 'No 16, Gaa Akanbi Ilorin',
                'department' => 'FOOD SCIENCE AND TECHNOLOGY',
                'birth_date' => '2000-04-16',
            ],
            [
                'name' => 'Ibiloye blessing',
                'phones' => ['07016749387'],
                'gender' => 'F',
                'address' => 'Jibowu',
                'department' => 'Accounting',
                'birth_date' => '2000-08-25',
            ],
            [
                'name' => 'Adetimehin Bukola',
                'phones' => ['08107979139'],
                'gender' => 'F',
                'address' => 'South Gate',
                'department' => 'Biology',
                'birth_date' => '2000-06-15',
            ],
            [
                'name' => 'Ebimaro Jessica',
                'phones' => ['08141126313'],
                'gender' => 'F',
                'address' => 'Apatapiti, South gate',
                'department' => 'Remote Sensing and GIS',
                'birth_date' => '2000-04-21',
            ],
            [
                'name' => 'Agbonifo Cornelius Oluwapelumi',
                'phones' => ['09071275066'],
                'gender' => 'M',
                'address' => '10, morinatu street ejigbo lagos',
                'department' => null,
                'birth_date' => '2000-07-15',
            ],
            [
                'name' => 'UHAKHEME KELVIN',
                'phones' => ['08128904828'],
                'gender' => 'M',
                'address' => 'Peace hostel,south gate',
                'department' => 'Transport management technology',
                'birth_date' => '2000-08-22',
            ],
            [
                'name' => 'Adedokun Amos Abiodun pka HighGuy',
                'phones' => ['0806082872007049207135'],
                'gender' => 'M',
                'address' => 'South Gate',
                'department' => 'CYS',
                'birth_date' => '2000-04-06',
            ],
            [
                'name' => 'Success Oluwaseun Kayode',
                'phones' => ['08073800629'],
                'gender' => 'M',
                'address' => 'FUTA Northgate',
                'department' => 'Crop, soil and pest management',
                'birth_date' => '2000-04-28',
            ],
            [
                'name' => 'Fayoke AKINKUADE',
                'phones' => ['08139085620'],
                'gender' => 'F',
                'address' => 'Stateline south gate',
                'department' => 'Food science and technology',
                'birth_date' => '2000-03-09',
            ],
            [
                'name' => 'Ajayi Oseyemi Mojisola',
                'phones' => ['08130201030'],
                'gender' => 'F',
                'address' => 'Futa South Gate',
                'department' => 'Project management technology',
                'birth_date' => '2000-09-06',
            ],
            [
                'name' => 'Oluwakuade Pintotina',
                'phones' => ['08144998045'],
                'gender' => 'F',
                'address' => 'Futa Southgate',
                'department' => 'Food science and technology',
                'birth_date' => '2000-02-16',
            ],
            [
                'name' => 'Diji Precious',
                'phones' => ['08112498224'],
                'gender' => 'M',
                'address' => 'South Gate',
                'department' => 'Urban and Regional Planning',
                'birth_date' => '2000-10-07',
            ],
        ];

        $updated = 0;
        $created = 0;

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            // Lookup department_id from department name
            $departmentName = $data['department'] ?? null;
            unset($data['department']);
            if ($departmentName) {
                $department = Department::where('name', 'like', '%' . $departmentName . '%')
                    ->orWhere('name', 'like', $departmentName . '%')
                    ->first();
                if ($department) {
                    $data['department_id'] = $department->id;
                }
            }

            // Find existing alumnus by name
            $alumnus = Alumnus::where('name', $data['name'])->first();
            
            if ($alumnus) {
                // Update with new data
                $updateData = [];
                if (($data['gender'] ?? null) && empty($alumnus->gender)) {
                    $updateData['gender'] = $data['gender'];
                }
                if (($data['address'] ?? null) && empty($alumnus->address)) {
                    $updateData['address'] = $data['address'];
                }
                if (($data['phones'] ?? null) && empty($alumnus->phones)) {
                    $updateData['phones'] = $data['phones'];
                }
                if (($data['birth_date'] ?? null) && empty($alumnus->birth_date)) {
                    $updateData['birth_date'] = $data['birth_date'];
                }
                if (($data['department_id'] ?? null) && empty($alumnus->department_id)) {
                    $updateData['department_id'] = $data['department_id'];
                }
                if (!empty($updateData)) {
                    $alumnus->update($updateData);
                    $updated++;
                }
            } else {
                // Create new record with 2021-2022 tenure
                if ($tenure) {
                    $data['tenure_id'] = $tenure->id;
                }
                Alumnus::create($data);
                $created++;
            }
        }

        $this->command->info("Heirs of Promise Seeder: Updated {$updated}, Created {$created} records");
    }
}
