<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class TvmAlumniSeeder extends Seeder
{
    /**
     * Seed TVM (True Vine Ministers / Choir) Alumni.
     * Data source: TVM ALUMNI LIST.docx
     */
    public function run(): void
    {
        // TVM alumni may come from various years, so we don't assign a specific tenure
        $alumni = [
            [
                'name' => 'ADEYEMO HELEN .O.',
                'phones' => ['08062963463', '08178164888'],
                'birth_date' => '2000-01-01',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINMOYE AKINWALE',
                'phones' => ['09038146128', '07088721263'],
                'birth_date' => '2000-01-01',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINBOLA OLADIMEJI',
                'phones' => ['08147112500'],
                'birth_date' => '2000-01-06',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'MAJOLAGBE OLANREWAJU',
                'phones' => ['07030736633'],
                'birth_date' => '2000-01-06',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OWOEYE TIMI',
                'phones' => ['08060166514', '08125864157'],
                'birth_date' => '2000-01-07',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OKE FEMI .F.',
                'phones' => ['08034887848'],
                'birth_date' => '2000-01-11',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'EKUNKOYA SEUN',
                'phones' => ['08069105066'],
                'birth_date' => '2000-01-14',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ONABOWALE ONABODE ELIJAH',
                'phones' => ['08066974472'],
                'birth_date' => '2000-01-17',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FAGBEMI DAMILARE A.',
                'phones' => ['08184556053', '07030418663'],
                'birth_date' => '2000-01-21',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUSOJI SARAH',
                'phones' => ['08181620062', '08100771757'],
                'birth_date' => '2000-01-21',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FABUNMI OLUMIDE',
                'phones' => ['08035859896'],
                'birth_date' => '2000-01-23',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OMOJOLA VICTOR',
                'phones' => ['07032498399'],
                'birth_date' => '2000-01-25',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AJAYI GBENGA COLLINS',
                'phones' => ['08033595273'],
                'birth_date' => '2000-01-27',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'SOBOGUN OLATUNDE',
                'phones' => ['08066223558'],
                'birth_date' => '2000-01-27',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ODUNIYI SAMUEL',
                'phones' => ['07035027164'],
                'birth_date' => '2000-01-30',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEBAYO OPEYEMI',
                'phones' => ['08137171535'],
                'birth_date' => '2000-02-04',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'BABAYEMI OLUSESAN K.',
                'phones' => ['08034801498'],
                'birth_date' => '2000-02-06',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'JEGEDE TOMILOLA',
                'phones' => ['07031251811'],
                'birth_date' => '2000-02-10',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AYENI AKOLADE .S.',
                'phones' => ['07034388257'],
                'birth_date' => '2000-02-12',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINYEMI AKINKUNLE P.',
                'phones' => ['08066906437', '08156930665'],
                'birth_date' => '2000-02-14',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGUNLEYE OLUWABUKOLA .I.',
                'phones' => ['07036746667'],
                'birth_date' => '2000-02-16',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEBAYO ABIMBOLA',
                'phones' => ['08136091134'],
                'birth_date' => '2000-02-17',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUKOLATIMI TOBI',
                'phones' => ['08105425840', '08168572538'],
                'birth_date' => '2000-02-18',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEDEJI OLUWASEYIFUNMI .S.',
                'phones' => ['08067491716', '07088449592'],
                'birth_date' => '2000-02-19',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AGORO TAIWO',
                'phones' => ['08063685885'],
                'birth_date' => '2000-02-19',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUBOWALE AJOKE',
                'phones' => ['08067302546'],
                'birth_date' => '2000-02-22',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEYEMO ABISOYE',
                'phones' => ['08104169321'],
                'birth_date' => '2000-02-24',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADENIYI KEMISOLA',
                'phones' => ['08062501885'],
                'birth_date' => '2000-02-25',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGUNLEYE OLAKUNLE',
                'phones' => ['07066122526'],
                'birth_date' => '2000-02-25',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'JAYEIOLA GABRIEL',
                'phones' => ['08139470481'],
                'birth_date' => '2000-02-27',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLOFINMOYO OLUWABUSAYOMI',
                'phones' => ['07038261495'],
                'birth_date' => '2000-02-28',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'DADA BLESSING O.',
                'phones' => ['08091507325'],
                'birth_date' => '2000-02-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'SOBOLA AYOTUNDE',
                'phones' => ['08023238875'],
                'birth_date' => null,
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINTELURE BUKOLA',
                'phones' => ['07032305818'],
                'birth_date' => '2000-03-02',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OPAYINKA OLUWASANJO J.',
                'phones' => ['08132129111', '080870709198'],
                'birth_date' => '2000-03-03',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINLUDE SEYI',
                'phones' => ['08138433226'],
                'birth_date' => '2000-03-05',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FAMAKINWA MICHAEL',
                'phones' => ['07033284447', '08094217997'],
                'birth_date' => '2000-03-10',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLOPADE ADEBAYO SOLA',
                'phones' => ['07039390218'],
                'birth_date' => '2000-03-12',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AWE OLUWAYOMI',
                'phones' => ['08056179816'],
                'birth_date' => '2000-03-17',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGBOLU BENJAMIN O.',
                'phones' => ['07032662092'],
                'birth_date' => '2000-03-17',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AJAYI DAMILOLA E.',
                'phones' => ['08133821032', '08177547917'],
                'birth_date' => '2000-03-22',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ANIFOWOSE FOLUKE',
                'phones' => ['08171352396'],
                'birth_date' => '2000-03-13',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEDEJI FUNMI. C',
                'phones' => ['08067647317'],
                'birth_date' => '2000-03-24',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEGBITE AYOMIDE',
                'phones' => ['08181488790'],
                'birth_date' => '2000-03-25',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ODETUNDE LANRE',
                'phones' => ['08189497925', '08082033583'],
                'birth_date' => '2000-03-28',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGUNTAYO ESTHER',
                'phones' => ['09039213918'],
                'birth_date' => '2000-03-31',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGUNDIPE TUNDE (T-BASS)',
                'phones' => ['08035963873'],
                'birth_date' => '2000-04-01',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OKUNLOLA FIYINFOLUWA. S',
                'phones' => ['08038556197'],
                'birth_date' => '2000-04-01',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AZIKE CHINYERE. B',
                'phones' => ['08056854234', '08136971891'],
                'birth_date' => '2000-04-04',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OJOLO GBENGA T.',
                'phones' => ['07033958225'],
                'birth_date' => '2000-04-04',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLANREWAJU TUNDE',
                'phones' => ['07032479706', '08082358006'],
                'birth_date' => '2000-04-04',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OSHO BANKOLE JOSHUA',
                'phones' => ['08035799932'],
                'birth_date' => '2000-04-04',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AJIBOLA TEMIDAYO',
                'phones' => ['07033320543'],
                'birth_date' => '2000-04-04',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADESUYI TOSIN',
                'phones' => ['08067117237'],
                'birth_date' => '2000-04-07',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OBISESAN IFEOLUWA',
                'phones' => ['07037901602'],
                'birth_date' => '2000-04-07',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ODANYE OLUWABUNMI. B',
                'phones' => ['08062795444', '08028966406'],
                'birth_date' => '2000-04-08',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AGUNBIADE OLUWAFEMI. J',
                'phones' => ['08036456199'],
                'birth_date' => '2000-04-09',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ODEWOLE OLUWATOMIWA',
                'phones' => ['08063222359'],
                'birth_date' => '2000-04-09',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'SOBOLA MICHAEL',
                'phones' => ['08037827476', '080542029282'],
                'birth_date' => '2000-04-13',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUPONA TAYO',
                'phones' => ['07062660497'],
                'birth_date' => '2000-04-16',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEMUWAGUN PAUL. O',
                'phones' => ['08035889086'],
                'birth_date' => '2000-04-18',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'UMEH PETER ABIDEMI',
                'phones' => ['07060971948'],
                'birth_date' => '2000-04-22',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEGBORO SANMI',
                'phones' => ['08101501553'],
                'birth_date' => '2000-04-22',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FAJIMETE OLAYINKA. E',
                'phones' => ['08029265121'],
                'birth_date' => '2000-04-23',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEDOKUN AYOSUNBO',
                'phones' => ['07060467228'],
                'birth_date' => '2000-04-26',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OJO PRECIOUS ADEFUNKE',
                'phones' => ['07065572128'],
                'birth_date' => '2000-04-26',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEKUNLE ADEBIMPE. B',
                'phones' => ['07066295209'],
                'birth_date' => '2000-05-01',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AYOOLA AYOTUNDE',
                'phones' => ['07033980855', '08029017086'],
                'birth_date' => '2000-05-02',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OWOEYE TEMITOPE',
                'phones' => ['09033494696'],
                'birth_date' => '2000-05-02',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ASHAJU ABIMBOLA. S',
                'phones' => ['08062302107'],
                'birth_date' => '2000-05-03',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'HAASTRUP ADEDOYIN',
                'phones' => ['08029096564', '08030751090'],
                'birth_date' => '2000-05-04',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLAJIDE ADEMOLA',
                'phones' => ['08106174438'],
                'birth_date' => '2000-05-07',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OYEYEMI KEMISOLA',
                'phones' => ['08166135613'],
                'birth_date' => '2000-05-07',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEKOYA ADENIKE',
                'phones' => ['08034995413', '07056713756'],
                'birth_date' => '2000-05-10',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ODUDIMU OLUWASEGUN .S.',
                'phones' => ['08021191787', '07063656451'],
                'birth_date' => '2000-05-11',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEGBOYEGA TAIWO',
                'phones' => ['08039123739'],
                'birth_date' => '2000-05-11',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OYEYIOLA OYEDOYIN',
                'phones' => ['08066337070'],
                'birth_date' => '2000-05-13',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'BADMUS OLUFUNKE',
                'phones' => ['07036361316'],
                'birth_date' => '2000-05-13',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUWALEYE ADELEKE JOSEPH',
                'phones' => ['08063040378', '07040405224'],
                'birth_date' => '2000-05-14',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'EGBEYEYE IFEOLUWA M.',
                'phones' => ['08061330901'],
                'birth_date' => '2000-05-16',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEYINA FAYOKEMI COMFORT',
                'phones' => ['08034783099'],
                'birth_date' => '2000-05-17',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FAGBAMIGBE TAIWO',
                'phones' => ['07035618487'],
                'birth_date' => '2000-05-20',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEOTI ISRAEL',
                'phones' => ['08102564922'],
                'birth_date' => '2000-05-21',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OWOLABI ADEDOTUN. J',
                'phones' => ['08066049294'],
                'birth_date' => '2000-05-23',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADARAMOLA GIDEON',
                'phones' => ['07032827407'],
                'birth_date' => '2000-05-25',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEATE BANKE RUTH',
                'phones' => ['08076312667', '07069569425'],
                'birth_date' => '2000-05-25',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGBEIWI SEUN',
                'phones' => ['07039180356'],
                'birth_date' => '2000-05-27',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINYELU TINUKE (TK)',
                'phones' => ['08028859023'],
                'birth_date' => '2000-05-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUWATOBI ADEFISAN',
                'phones' => ['08134150545'],
                'birth_date' => '2000-06-01',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OYESOMI ROTIMI',
                'phones' => null,
                'birth_date' => '2000-06-02',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'TOGUN JOHN A.',
                'phones' => ['08061684326'],
                'birth_date' => '2000-06-04',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLAWUYI SAMUEL',
                'phones' => ['08031174163'],
                'birth_date' => '2000-06-04',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'POPOOLA YETUNDE',
                'phones' => ['07035658795'],
                'birth_date' => '2000-06-11',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'BAKARE  TOLULOPE .S.',
                'phones' => ['07032571962'],
                'birth_date' => '2000-06-11',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUKOYA OLUDOTUN',
                'phones' => ['08062373941'],
                'birth_date' => '2000-06-13',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ELEHINLE FOLASHADE',
                'phones' => ['08037041427'],
                'birth_date' => '2000-06-13',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLATOMIRIN OLOLADE O.',
                'phones' => ['07035015251'],
                'birth_date' => '2000-06-15',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ESAN FOLAKEMI (FLAKY J)',
                'phones' => ['080336173058'],
                'birth_date' => '2000-06-16',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKRAN ABOSEDE MODUPE',
                'phones' => ['07084045929'],
                'birth_date' => '2000-06-17',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'BADEJO JOSHUA',
                'phones' => ['08160489973'],
                'birth_date' => '2000-06-24',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEPOJU ADEDAYO',
                'phones' => ['08161133757'],
                'birth_date' => '2000-06-24',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEYO DUNSIN ELIZABETH',
                'phones' => ['07033321356'],
                'birth_date' => '2000-07-07',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AYODELE GBENGA',
                'phones' => ['07036649090'],
                'birth_date' => '2000-07-07',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FAGBOHUN OLUWATUNMISE',
                'phones' => ['08038000903'],
                'birth_date' => '2000-07-08',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADESEUN EBUNOLUWA .D.',
                'phones' => ['08054934829', '08167466211'],
                'birth_date' => '2000-07-14',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ALO DOLAPO',
                'phones' => ['07030440383'],
                'birth_date' => '2000-07-15',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINKUNMI TOLULOPE',
                'phones' => ['08036957592'],
                'birth_date' => '2000-07-16',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLAIYA TOLUWANI',
                'phones' => ['+353863215693'],
                'birth_date' => '2000-07-20',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEDAPO IFETAYO STEPHEN',
                'phones' => ['08037862189'],
                'birth_date' => '2000-07-20',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINWOLE OLUWASEUNFUNMI',
                'phones' => ['08036129008'],
                'birth_date' => '2000-07-21',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'RAWA OLUTAYO OLUSEYI',
                'phones' => ['08038525626', '07081174627'],
                'birth_date' => '2000-07-23',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGUNGBE MICHAEL',
                'phones' => ['08114301280'],
                'birth_date' => '2000-07-23',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGUNJI ABOSEDE OLUWASEUN',
                'phones' => ['08138492079', '08088667318'],
                'birth_date' => '2000-07-25',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEJUMO BUNMI',
                'phones' => ['08033861358'],
                'birth_date' => '2000-08-01',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADETUNJI SAMSON FEMI',
                'phones' => ['08053059353'],
                'birth_date' => '2000-08-19',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OYEWUNMI SAMSON. T',
                'phones' => ['08037925716'],
                'birth_date' => '2000-08-22',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLONIYO SEUN',
                'phones' => ['08132129140'],
                'birth_date' => '2000-08-25',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OWOSENI MICHEAL',
                'phones' => ['08137898794'],
                'birth_date' => '2000-08-27',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLAGUNJU OLUWATOMISIN',
                'phones' => ['07062590884'],
                'birth_date' => '2000-08-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OJO TIMILEHIN',
                'phones' => ['08034397019'],
                'birth_date' => '2000-09-02',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEBUNMI FUNMILAYO',
                'phones' => ['08080706528'],
                'birth_date' => '2000-09-03',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADUBI TEMITOPE',
                'phones' => ['07065597080'],
                'birth_date' => '2000-10-03',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINTARO ABIGAEL ABOSEDE',
                'phones' => ['08101109534'],
                'birth_date' => '2000-09-03',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AYEBODE VICTOR',
                'phones' => ['08167997025'],
                'birth_date' => '2000-09-06',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'UCHENNA JAMES',
                'phones' => ['08100427990'],
                'birth_date' => '2000-09-07',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ISAAC',
                'phones' => ['08032523465'],
                'birth_date' => '2000-09-09',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AYOOLA ADEOLA O.',
                'phones' => ['07031175344', '08079950150', '+8618801257457'],
                'birth_date' => '2000-09-09',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINSUYI OLAYEMI',
                'phones' => ['08132962361'],
                'birth_date' => '2000-09-13',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINJOLE LYDIA',
                'phones' => ['08037544669'],
                'birth_date' => '2000-09-13',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FALOWO OLUWAGBEMINIYI',
                'phones' => ['08030789669'],
                'birth_date' => '2000-09-18',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEWUSI OPEYEMI',
                'phones' => ['08062204693'],
                'birth_date' => '2000-09-19',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLATOKUNBO OLALEKAN',
                'phones' => ['08086940881'],
                'birth_date' => '2000-09-19',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'IGBALAJOBI OLATUNBOSUN',
                'phones' => ['08074571053', '09059020873'],
                'birth_date' => '2000-09-23',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OVADA OLUWATOSIN D.',
                'phones' => ['08062747963'],
                'birth_date' => '2000-09-22',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'SUNDAY OLUWASEUN R.',
                'phones' => ['08138337756'],
                'birth_date' => '2000-09-24',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUWADARE OLUWATOSIN',
                'phones' => ['08038374104'],
                'birth_date' => '2000-09-25',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'BAYODE JIDE',
                'phones' => ['08064986211'],
                'birth_date' => '2000-09-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OMIOGBEMI DEBORAH',
                'phones' => ['08025322910'],
                'birth_date' => '2000-09-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGUNMILADE JOSEPH SOLA',
                'phones' => ['08030466036'],
                'birth_date' => '2000-09-30',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ILUYEMI VICTOR',
                'phones' => ['08160002590'],
                'birth_date' => '2000-09-30',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AGBOOLA TOMIWA',
                'phones' => ['08053505901'],
                'birth_date' => '2000-10-01',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'IZUAGIE EMMANUELLA .E.',
                'phones' => ['07068591788'],
                'birth_date' => '2000-10-02',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AJISOLA OLABISI .T.',
                'phones' => ['07030210645'],
                'birth_date' => '2000-10-03',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'MEDOYE OLUSOJI',
                'phones' => ['08033487856'],
                'birth_date' => '2000-10-03',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'KIKEKON OLUGBENGA',
                'phones' => ['07038121175'],
                'birth_date' => '2000-10-08',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEFARAKAN TONY',
                'phones' => ['08067985910'],
                'birth_date' => '2000-10-09',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'BAKARE OLALEKAN OLUSEYI',
                'phones' => ['07040169040'],
                'birth_date' => '2000-10-10',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKEJU OSUOLALE',
                'phones' => ['07038243809'],
                'birth_date' => '2000-10-11',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ABIDAKUN IFEDAYO',
                'phones' => ['09051240140'],
                'birth_date' => '2000-10-11',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'NZETEH NWAKAEGO',
                'phones' => ['07034672256'],
                'birth_date' => '2000-10-12',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AWE BOLADELE',
                'phones' => ['08037794748'],
                'birth_date' => '2000-10-14',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINBINU BUKOLA',
                'phones' => ['07038625295'],
                'birth_date' => '2000-10-15',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'BABALOLA AYODEJI',
                'phones' => ['08169472518', '08091590416'],
                'birth_date' => '2000-10-15',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUWAGBAMI TOBA .S',
                'phones' => ['07060490935', '08024160184'],
                'birth_date' => '2000-10-15',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADESANMI VICTOR ADEOLU',
                'phones' => ['08039717513'],
                'birth_date' => '2000-10-15',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AJAYI OLALEKAN (DEDUNNKE)',
                'phones' => ['08033970544', '08057782996'],
                'birth_date' => '2000-10-16',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADELUGBA OLORUNTOBA',
                'phones' => ['08039774539'],
                'birth_date' => '2000-10-19',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINWANDE TOLUWANI SEUN',
                'phones' => ['07030424829'],
                'birth_date' => '2000-10-20',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'TAYLOR-HARRY TINA',
                'phones' => ['08067083039'],
                'birth_date' => '2000-10-21',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEWUMI OLUWATOSIN',
                'phones' => ['08164024128'],
                'birth_date' => '2000-10-22',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADELUYI OLUWAYEMISI',
                'phones' => ['07030670669'],
                'birth_date' => '2000-10-22',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AJELE OMOLARAMI',
                'phones' => ['08132128966'],
                'birth_date' => '2000-10-22',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'LAWANI IBIYEMI .O',
                'phones' => ['08064406319'],
                'birth_date' => '2000-10-23',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGUNRUKU ESTHER',
                'phones' => ['08069172851', '08060635417'],
                'birth_date' => '2000-10-23',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AKINBISOSE AKINWUNMI D.',
                'phones' => ['08165661465'],
                'birth_date' => '2000-10-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ALABI SARAH',
                'phones' => ['08020709921'],
                'birth_date' => '2000-10-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADELODUN BLESSING',
                'phones' => ['07052616079'],
                'birth_date' => '2000-10-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AYODEJI ADEYEMI. O',
                'phones' => ['08062207116'],
                'birth_date' => '2000-11-02',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FESOBI MOYINOLUWA',
                'phones' => ['08133956186'],
                'birth_date' => '2000-11-02',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUGBARO CHARLES',
                'phones' => ['08188907434'],
                'birth_date' => '2000-11-06',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OBABUEKI OSARUME',
                'phones' => ['08084718291', '07066033222'],
                'birth_date' => '2000-11-07',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLAWANDE BUKOLA',
                'phones' => ['08066392495', '08058514292'],
                'birth_date' => '2000-11-11',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'JESUYON EMMANUEL O.',
                'phones' => ['08139520479', '08181915593'],
                'birth_date' => '2000-11-12',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OWOSENI TEMIDAYO. K',
                'phones' => ['08136123786'],
                'birth_date' => '2000-11-14',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'SHONEYE OLUWASHOLA. D',
                'phones' => ['07036443961', '08058143349'],
                'birth_date' => '2000-11-18',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLANIYAN VICTOR',
                'phones' => ['07036443961', '08155536570'],
                'birth_date' => '2000-11-19',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLADIPUPO ABDULWAHAB .O.',
                'phones' => ['08081000529', '09091270207'],
                'birth_date' => '2000-11-20',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ARIYO BLESSING',
                'phones' => ['08135770365'],
                'birth_date' => '2000-11-22',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEDOKUN OLUWASEYI',
                'phones' => ['08035592650'],
                'birth_date' => '2000-11-24',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ALO AYOPO',
                'phones' => ['07030077119'],
                'birth_date' => '2000-11-26',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'BAMIDELE JULIAN',
                'phones' => ['08033807456'],
                'birth_date' => '2000-11-27',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'UHAKHEME PRECIOUS',
                'phones' => ['07031872381'],
                'birth_date' => '2000-11-28',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLANIYAN OLAWUNMI .D.',
                'phones' => ['07062448977'],
                'birth_date' => '2000-11-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OMOLE BOLUWATIFE',
                'phones' => ['08038048353'],
                'birth_date' => '2000-11-27',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEMOLA BLESSING. O',
                'phones' => ['08032509453'],
                'birth_date' => '2000-11-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEBAYO (AWOFESO) SESAN',
                'phones' => ['08037504159', '07025889634'],
                'birth_date' => '2000-12-02',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AYENI TEMIDAYO',
                'phones' => ['08030422426'],
                'birth_date' => '2000-12-02',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AMOO OLADELE',
                'phones' => ['08028227909', '08067763811'],
                'birth_date' => '2000-12-03',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'EKURE BLESSING O.',
                'phones' => ['08143931006'],
                'birth_date' => '2000-12-08',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'KAFARU SIMILEOLUWA',
                'phones' => ['08032900274'],
                'birth_date' => '2000-12-08',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FAWOLE OLAOLUWA F.',
                'phones' => ['07065312405'],
                'birth_date' => '2000-12-12',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'BABARINDE OLUWATOSIN .M.',
                'phones' => ['07038328624'],
                'birth_date' => '2000-12-14',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OYEBAMIJI DOTUN',
                'phones' => ['08050980259', '08168101621'],
                'birth_date' => '2000-12-16',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'DARE ABIODUN',
                'phones' => ['08109039949'],
                'birth_date' => '2000-12-18',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OSAYANDE VICTORIA',
                'phones' => ['08032210661'],
                'birth_date' => '2000-12-21',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AJIBIKE ABIODUN .M.',
                'phones' => ['08068551731'],
                'birth_date' => '2000-12-21',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'YUSUF ABIODUN',
                'phones' => ['07036639218'],
                'birth_date' => '2000-12-23',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGUNLEKE BLESSING',
                'phones' => ['08135770365'],
                'birth_date' => '2000-12-23',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OMOMOFE EMMANUEL',
                'phones' => ['407061030582'],
                'birth_date' => '2000-12-24',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLONADE OLUWASEGUN',
                'phones' => ['08034474864', '07034027523'],
                'birth_date' => '2000-12-26',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OBAKPOLOR ABIODUN',
                'phones' => ['08066400176'],
                'birth_date' => '2000-12-27',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLALEKAN OLABODE ABIODUN',
                'phones' => ['08063453847'],
                'birth_date' => '2000-12-27',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FADODUN GABRIEL',
                'phones' => ['08134676609'],
                'birth_date' => '2000-12-28',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUDIMU OLUWATOBI',
                'phones' => ['08069696617'],
                'birth_date' => '2000-12-28',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OYEWUSI MICHAEL',
                'phones' => ['08054470323', '08061391911'],
                'birth_date' => '2000-12-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OLUMOKO FRANCIS',
                'phones' => ['08063903438'],
                'birth_date' => '2000-12-29',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OMOYELE ADEOLA .A.',
                'phones' => ['07065865141'],
                'birth_date' => '2000-12-31',
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'OGUNWO MOSUN',
                'phones' => ['08035781878'],
                'birth_date' => null,
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'AWOSEMO MOTUNRAYO',
                'phones' => ['08035768018'],
                'birth_date' => null,
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEWUNMI SADE',
                'phones' => ['08052254507'],
                'birth_date' => null,
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ORIMOGUNJE TOYIN',
                'phones' => ['08038216520'],
                'birth_date' => null,
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'ADEBAYO BANKOLE (TALLEST)',
                'phones' => ['08030695742'],
                'birth_date' => null,
                'unit' => 'Choir Unit',
            ],
            [
                'name' => 'FAJEMILEHIN YEMI',
                'phones' => null,
                'birth_date' => null,
                'unit' => 'Choir Unit',
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            // Try to find existing alumnus by phones or name
            $alumnus = null;
            if (!empty($data['phones'][0])) {
                $alumnus = Alumnus::whereJsonContains('phones', $data['phones'][0])->first();
            }
            if (!$alumnus) {
                $alumnus = Alumnus::where('name', $data['name'])->first();
            }

            if ($alumnus) {
                // Update unit to Choir Unit (TVM)
                $alumnus->update(['unit' => 'Choir Unit']);
            } else {
                // Create new record without tenure
                Alumnus::create($data);
            }
        }

        $this->command->info('Seeded TVM Alumni: ' . count($alumni) . ' records');
    }
}
