<?php

namespace Database\Seeders\AlumniSeeder;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2003_2004Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2003-2004'],
            [
                'name' => 'That I may Know Him Generation',
                'family_name' => 'Peculiar FAMILY'
            ]
        );

        $alumni = [
            [
                'name' => 'ABOABA OLANREWAJU',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => null,
                'birth_date' => '2000-11-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABODUNDE DOLAPO',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => null,
                'birth_date' => '2000-12-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADE-ODUMBONI ADELEKE',
                'email' => null,
                'phones' => null,
                'department_id' => 3,
                'gender' => null,
                'birth_date' => '2000-06-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBAYO BANKOLE',
                'email' => null,
                'phones' => null,
                'department_id' => 8,
                'gender' => null,
                'birth_date' => '2000-06-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBOYEGA MAYOKUN',
                'email' => null,
                'phones' => null,
                'department_id' => 38,
                'gender' => null,
                'birth_date' => '2000-05-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIRAN PETER',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => null,
                'birth_date' => '2000-03-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESIDA ABIODUN',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-12-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETAYO BABATUNDE',
                'email' => null,
                'phones' => null,
                'department_id' => 13,
                'gender' => null,
                'birth_date' => '2000-07-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUMI FOLASADE',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-10-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEYE FESTUS',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => null,
                'birth_date' => '2000-07-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFOLALU ADENIRAN',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => null,
                'birth_date' => '2000-12-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AINA ABAYOMI',
                'email' => null,
                'phones' => null,
                'department_id' => 11,
                'gender' => null,
                'birth_date' => '2000-02-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI ADENIYI',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-12-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJENIFUJA KELVIN',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-09-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJUMOBI OLUMAYOWA',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => null,
                'birth_date' => '2000-12-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKANO OLAKUNLE',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => null,
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOLA BOLANLE',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => null,
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOLA FRANK',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-04-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOLA TEMIDAYO',
                'email' => null,
                'phones' => null,
                'department_id' => 38,
                'gender' => null,
                'birth_date' => '2000-07-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALEXANDER ADESHINA',
                'email' => null,
                'phones' => null,
                'department_id' => 41,
                'gender' => null,
                'birth_date' => '2000-12-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALIU OLUWATOYIN',
                'email' => null,
                'phones' => null,
                'department_id' => 11,
                'gender' => null,
                'birth_date' => '2000-04-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALONGE JOSEPHINE',
                'email' => null,
                'phones' => null,
                'department_id' => 38,
                'gender' => null,
                'birth_date' => '2000-06-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARINDE FUNSHO',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => null,
                'birth_date' => '2000-01-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOFISOYE B.O',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => null,
                'birth_date' => '2000-01-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BADA ABOSEDE',
                'email' => null,
                'phones' => null,
                'department_id' => 11,
                'gender' => null,
                'birth_date' => '2000-09-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'CLARKE OKAH W.E',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-01-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EGBOBI K.O',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => null,
                'birth_date' => '2000-12-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EJIOFOR NKIRUKA',
                'email' => null,
                'phones' => null,
                'department_id' => 7,
                'gender' => null,
                'birth_date' => '2000-10-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ELEHINTE YEMISI',
                'email' => null,
                'phones' => null,
                'department_id' => 38,
                'gender' => null,
                'birth_date' => '2000-10-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAKOREDE ADESOJI',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => null,
                'birth_date' => '2000-09-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALEYE TAYO',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => null,
                'birth_date' => '2000-08-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IBINI OLUMIDE',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => null,
                'birth_date' => '2000-10-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ILAYA ANDREW',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => null,
                'birth_date' => '2000-04-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ISARINDE ISIAH',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => null,
                'birth_date' => '2000-04-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ISIMIJOLA OLUWATOYIN',
                'email' => null,
                'phones' => null,
                'department_id' => 13,
                'gender' => null,
                'birth_date' => '2000-06-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IWAYE CHRISTIANAH',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => null,
                'birth_date' => '2000-04-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KAYODE TEMITOPE',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => null,
                'birth_date' => '2000-05-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LERAMO PETER',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => null,
                'birth_date' => '2000-12-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'NATHANIEL SEGUN',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => null,
                'birth_date' => '2000-07-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNBANJO YOMI',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => null,
                'birth_date' => '2000-04-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNGBMILA TOKUNBO',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-01-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLANA ADEBOYE',
                'email' => null,
                'phones' => null,
                'department_id' => 38,
                'gender' => null,
                'birth_date' => '2000-06-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNTOLA SEUN',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-03-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNYE AYOYEMI',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => null,
                'birth_date' => '2000-10-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO EZEIKEL',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => null,
                'birth_date' => '2000-04-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO WURAOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-03-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJOADE OLUWASEYI',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => null,
                'birth_date' => '2000-07-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKUWOBI ADEWALE',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => null,
                'birth_date' => '2000-05-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLA MONISOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-02-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLALUDE IFEDAYO',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => null,
                'birth_date' => '2000-09-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLASUKANMI OLATUNJI',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => null,
                'birth_date' => '2000-04-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATUNJI MODUPE',
                'email' => null,
                'phones' => null,
                'department_id' => 7,
                'gender' => null,
                'birth_date' => '2000-05-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLANIPEKUN PHILIP',
                'email' => null,
                'phones' => null,
                'department_id' => 30,
                'gender' => null,
                'birth_date' => '2000-05-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOWOLEREKUN SAMSON',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-04-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWADARE DOMINIC',
                'email' => null,
                'phones' => null,
                'department_id' => 34,
                'gender' => null,
                'birth_date' => '2000-11-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOLE OLANREWAJU',
                'email' => null,
                'phones' => null,
                'department_id' => 11,
                'gender' => null,
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOSUYI DEJI',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => null,
                'birth_date' => '2000-01-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONILEOWO ARIYO',
                'email' => null,
                'phones' => null,
                'department_id' => 13,
                'gender' => null,
                'birth_date' => '2000-08-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEDUNTAN GBENGA',
                'email' => null,
                'phones' => null,
                'department_id' => 41,
                'gender' => null,
                'birth_date' => '2000-09-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYENUGA OLUFEMI',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => null,
                'birth_date' => '2000-03-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'QUADRI MODUPE',
                'email' => null,
                'phones' => null,
                'department_id' => 7,
                'gender' => null,
                'birth_date' => '2000-01-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ROMILUYI ADESUYI',
                'email' => null,
                'phones' => null,
                'department_id' => 4,
                'gender' => null,
                'birth_date' => '2000-10-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SHEYA ROBINSON',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => null,
                'birth_date' => '2000-04-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TAIWO ADEYINKA',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => null,
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TEIBO JOHN',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-11-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSUNMOYE FRANKLIN',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => null,
                'birth_date' => '2000-03-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: " . count($alumni) . " records");
    }
}
