<?php

namespace Database\Seeders\AlumniSeeder;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2011_2012Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::updateOrCreate(
            ['year' => '2011-2012'],

            [
                'name' => 'The Lord reigns generation',
                'family_name' => 'Peculiar Treasure FAMILY',
            ]
        );

        $alumni = [
            [
                'name' => 'ABE GBEMISOLA E',
                'email' => null,
                'phones' => ['07033465538'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-01-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADARA MARK',
                'email' => null,
                'phones' => ['07036521171'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYEMI TIMOTHY',
                'email' => null,
                'phones' => ['08061186647'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASHOGBON OLUWATOSIN',
                'email' => null,
                'phones' => ['08032105544'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABANIJI OLUWATOBI',
                'email' => null,
                'phones' => ['08026881140'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOEYE TIMI',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAMIGBOYE GBEMISOLA',
                'email' => null,
                'phones' => ['08030469302'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'GBADEBO IFEOLUWA K',
                'email' => null,
                'phones' => ['08132129143'],
                'department_id' => 4,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IBILEYE DOTUN',
                'email' => null,
                'phones' => ['08032172500'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IKE OLUSOLA',
                'email' => null,
                'phones' => ['07032573172'],
                'department_id' => 3,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JEMIBEWON OLUWAKEMI',
                'email' => null,
                'phones' => ['08032820336'],
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDOJUTIMI SUNDAY',
                'email' => null,
                'phones' => ['08062635954'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKERAYI GBOLAHAN',
                'email' => null,
                'phones' => ['07065719600'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKOYEANICHE PATRICK',
                'email' => null,
                'phones' => ['07060539447'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOBOYEJE VICTOR O',
                'email' => null,
                'phones' => ['07039221051'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OZORE U. MOSES',
                'email' => null,
                'phones' => ['07034737980'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SOBOGUN OLATUNDE',
                'email' => null,
                'phones' => ['08066223558'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBISI MERCY A',
                'email' => null,
                'phones' => ['07033958498'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBOYE OLUFUNKE A',
                'email' => null,
                'phones' => ['08030437159'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-02-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIYI KEMISOLA',
                'email' => null,
                'phones' => ['08062501885'],
                'department_id' => 25,
                'gender' => null,
                'birth_date' => '2000-02-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYANJU EMMANUEL',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEOTI AYODELE',
                'email' => null,
                'phones' => ['08071865089'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFOLABI BUSAYO S',
                'email' => null,
                'phones' => ['08036887477'],
                'department_id' => 18,
                'gender' => 'F',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI KEHINDE',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJILORE KOLAWOLE',
                'email' => null,
                'phones' => ['07060171206'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINDOYO FELIX AKINOLA',
                'email' => null,
                'phones' => ['08130561055'],
                'department_id' => 3,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOLA OLUWASHINA J',
                'email' => null,
                'phones' => ['07063091042'],
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWUMI YEWANDE E',
                'email' => null,
                'phones' => ['08069844969'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASEYAN BABAJIDE',
                'email' => null,
                'phones' => ['08072104992'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOSIKA BABAJIDE M',
                'email' => null,
                'phones' => ['08064405504'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DADA ADADEJI SOLOMON',
                'email' => null,
                'phones' => ['07058031850'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DADA DAVID O',
                'email' => null,
                'phones' => ['08034207934'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAGBAYI ABAYOMI DANIEL',
                'email' => null,
                'phones' => ['07064333408'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => 'Academic Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FARONBI SAMUEL',
                'email' => null,
                'phones' => ['07064522412'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JAIYEOLA GABRIEL O',
                'email' => null,
                'phones' => ['08139470481'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'NKWUKA NNAMDI A',
                'email' => null,
                'phones' => ['07058844561'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => 'Academic Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUOKUN OLUWAYIMIKA',
                'email' => null,
                'phones' => ['08039473852'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ORISAWUYI BOLUWATIWI',
                'email' => null,
                'phones' => ['07039718700'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIYI HEZEKIAH T',
                'email' => null,
                'phones' => ['07030718777'],
                'department_id' => 45,
                'gender' => 'F',
                'birth_date' => '2000-03-01',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADERETI ADEWALE',
                'email' => null,
                'phones' => ['08068487147'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '1931-03-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBEBI OLUWASEUN J',
                'email' => null,
                'phones' => ['08024247489'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI AYODELE O',
                'email' => null,
                'phones' => ['07030846493'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKANDE GLADYS M',
                'email' => null,
                'phones' => ['08059064300'],
                'department_id' => 4,
                'gender' => 'F',
                'birth_date' => '2000-03-01',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EKUDEHINWA SESAN A',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBILE OLUWAKEMI',
                'email' => null,
                'phones' => ['07032658866'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-03-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DOSUMU SEGUN',
                'email' => null,
                'phones' => ['08037980307'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EGENA VINCENT',
                'email' => null,
                'phones' => ['08067962158'],
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EROMOJELE E. FREDRICK',
                'email' => null,
                'phones' => ['07035272506'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAMAKINWA MICHAEL B',
                'email' => null,
                'phones' => ['07033282447'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAWIBE MATTHEW O',
                'email' => null,
                'phones' => ['08022509228'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FOLARANMI OLABISI E',
                'email' => null,
                'phones' => ['08068493058'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IBITOYE TITILAYO',
                'email' => null,
                'phones' => ['08063227510'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGBENA GIFT E',
                'email' => null,
                'phones' => ['08032427066'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNSUYI OPEYEMI B',
                'email' => null,
                'phones' => ['08067619381'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOJOLA IFEOLUWA A',
                'email' => null,
                'phones' => ['08060402418'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOEYE GABREL SEYI',
                'email' => null,
                'phones' => ['08164050474'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDOKUN AYOSUNBO',
                'email' => null,
                'phones' => ['08094504798'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEPOJU OLUSOLA D',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKILE MODUPE A',
                'email' => null,
                'phones' => ['08022081172'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELOYE ADEBAYO',
                'email' => null,
                'phones' => ['07067812806'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIYI DAMILOLA M',
                'email' => null,
                'phones' => ['08060880517'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-04-01',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EHUMADA UCHE',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => null,
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEPOJU OLUSOLA D',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETUNJI ADEDOLAPO',
                'email' => null,
                'phones' => ['08062183637'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETUNJI ADEDOLAPO E',
                'email' => null,
                'phones' => ['08062183637'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYA ADEOLA  O',
                'email' => null,
                'phones' => ['08067299390'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFE KADE OLATUNDE',
                'email' => null,
                'phones' => ['07038608152'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYA OLUWABUNMI',
                'email' => null,
                'phones' => ['08068667441'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALADEMEHIN YEMIDALE T',
                'email' => null,
                'phones' => ['07031175856'],
                'department_id' => 8,
                'gender' => null,
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AROWOLO IDOWU',
                'email' => null,
                'phones' => ['08066076918'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BELIE AKINJUBI D',
                'email' => null,
                'phones' => ['08038385341'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Follow up/Counselling Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAKUA OLAMIDE F',
                'email' => null,
                'phones' => ['08062654181'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FOLAJIMI DAMILOLA F',
                'email' => null,
                'phones' => ['08066268467'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '1930-04-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IDOWU TEMITOPE K',
                'email' => null,
                'phones' => ['08034023774'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JAIYEOLA GABRIAL',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KAYODE OLUWASEYI',
                'email' => null,
                'phones' => ['07065719553'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Follow up/Counselling Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOSOWON TOLU',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBASUSI OLASUNKANMI I',
                'email' => null,
                'phones' => ['08034317185'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBAYELU IGBEKELE S',
                'email' => null,
                'phones' => ['07065949520'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKUSANYA AFOLARIN',
                'email' => null,
                'phones' => ['07061103528'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLULEYE AYOKUNLE',
                'email' => null,
                'phones' => ['08038262865'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUYEMI DAMILOLA H',
                'email' => null,
                'phones' => ['08165670190'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMIYALE OLATUNBOSUN',
                'email' => null,
                'phones' => ['08084188475'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONI MOYINOLUWA A',
                'email' => null,
                'phones' => ['08066317277'],
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OTEMOYE TOLULOPE',
                'email' => null,
                'phones' => ['07066295281'],
                'department_id' => 17,
                'gender' => 'F',
                'birth_date' => '2000-05-01',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWONAIYE SANMI I',
                'email' => null,
                'phones' => ['08037461995'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADAJA OLUWABUNMI O',
                'email' => null,
                'phones' => ['08062157537'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-05-01',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDEJI TOSIN E',
                'email' => null,
                'phones' => ['08068939165'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKANNBI SAMUEL',
                'email' => null,
                'phones' => ['07035739546'],
                'department_id' => 11,
                'gender' => null,
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKOYA ADEBOWALE',
                'email' => null,
                'phones' => ['08186028964'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOLA FESTUS A',
                'email' => null,
                'phones' => ['08036854498'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BANKOLE GABRAEL A',
                'email' => null,
                'phones' => ['07062395683'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BETIKU SEGUN',
                'email' => null,
                'phones' => ['08038467788'],
                'department_id' => 33,
                'gender' => null,
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DARE OGUNLEYE M',
                'email' => null,
                'phones' => ['08034431523'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAJOBI OLALEKAN',
                'email' => null,
                'phones' => ['08038329669'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FASUGBA GBENGA J',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FOLAYAN BABATUNDE ISAA',
                'email' => null,
                'phones' => ['08024224261'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNBADEJO TOPE',
                'email' => null,
                'phones' => ['08039379949'],
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => 'Follow up/Counselling Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONAYEMI DAMILOLA D',
                'email' => null,
                'phones' => ['07039327291'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYELEYE GRACE O',
                'email' => null,
                'phones' => ['08065831520'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-05-01',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEYIOLA OYEDOYIN O',
                'email' => null,
                'phones' => ['08066337070'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-05-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SAMUEL SEUN G',
                'email' => null,
                'phones' => ['08065372641'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABATAN OLUWADUNNI O',
                'email' => null,
                'phones' => ['08073652284'],
                'department_id' => 32,
                'gender' => 'F',
                'birth_date' => '2000-06-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBOYEGA JIDE',
                'email' => null,
                'phones' => ['07033349097'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENOLA OLUKEMI 0',
                'email' => null,
                'phones' => ['08077719601'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYOBAMI OLUOKUN',
                'email' => null,
                'phones' => ['07035669225'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALADE OMOLOLU OLUMIDE',
                'email' => null,
                'phones' => ['07068330308'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALODUN OLANIKE  P',
                'email' => null,
                'phones' => ['08068506541'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-06-01',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOUKI YETUNDE',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FASAE OLUSOLA',
                'email' => null,
                'phones' => ['08065178065'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IMANI OLAWALE',
                'email' => null,
                'phones' => ['07063011403'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ISRAEL M ADEMOLA',
                'email' => null,
                'phones' => ['08063966884'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JEGEDE TEMITAYO',
                'email' => null,
                'phones' => ['08026141578'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KEHIDE OPEYEMI',
                'email' => null,
                'phones' => ['07034222857'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLANA BABAJIDE T',
                'email' => null,
                'phones' => ['08161887261'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJENIKE ADEKEMI A',
                'email' => null,
                'phones' => ['08050453232'],
                'department_id' => 8,
                'gender' => 'F',
                'birth_date' => '2000-06-01',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO SHOLA',
                'email' => null,
                'phones' => ['08064929345'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAWUMI OLUFEMI',
                'email' => null,
                'phones' => ['08132138693'],
                'department_id' => 30,
                'gender' => 'F',
                'birth_date' => '2000-06-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMEOBI VICTOR',
                'email' => null,
                'phones' => ['08035922231'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMONIYI TEMITOPE J',
                'email' => null,
                'phones' => ['07033958234'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => 'Follow up/Counselling Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONIGBINDE BUKOLA O',
                'email' => null,
                'phones' => ['07067803475'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-06-01',
                'unit' => 'Editorial Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYESOMI ROTIMI M',
                'email' => null,
                'phones' => ['08063453847'],
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'UMUKORO REUBEN',
                'email' => null,
                'phones' => ['08079440756'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKUNLE TOLULOPE',
                'email' => null,
                'phones' => ['07038158986'],
                'department_id' => 11,
                'gender' => 'F',
                'birth_date' => '1930-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELEYE BENARD A',
                'email' => null,
                'phones' => ['08132364486'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIYI ALABA E',
                'email' => null,
                'phones' => ['08028651802'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => 'Editorial Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYO OLUWADUNSIN',
                'email' => null,
                'phones' => ['07033321356'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFUYE OLAKUNLE',
                'email' => null,
                'phones' => ['08068642309'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGOFURE JEREMIAH O',
                'email' => null,
                'phones' => ['08035207065'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBOLUJI ADEYEMI N',
                'email' => null,
                'phones' => ['07033263774'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => 'Follow up/Counselling Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINDOLIE TOBI',
                'email' => null,
                'phones' => ['08130567582'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '1931-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWA SEGUN',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWOLEOLA OPEYEMI',
                'email' => null,
                'phones' => ['07036693296'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWEKOHE FELIX E',
                'email' => null,
                'phones' => ['08136321343'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYODELE OLUWAGBEGA J.',
                'email' => null,
                'phones' => ['07036649090'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BETIKU OLUWASEGUN',
                'email' => null,
                'phones' => ['08038467708'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ESAN  ISRAEL A.',
                'email' => null,
                'phones' => ['08060036319'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALORE TOSIN',
                'email' => null,
                'phones' => ['08063259497'],
                'department_id' => 33,
                'gender' => 'F',
                'birth_date' => '2000-07-01',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IBITOYE SOJI M',
                'email' => null,
                'phones' => ['07030220877'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDANA KUNLE',
                'email' => null,
                'phones' => ['07032022073'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKOKO MKPOUTO U',
                'email' => null,
                'phones' => ['07062479114'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => 'Editorial Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAYINKA JOSEPH',
                'email' => null,
                'phones' => ['08134986899'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TOSIN DARAMOLA',
                'email' => null,
                'phones' => ['08061579151'],
                'department_id' => 10,
                'gender' => 'F',
                'birth_date' => '2000-07-01',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIRAN OLUWAKEMI A',
                'email' => null,
                'phones' => ['08030853273'],
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-08-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWOLE VINCENT',
                'email' => null,
                'phones' => ['08068016848'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI TOSIN TUNRAYO',
                'email' => null,
                'phones' => ['08034554616'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-08-01',
                'unit' => 'Follow up/Counselling Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOJOYE WALE',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYOSOYE BABAWALE',
                'email' => null,
                'phones' => ['07032689004'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOYEMI SAMUEL',
                'email' => null,
                'phones' => ['08066379609'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IMORU OLUWATOYIN',
                'email' => null,
                'phones' => ['07032418541'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-08-01',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBAGUNWA KEMI',
                'email' => null,
                'phones' => ['07033584368'],
                'department_id' => 45,
                'gender' => 'F',
                'birth_date' => '2000-08-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKIEMURE HENRY EJIRO',
                'email' => null,
                'phones' => ['07026683774'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '1931-08-01',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADELE GILBERT A',
                'email' => null,
                'phones' => ['08060601810'],
                'department_id' => 10,
                'gender' => null,
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOWOJOBA ADEMULEGUN',
                'email' => null,
                'phones' => ['07069693226'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUSOGA OLAWALE',
                'email' => null,
                'phones' => ['08087654838'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SHITTU OMOLARA',
                'email' => null,
                'phones' => ['08032151854'],
                'department_id' => 8,
                'gender' => 'F',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBUNMI FUNMILAYO H',
                'email' => null,
                'phones' => ['08080706528'],
                'department_id' => 38,
                'gender' => 'F',
                'birth_date' => '2000-09-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWE BABATUNDE',
                'email' => null,
                'phones' => null,
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELOWO ADEOLA A',
                'email' => null,
                'phones' => ['07030838655'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINGBOYEGBE OPEYEMI',
                'email' => null,
                'phones' => ['07031857895'],
                'department_id' => 11,
                'gender' => 'F',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABATUNDE WUMI',
                'email' => null,
                'phones' => ['07038319479'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-09-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BOLARINWA ABIMBOLA',
                'email' => null,
                'phones' => ['08036537715'],
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSELE AKINBAYO',
                'email' => null,
                'phones' => ['08039559165'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ENYA ROLAND',
                'email' => null,
                'phones' => ['07062395810'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FETUGA ADEDOTUN',
                'email' => null,
                'phones' => ['08065864435'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KEHINDE IFEDAYO',
                'email' => null,
                'phones' => ['07055364584'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATOKUNBO OLALEKAN V',
                'email' => null,
                'phones' => ['08086940881'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOJUOLA ALEX',
                'email' => null,
                'phones' => ['08063809409'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLONITOYE TOLU F',
                'email' => null,
                'phones' => ['08067226316'],
                'department_id' => 44,
                'gender' => 'F',
                'birth_date' => '2000-09-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWATOSIN EMMANUEL',
                'email' => null,
                'phones' => ['08038374104'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEMI BABATUNDE D',
                'email' => null,
                'phones' => ['07064990738'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEYE AYODEJI BAYO',
                'email' => null,
                'phones' => ['08030512701'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBOOLA IBIRONKE',
                'email' => null,
                'phones' => ['07038946010'],
                'department_id' => 49,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKEJU OSUOLALE J',
                'email' => null,
                'phones' => ['07038243809'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINDOLIE OLUWALEKE',
                'email' => null,
                'phones' => ['08068855222'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYENI OLUWATOSIN',
                'email' => null,
                'phones' => ['08066306319'],
                'department_id' => 44,
                'gender' => 'F',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABALOLA AYODEJI S',
                'email' => null,
                'phones' => ['08095610496'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALEYE VICTOR IDOWU',
                'email' => null,
                'phones' => ['08063766718'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => 'Editorial Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KIKEKAN OLUGBENGA',
                'email' => null,
                'phones' => ['07038121175'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'NUFFI OSIEKA MENI',
                'email' => null,
                'phones' => ['08065343363'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATOMIRIN OLABANJI S',
                'email' => null,
                'phones' => ['07033295183'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAWOLE BANJI',
                'email' => null,
                'phones' => ['07030077805'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAWOYE DAYO',
                'email' => null,
                'phones' => ['08066589188'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNTOBA MAYOWA',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'F',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSUNLOLA FEMI V',
                'email' => null,
                'phones' => ['08062227840'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGOKE TEMITAYO O',
                'email' => null,
                'phones' => ['07032623818'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '1930-11-01',
                'unit' => 'Editorial Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIYI AKINWALE',
                'email' => null,
                'phones' => ['08036365919'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFOLABI ISMAILA P',
                'email' => null,
                'phones' => ['08035486807'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKABUIKECHRISTIANA O',
                'email' => null,
                'phones' => ['08024905586'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-11-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINMOLADUN ABAYOMI H',
                'email' => null,
                'phones' => ['08025598549'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKIODE OLUWATOBI S',
                'email' => null,
                'phones' => ['08038640037'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALO AYOPO B',
                'email' => null,
                'phones' => ['07030077119'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BENYEOGOR NAOMI ROHEM',
                'email' => null,
                'phones' => ['08131361995'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KEHINDE OLASUNKANMI',
                'email' => null,
                'phones' => ['08032530242'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => 'Academic Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNSUSI ADEMOLA A',
                'email' => null,
                'phones' => ['08032234744'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO OLAOLUWA O',
                'email' => null,
                'phones' => ['08050208560'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAONIPEKUN OLADOTUN',
                'email' => null,
                'phones' => null,
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADIPO OLUREMI',
                'email' => null,
                'phones' => ['08068881045'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAGUNDOYE AKIN',
                'email' => null,
                'phones' => ['08062268667'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMONAIYE ISAAC',
                'email' => null,
                'phones' => ['08137973427'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAMI MICHAEL',
                'email' => null,
                'phones' => ['08069392599'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SANNI FUMILAYO',
                'email' => null,
                'phones' => ['08036098587'],
                'department_id' => 49,
                'gender' => 'F',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'UHAKHEME D MATHEW',
                'email' => null,
                'phones' => ['08036103705'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '1930-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEOGUN TEMITOPE',
                'email' => null,
                'phones' => ['08131899276'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETOKUNBO TITILOLA T',
                'email' => null,
                'phones' => ['08034258627'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWOLE DOTUN',
                'email' => null,
                'phones' => ['07036316846'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBOOLA OLUWASEUN Y',
                'email' => null,
                'phones' => ['08061684685'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALONGE OLATUNDE DANIEL',
                'email' => null,
                'phones' => ['08062206502'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DARAMOLA STEPHEN O',
                'email' => null,
                'phones' => ['07033340879'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '1930-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ESAN OLUWASEUN O',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IJANIYI OLUWATOSIN O',
                'email' => null,
                'phones' => ['08067907234'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MBA EMMANUEL U',
                'email' => null,
                'phones' => ['08050883227'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDIJO SESAN',
                'email' => null,
                'phones' => ['07032353814'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJENIKE ADEKEMI',
                'email' => null,
                'phones' => null,
                'department_id' => 8,
                'gender' => 'F',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUMOKO FRANCIS',
                'email' => null,
                'phones' => ['08063903438'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOBOWALE DARE',
                'email' => null,
                'phones' => ['08169590405'],
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEBAMIJI TIMOTHY D',
                'email' => null,
                'phones' => ['08050980259'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALABI SAMUEL',
                'email' => null,
                'phones' => ['08065821763'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
