<?php

namespace Database\Seeders\AlumniSeeder;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2007_2008Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::updateOrCreate(
            ['year' => '2007-2008'],
            ['name' => '2007-2008 Set']
        );

        $alumni = [
            [
                'name' => 'ADENIYI ONAOPEPO',
                'email' => null,
                'phones' => ['08067117231'],
                'department_id' => 34,
                'gender' => 'F',
                'birth_date' => '2000-01-13',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OHIKHENA IFEOLUWA',
                'email' => null,
                'phones' => ['08057319263'],
                'department_id' => 41,
                'gender' => null,
                'birth_date' => '2000-01-18',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDEJI TOLA',
                'email' => null,
                'phones' => ['08068976897'],
                'department_id' => 17,
                'gender' => null,
                'birth_date' => '2000-12-22',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODUNAYO G.O',
                'email' => null,
                'phones' => ['08035125076'],
                'department_id' => 17,
                'gender' => null,
                'birth_date' => '2000-09-14',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SHADYA JUMOKE',
                'email' => null,
                'phones' => ['07033388932'],
                'department_id' => 32,
                'gender' => 'F',
                'birth_date' => '2000-03-28',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DARE ADEGBITE',
                'email' => null,
                'phones' => ['08034095273'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-01-22',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWE OLUWAYOMI',
                'email' => null,
                'phones' => ['08056179816'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-03-17',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSHO BANKOLE',
                'email' => null,
                'phones' => ['08035799932'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-04-04',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ELEHINLE FOLASHADE',
                'email' => null,
                'phones' => ['08030741427'],
                'department_id' => 38,
                'gender' => 'F',
                'birth_date' => '2000-07-13',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO TIMILEHIN',
                'email' => null,
                'phones' => ['08034397019'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-09-02',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI OLALEKAN',
                'email' => null,
                'phones' => ['08033970544'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-10-16',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELUGBA OLORUNTOBA',
                'email' => null,
                'phones' => ['08039774539'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-10-19',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFELUYI OLUWAYEMISI',
                'email' => null,
                'phones' => ['07030670659'],
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-10-22',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOLE BOLUWATIFE',
                'email' => null,
                'phones' => ['08038048353'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-11-27',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DAUDU ORINAMI',
                'email' => null,
                'phones' => ['08032234727'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-08-08',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'PELEMO BUKOLA',
                'email' => null,
                'phones' => ['08038459639'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-01-07',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEMO BIMBO',
                'email' => null,
                'phones' => ['08036552522'],
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-09-29',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGOKE OLOLADE',
                'email' => null,
                'phones' => ['08068976814'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-03-21',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESKO MAYOWA',
                'email' => null,
                'phones' => ['08034831502'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-01-06',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIYI ADEOLA',
                'email' => null,
                'phones' => ['08062228024'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-05-09',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFOLABI JANET',
                'email' => null,
                'phones' => ['08060352988'],
                'department_id' => 44,
                'gender' => 'F',
                'birth_date' => '2000-06-20',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYEMI BUNMI',
                'email' => null,
                'phones' => ['08037840477'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-07-22',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DILE OLUWASEYI J.',
                'email' => null,
                'phones' => ['08038528643'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-09-19',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAGBEMIGUN FEMI',
                'email' => null,
                'phones' => ['08039415726'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-03-11',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FATUNBI TOPE',
                'email' => null,
                'phones' => ['08038207756'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-05-23',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAWIBE OLAYIWOLA',
                'email' => null,
                'phones' => ['08038567604'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-11-02',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IBUKUN OLUWASEGUN',
                'email' => null,
                'phones' => ['08027191851'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-03-02',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONI OLUWATOSIN',
                'email' => null,
                'phones' => ['08060345979'],
                'department_id' => 4,
                'gender' => 'F',
                'birth_date' => '2000-01-11',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
