<?php

namespace Database\Seeders\AlumniSeeder;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2017_2018Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::updateOrCreate(
            ['year' => '2017-2018'],
            ['name' => 'The shining light generation',
                'family_name' => 'REDEEMER’S ARMY FAMILY']
        );

        $alumni = [
            [
                'name' => 'AWE DEBBIE',
                'email' => null,
                'phones' => ['07067837014'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINTE DAMILOLA',
                'email' => null,
                'phones' => ['08034738357'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-01-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IJAGBEMI OLUWADUNSIN',
                'email' => null,
                'phones' => ['08101107993'],
                'department_id' => 6,
                'gender' => 'F',
                'birth_date' => '2000-02-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOYEMI MODUPE',
                'email' => null,
                'phones' => ['08064128443'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-03-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATUNBOSUN KEMI',
                'email' => null,
                'phones' => ['08167144636'],
                'department_id' => 1,
                'gender' => 'F',
                'birth_date' => '2000-03-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENUGBA MICHEAL',
                'email' => null,
                'phones' => ['08160881677'],
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-04-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LAMIDI ADETOLA',
                'email' => null,
                'phones' => ['08101346534'],
                'department_id' => 2,
                'gender' => 'M',
                'birth_date' => '2000-05-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYANWALE SAMUEL',
                'email' => null,
                'phones' => ['08165910406'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-06-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYENIRAN MARY',
                'email' => null,
                'phones' => ['08166612620'],
                'department_id' => 3,
                'gender' => 'F',
                'birth_date' => '2000-08-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KOKO ADEYINKA',
                'email' => null,
                'phones' => ['08153708801'],
                'department_id' => 3,
                'gender' => 'F',
                'birth_date' => '2000-08-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNMAKIN TOBILOBA',
                'email' => null,
                'phones' => ['08139123445'],
                'department_id' => 2,
                'gender' => 'M',
                'birth_date' => '2000-08-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARANSIOLA PEACE',
                'email' => null,
                'phones' => ['07067500992'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-08-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABORISADE ANU',
                'email' => null,
                'phones' => ['08066054445'],
                'department_id' => 1,
                'gender' => 'F',
                'birth_date' => '2000-09-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJISAFE TOBI',
                'email' => null,
                'phones' => ['08132981726'],
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-10-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DARAMOLA ADEOLA',
                'email' => null,
                'phones' => ['07032451725'],
                'department_id' => 2,
                'gender' => 'F',
                'birth_date' => '2000-10-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARIYO SEUN',
                'email' => null,
                'phones' => ['08135770365'],
                'department_id' => 4,
                'gender' => 'F',
                'birth_date' => '2000-11-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'UHAKHEME PRECIOUS',
                'email' => null,
                'phones' => ['07031892381'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-11-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBAYO SOLA',
                'email' => null,
                'phones' => ['09032223878'],
                'department_id' => 2,
                'gender' => 'F',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IKHAZOBOR SOLOMON',
                'email' => null,
                'phones' => ['07035471308'],
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONI GBOHUNMI',
                'email' => null,
                'phones' => ['08168561404'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDEJI KAYODE',
                'email' => null,
                'phones' => ['08105977882'],
                'department_id' => 3,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEDEJI GIFT',
                'email' => null,
                'phones' => ['08181926597'],
                'department_id' => 1,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALABI BUNMI',
                'email' => null,
                'phones' => ['08063871422'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAO IFE',
                'email' => null,
                'phones' => ['08149809643'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MEBUDE SAMUEL',
                'email' => null,
                'phones' => ['07054628599'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-03-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'UJATTAH MONDY',
                'email' => null,
                'phones' => ['08102348349'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOYA OLUWASOLA',
                'email' => null,
                'phones' => ['08107151566'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-04-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYODELE OPEYEMI',
                'email' => null,
                'phones' => ['08186257510'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-05-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDIJI ABISOLUWA',
                'email' => null,
                'phones' => ['08167158489'],
                'department_id' => 10,
                'gender' => 'F',
                'birth_date' => '2000-05-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOEYE SAMUEL',
                'email' => null,
                'phones' => ['08140398140'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-05-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYINLOYE OLUWASEUN',
                'email' => null,
                'phones' => ['08130252922'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-05-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEOTI ISRAEL',
                'email' => null,
                'phones' => ['08102564922'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-05-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'CHIDIEBERE PRECIOUS',
                'email' => null,
                'phones' => ['08160994624'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-05-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABIOLA KEHINDE',
                'email' => null,
                'phones' => ['07069263676'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-06-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IGBALAJOBI MICHAEL',
                'email' => null,
                'phones' => ['08165260157'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-06-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEBAMIJI SAMUEL',
                'email' => null,
                'phones' => ['07062743233'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-06-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODESANMI KEHINDE',
                'email' => null,
                'phones' => ['907553349'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-06-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWAROTIMI WILLIAMS',
                'email' => null,
                'phones' => ['09030909165'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-06-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKOYE COLLINS',
                'email' => null,
                'phones' => ['08138376172'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-06-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JULIUS JOSEPH',
                'email' => null,
                'phones' => ['09038003379'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-07-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKUNLE TAIWO',
                'email' => null,
                'phones' => ['08144283420'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-08-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNSOLA JEDIDIAH',
                'email' => null,
                'phones' => ['08137530625'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-08-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUDAMIRO EMMANUEL',
                'email' => null,
                'phones' => ['08168492234'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-08-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDIRAN MICHAEL',
                'email' => null,
                'phones' => ['08167137610'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-09-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EWUOLA OLUSHONAOLA',
                'email' => null,
                'phones' => ['08036792735'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-09-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABALOLA IFEOLUWAPO',
                'email' => null,
                'phones' => ['08100921167'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-10-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO OLUWATOYOSI',
                'email' => null,
                'phones' => ['08164340150'],
                'department_id' => 16,
                'gender' => 'F',
                'birth_date' => '2000-11-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODENIYI MOSES',
                'email' => null,
                'phones' => ['08137534728'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-11-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNFEMI JOHN',
                'email' => null,
                'phones' => ['08067681248'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-11-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJASANYA KELVIN',
                'email' => null,
                'phones' => ['08185183321'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-12-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWUMI OLAKUNLE',
                'email' => null,
                'phones' => ['08162345840'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOYEMI OLANREWAJU',
                'email' => null,
                'phones' => ['08124435655'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUDARE DOLAMU',
                'email' => null,
                'phones' => ['08165539137'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'YUSUF BENJAMIN',
                'email' => null,
                'phones' => ['08139331357'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AROBOTO',
                'email' => null,
                'phones' => ['08132586404'],
                'department_id' => 10,
                'gender' => 'F',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAIGBE JOSHUA',
                'email' => null,
                'phones' => ['08135556767'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-11-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EMEKPO ZEAL',
                'email' => null,
                'phones' => ['08108282853'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'NZOMIWU COLLINS',
                'email' => null,
                'phones' => ['08164024225'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNGBEMI ELIJAH',
                'email' => null,
                'phones' => ['07068540454'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AIGBOJARE LUCKY',
                'email' => null,
                'phones' => ['07033855537'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEMOLA AYOBAMI',
                'email' => null,
                'phones' => ['08167967805'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADERINWALE A',
                'email' => null,
                'phones' => ['08136481236'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '1931-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBAMEHINTI S',
                'email' => null,
                'phones' => ['08114573440'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKEOWO DARE PETER',
                'email' => null,
                'phones' => ['08131909011'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLABIYI EMMANUEL',
                'email' => null,
                'phones' => ['07032779031'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLURINDE GBENGA',
                'email' => null,
                'phones' => ['08069553378'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBOYE ADESOLA',
                'email' => null,
                'phones' => ['08133783310'],
                'department_id' => 10,
                'gender' => 'F',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI RICHARD',
                'email' => null,
                'phones' => ['08138231123'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONU AMOS',
                'email' => null,
                'phones' => ['08134708486'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-01-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOWE IYANULOLUWA',
                'email' => null,
                'phones' => ['07069298798'],
                'department_id' => 26,
                'gender' => 'F',
                'birth_date' => '2000-01-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINGBESOTE OMOTAYO',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => 'F',
                'birth_date' => '2000-08-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABODUNRIN AMOS',
                'email' => null,
                'phones' => ['08109796203'],
                'department_id' => 29,
                'gender' => 'M',
                'birth_date' => '2000-08-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'YUSUF  ABIODUN',
                'email' => null,
                'phones' => ['07036639218'],
                'department_id' => 29,
                'gender' => 'F',
                'birth_date' => '2000-12-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI BOLUWATIFE',
                'email' => null,
                'phones' => ['08106377097'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TANIMOWO ADETOMIWA',
                'email' => null,
                'phones' => ['08099078019'],
                'department_id' => 29,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BADA ADEBAYO',
                'email' => null,
                'phones' => ['08066293047'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLEYE TOPE O',
                'email' => null,
                'phones' => ['810885441'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSODE VICTOR',
                'email' => null,
                'phones' => ['08060786885'],
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '1931-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALUSI ADEWOLE',
                'email' => null,
                'phones' => ['08147973819'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADISA TEMITOPE',
                'email' => null,
                'phones' => ['08138329470'],
                'department_id' => 17,
                'gender' => null,
                'birth_date' => '2000-06-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEBUKOLA FLORENCE',
                'email' => null,
                'phones' => ['08139376055'],
                'department_id' => 32,
                'gender' => 'F',
                'birth_date' => '2000-01-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EKHAFE ANDREW',
                'email' => null,
                'phones' => ['08165101596'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-01-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINPELUMI TOLU',
                'email' => null,
                'phones' => ['08166565784'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-02-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLENBA PECULIAR',
                'email' => null,
                'phones' => ['07038321143'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-02-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAMI ADENIYI',
                'email' => null,
                'phones' => ['07010367284'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-03-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADAEZE MERCY',
                'email' => null,
                'phones' => ['07033928359'],
                'department_id' => 33,
                'gender' => 'F',
                'birth_date' => '2000-04-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LAOYE GIDEON',
                'email' => null,
                'phones' => ['09035836132'],
                'department_id' => 35,
                'gender' => 'M',
                'birth_date' => '2000-04-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTORIOGUN OLUMIDE',
                'email' => null,
                'phones' => ['07061936970'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-04-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBIYI BOLUTITO',
                'email' => null,
                'phones' => ['08060666770'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-05-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FADOJU OLUWASEYI',
                'email' => null,
                'phones' => ['08089667925'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-05-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KOLAWOLE AYOBAMI',
                'email' => null,
                'phones' => ['08160533254'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-06-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELEKE ADEMOLA',
                'email' => null,
                'phones' => ['08100073891'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-06-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELUGBA AYOMIDE',
                'email' => null,
                'phones' => ['08163187417'],
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-07-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FOLARIN ONADELE',
                'email' => null,
                'phones' => ['07061965609'],
                'department_id' => 31,
                'gender' => 'M',
                'birth_date' => '2000-07-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOWERE KEHINDE',
                'email' => null,
                'phones' => ['08106140211'],
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-07-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODEJAYI ENOCH',
                'email' => null,
                'phones' => ['08166236731'],
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-08-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDEJI VICTOR',
                'email' => null,
                'phones' => ['08164227928'],
                'department_id' => 31,
                'gender' => 'M',
                'birth_date' => '2000-08-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLABOYE OLUWASEUN',
                'email' => null,
                'phones' => ['08139220590'],
                'department_id' => 31,
                'gender' => 'M',
                'birth_date' => '2000-08-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWOLE OLUDARE',
                'email' => null,
                'phones' => ['08101668692'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-09-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNSANYA OLAMIDE',
                'email' => null,
                'phones' => ['08171037337'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-09-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYENIYI KAYODE',
                'email' => null,
                'phones' => ['08138957964'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-09-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DANIEL ANTHONY',
                'email' => null,
                'phones' => ['07062735169'],
                'department_id' => 31,
                'gender' => 'M',
                'birth_date' => '2000-09-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOLABI EMMANUEL',
                'email' => null,
                'phones' => ['08063460198'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-09-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNWALE TEMITAYO',
                'email' => null,
                'phones' => ['09055637107'],
                'department_id' => 31,
                'gender' => 'M',
                'birth_date' => '2000-10-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AMODU EMMANUEL',
                'email' => null,
                'phones' => ['09039120089'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-11-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEJOLU TEMITOPE',
                'email' => null,
                'phones' => ['08161564659'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-11-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EMMANUEL OLUWASEUN',
                'email' => null,
                'phones' => ['08139520479'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-11-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEOYE ANTHONY',
                'email' => null,
                'phones' => ['08173194949'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-12-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBAJIMI TOLULOPE',
                'email' => null,
                'phones' => ['07068502700'],
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-12-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOPADE TEMITOPE',
                'email' => null,
                'phones' => ['08163576049'],
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-12-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLANIYI PAUL',
                'email' => null,
                'phones' => ['08139122555'],
                'department_id' => 31,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNLOGBON BIBIRE',
                'email' => null,
                'phones' => ['08138393068'],
                'department_id' => 32,
                'gender' => 'F',
                'birth_date' => '1930-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEKAN TOLULOPE',
                'email' => null,
                'phones' => ['08166924356'],
                'department_id' => 31,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDAYO AYODEJI',
                'email' => null,
                'phones' => ['09030707561'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADAPO MAYOWA',
                'email' => null,
                'phones' => ['08062845148'],
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETOLA DOTUN',
                'email' => null,
                'phones' => ['08140070524'],
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNTUASE GBEMIGA',
                'email' => null,
                'phones' => ['08163060676'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETOYE FAITH',
                'email' => null,
                'phones' => ['08104884510'],
                'department_id' => 30,
                'gender' => 'F',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LAWAL JAMES',
                'email' => null,
                'phones' => ['08066190308'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYEMI ABIODUN',
                'email' => null,
                'phones' => ['08134276692'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBAJU GABRIEL',
                'email' => null,
                'phones' => ['08167831975'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FASUYI FEMI',
                'email' => null,
                'phones' => ['08133890921'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKEOWO OLAJIDE',
                'email' => null,
                'phones' => ['08169429839'],
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAGBEMI ABIODUN',
                'email' => null,
                'phones' => ['07036369685'],
                'department_id' => 47,
                'gender' => 'F',
                'birth_date' => '2000-01-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAYOSE TEMITOPE',
                'email' => null,
                'phones' => ['08060056935'],
                'department_id' => 49,
                'gender' => 'M',
                'birth_date' => '2000-04-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNSOLA OLUWAYEMI',
                'email' => null,
                'phones' => ['08082901564'],
                'department_id' => 52,
                'gender' => 'F',
                'birth_date' => '2000-04-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNYEMI AYODEJI',
                'email' => null,
                'phones' => ['08132702356'],
                'department_id' => 49,
                'gender' => 'M',
                'birth_date' => '2000-05-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'POPOOLA PAUL',
                'email' => null,
                'phones' => ['08090742214'],
                'department_id' => 49,
                'gender' => 'M',
                'birth_date' => '2000-06-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TENIOLA AYOKUNLE',
                'email' => null,
                'phones' => ['08100518502'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-06-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABATUNDE JOSEPH',
                'email' => null,
                'phones' => ['09053267542'],
                'department_id' => 52,
                'gender' => 'M',
                'birth_date' => '2000-07-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSUYI OLAYEMI',
                'email' => null,
                'phones' => ['08132962361'],
                'department_id' => 49,
                'gender' => 'M',
                'birth_date' => '2000-09-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODEDE EMMANUEL',
                'email' => null,
                'phones' => ['08161999422'],
                'department_id' => 47,
                'gender' => 'M',
                'birth_date' => '2000-11-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALASONIYI SAMUEL',
                'email' => null,
                'phones' => ['09067252265'],
                'department_id' => 52,
                'gender' => 'M',
                'birth_date' => '2000-12-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEMI TOKUNBO',
                'email' => null,
                'phones' => ['08165906106'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MAJOLAGBE LANRE',
                'email' => null,
                'phones' => ['07030736633'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-01-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOWAYE DAMILOLA',
                'email' => null,
                'phones' => ['08162010074'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-01-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DICKSON UCHE',
                'email' => null,
                'phones' => ['07036767319'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-02-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'CHUKWUDI JEFFREY',
                'email' => null,
                'phones' => ['08102810229'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-02-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODUNLADE SEGUN',
                'email' => null,
                'phones' => ['08163439521'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-02-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEMO ADEWALE',
                'email' => null,
                'phones' => ['07060737565'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-03-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYANJU OJO',
                'email' => null,
                'phones' => ['08068257936'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-03-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELEKUN BLESSING',
                'email' => null,
                'phones' => ['08060482404'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-03-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYEGBEMOH DANIEL',
                'email' => null,
                'phones' => ['08142517846'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-03-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASHIRU RUTH',
                'email' => null,
                'phones' => ['07033157618'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-03-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWALE IBUKUN',
                'email' => null,
                'phones' => ['08143863689'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-04-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOPADE AYOMIDE',
                'email' => null,
                'phones' => ['903034477'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-05-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLASANMI BISOLA',
                'email' => null,
                'phones' => ['08094782096'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-05-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADIRAN MATTHEW',
                'email' => null,
                'phones' => ['08033780394'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-06-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'GHARORO PUREHEART',
                'email' => null,
                'phones' => ['08169560365'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-06-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSOLA OLAMIDE',
                'email' => null,
                'phones' => ['07069119847'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-08-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABIOYE DOYINSOLA',
                'email' => null,
                'phones' => ['08164706626'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-08-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELAKUN SAMSON',
                'email' => null,
                'phones' => ['08098901284'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-08-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONOIGBORIA OSAGIE',
                'email' => null,
                'phones' => ['07068992952'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-09-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ANIFOWOSHE GBENGA',
                'email' => null,
                'phones' => ['08137834079'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-09-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKONJI SAMUEL',
                'email' => null,
                'phones' => ['07032309229'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-10-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IGBUHOR CHIDINMA',
                'email' => null,
                'phones' => ['08177544287'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-10-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWALE OLUWASEUN',
                'email' => null,
                'phones' => ['07062373862'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-10-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELODUN BLESSING',
                'email' => null,
                'phones' => ['07052616079'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-10-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODETUNDE KEHINDE',
                'email' => null,
                'phones' => ['08122395570'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-11-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWOLE OLALEKAN',
                'email' => null,
                'phones' => ['08132873922'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-11-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASHAOLU KEHINDE',
                'email' => null,
                'phones' => ['08034284482'],
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-11-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ATOYEBI OPEYEMI',
                'email' => null,
                'phones' => ['08166013009'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-11-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTEHINSE EKUNDAYO',
                'email' => null,
                'phones' => ['08093506625'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-12-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLEKE BLESSING',
                'email' => null,
                'phones' => ['08167173641'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-12-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATOMIDE NICHOLAS',
                'email' => null,
                'phones' => ['08149512420'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWATEMILEHIN OGO. C',
                'email' => null,
                'phones' => ['08062723471'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYIDU DANIEL',
                'email' => null,
                'phones' => ['08162319146'],
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLABODE EMMANUEL',
                'email' => null,
                'phones' => ['07069248190'],
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBAYO EMMANUEL',
                'email' => null,
                'phones' => ['08072139290'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FOLAYAN TOBILOBA',
                'email' => null,
                'phones' => ['09038516909'],
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'USMAN CHRISTIANAH',
                'email' => null,
                'phones' => ['08102768532'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-01-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OTUNLA GIDEON',
                'email' => null,
                'phones' => ['08103831802'],
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-04-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNNOTE OLUWAFEMI',
                'email' => null,
                'phones' => ['08106095060'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-09-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EGBOFOR JENNIFER',
                'email' => null,
                'phones' => ['08177544287'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
