<?php

namespace Database\Seeders\AlumniSeeder;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2013_2014Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2013-2014'],

            [
                'name' => "A new creature generation",
                'family_name' => "God's Own people FAMILY"
            ]
        );

        $alumni = [
            [
                'name' => 'SHONUGA BUSOLA A.',
                'email' => 'adesho247@yahoo.com',
                'phones' => null,
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-02-16',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI MOSUNMOLA',
                'email' => 'mosunmolakofoworola@gmail.com',
                'phones' => null,
                'department_id' => 30,
                'gender' => 'F',
                'birth_date' => '2000-12-14',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWALE LAWANI O.',
                'email' => 'lawaniadewale@gmail.com',
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-05-17',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETULA KEHINDE',
                'email' => 'kehindeadetula@gmail.com',
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-09-29',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FASOLA BUSAYO',
                'email' => 'bharms14@gmail.com',
                'phones' => null,
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-10-02',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNFEMI JOY',
                'email' => 'olorunfemijoy@gmail.com',
                'phones' => null,
                'department_id' => 8,
                'gender' => 'F',
                'birth_date' => '2000-02-06',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EKPE EDIDIONG EKPE',
                'email' => 'eddy_ekpe@yahoo.com',
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-09-02',
                'unit' => 'Sanctuary Keeping Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOBAYI JOHN',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-01-13',
                'unit' => 'Sanctuary Keeping Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINROWO OLUWAFEMI M.',
                'email' => null,
                'phones' => null,
                'department_id' => 3,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => 'Sanctuary Keeping Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADEJI ABIGAEL O',
                'email' => 'queenabigael08@yahoo.com',
                'phones' => null,
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-11-08',
                'unit' => 'Sanctuary Keeping Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKIYESI EMMANUEL A',
                'email' => 'akiyesi.aemmanuel@yahoo.com',
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-12-28',
                'unit' => 'Editorial Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI OMOBOLAJI O',
                'email' => 'tosinbj4wisdom@yahoo.com',
                'phones' => null,
                'department_id' => 13,
                'gender' => 'F',
                'birth_date' => '2000-02-04',
                'unit' => 'Editorial Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDOTUN SOLA T',
                'email' => null,
                'phones' => null,
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-04-22',
                'unit' => 'Editorial Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEBANJO OLOLADE T',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => 'F',
                'birth_date' => '2000-02-28',
                'unit' => 'Editorial Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MOSES FADOLU O',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-05-26',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],

            [
                'name' => 'ADEWUMI SEGUN E',
                'email' => 'olusegunadex@gmail.com',
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-11-24',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OTUN TEMITOPE',
                'email' => null,
                'phones' => null,
                'department_id' => 11,
                'gender' => 'F',
                'birth_date' => '2000-02-06',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBISI C ADEYEMI',
                'email' => 'bechiey14@yahoo.com',
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-05-16',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'UDOKWU FRANCIS O',
                'email' => 'francisudokwu@gmail.com',
                'phones' => null,
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-09-08',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IBITOYE VINCENT O',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODUNYEMI SUNDAY J',
                'email' => null,
                'phones' => null,
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-01-06',
                'unit' => 'Follow up/Counselling Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNMOLA OLUWAFEMI B',
                'email' => null,
                'phones' => null,
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-09-13',
                'unit' => 'Follow up/Counselling Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EKUNDINA SAMUEL O',
                'email' => 'talk2bigekun@yahoo.com',
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-02-20',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABRAHAM SAMUEL D',
                'email' => null,
                'phones' => null,
                'department_id' => 52,
                'gender' => 'M',
                'birth_date' => '2000-09-25',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJEBODE MORENIKEJI B',
                'email' => 'kejiojebode@yahoo.com',
                'phones' => null,
                'department_id' => 32,
                'gender' => 'F',
                'birth_date' => '2000-10-10',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINTAN MODESOLA',
                'email' => 'prismod@yahoo.com',
                'phones' => null,
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-08-12',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOSUNDE TAIYE JOHN',
                'email' => 'Jotinica@yahoo.com',
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-09-12',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOMORO GOD\'SPOWER',
                'email' => 'gio4real2010@yahoo.com',
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-10-09',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI TEMITOPE',
                'email' => null,
                'phones' => null,
                'department_id' => 52,
                'gender' => 'M',
                'birth_date' => '2000-09-19',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABEGUNDE TOLULOPE',
                'email' => null,
                'phones' => null,
                'department_id' => 34,
                'gender' => 'F',
                'birth_date' => '2000-09-11',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IJAOLA OLUWATOMI',
                'email' => 'graceevangelist@gmail.com',
                'phones' => null,
                'department_id' => 4,
                'gender' => 'F',
                'birth_date' => '2000-05-27',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JEGEDE KOLAPO',
                'email' => 'jegedeolanoy_1@yahoo.com',
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-01-27',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEOSUN OLABODE',
                'email' => null,
                'phones' => null,
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-10-09',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALOBA TOWOJU',
                'email' => null,
                'phones' => null,
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-12-23',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EDUN AYOBAMI',
                'email' => 'edun2014@gmail.com',
                'phones' => null,
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-10-13',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNSANYA ADENIYI',
                'email' => null,
                'phones' => null,
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-06-05',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MACAULAY DAMILARE',
                'email' => 'Daremacaulay@gmail.com',
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-05-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'THOTO BLESSING',
                'email' => 'thoto50j@gmail.com',
                'phones' => null,
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-11-18',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'YUSUF GBENGA',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-11-27',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNJI ABOSEDE O',
                'email' => 'abosedeogunji@gmail.com',
                'phones' => null,
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-07-25',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AZIKE CHINYERE',
                'email' => 'chi.azike@yahoo.com',
                'phones' => null,
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-04-04',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKRAN ABOSEDE M',
                'email' => 'bosbyakran@gmail.com',
                'phones' => null,
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-07-17',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWOLE SEUNFUNMI',
                'email' => 'seungracea@yahoo.com',
                'phones' => null,
                'department_id' => 32,
                'gender' => 'F',
                'birth_date' => '2000-07-21',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBOALU ESTHER A',
                'email' => null,
                'phones' => null,
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-04-17',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOSENI TEMIDAYO',
                'email' => 'purposevessel01@gmail.com',
                'phones' => null,
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-11-14',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUSI DIMEJI',
                'email' => null,
                'phones' => null,
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-01-14',
                'unit' => 'Academic Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBIDEYI BOLUWAJI DENNIS',
                'email' => 'obideyiboluwaji@gmail.com',
                'phones' => null,
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-04-09',
                'unit' => 'Academic Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOBOYEJE OYESANMI',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-03-03',
                'unit' => 'Academic Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOLOLA OLAJUMOKE',
                'email' => 'jummiepeace@yahoo.com',
                'phones' => null,
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-07-02',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBOOLA DAMILOLA',
                'email' => 'darmy4god@yahoo.com',
                'phones' => null,
                'department_id' => 11,
                'gender' => 'F',
                'birth_date' => '2000-09-08',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LEKAN KEHINDE DAMILARE',
                'email' => 'kennydam06@yahoo.co.uk',
                'phones' => null,
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-06-25',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJERINDE TEMITOPE J',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'F',
                'birth_date' => '2000-10-11',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINTARO KEMI',
                'email' => 'kemsy05@yahoo.co.uk',
                'phones' => null,
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-12-07',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BANJO-OGUNLEYE T',
                'email' => 'tellybrinkle@gmail.com',
                'phones' => null,
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-06-30',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLULEYE ABIGEAL O',
                'email' => 'bunmie4sure@rocketmail.com',
                'phones' => null,
                'department_id' => 5,
                'gender' => 'F',
                'birth_date' => '2000-11-16',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FATOGUN ABRAHAM',
                'email' => 'waleakanfe@yahoo.com',
                'phones' => null,
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-06-06',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWOLE FAITH',
                'email' => 'alaberefolu23@yahoo.com',
                'phones' => null,
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-07-19',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKANMU KAYODE',
                'email' => 'contactdonmax@yahoo.com',
                'phones' => null,
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-03-25',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUSI BAYO',
                'email' => 'thonie2460@yahoo.com',
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-06-07',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI SEGUN O',
                'email' => 'shagzzy01@yahoo.com',
                'phones' => null,
                'department_id' => 52,
                'gender' => 'M',
                'birth_date' => '2000-09-26',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJETUNMOBI  ABIOLA',
                'email' => 'habbybaby16@yahoo.com',
                'phones' => null,
                'department_id' => 26,
                'gender' => 'F',
                'birth_date' => '2000-05-13',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUMI SEGUN E',
                'email' => 'sege4luv99@gmail.com',
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-11-24',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABIODUN ADELEKAN',
                'email' => 'Lekinfuska@yahoo.com',
                'phones' => null,
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-12-07',
                'unit' => 'Follow up/Counselling Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALIU AYODEJI A.',
                'email' => null,
                'phones' => null,
                'department_id' => 36,
                'gender' => 'M',
                'birth_date' => '2000-05-03',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWALE OYINLOLUWA B',
                'email' => null,
                'phones' => null,
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-04-11',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAKOREDE ELIJAH O.',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-08-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABAYEMI OLUSESAN K',
                'email' => 'righteounesskenny@gmail.com',
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-02-06',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEWUMI SAMSON',
                'email' => 'samvictor9055@yahoo.com',
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-08-22',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAJUBUTU AYODELE M',
                'email' => null,
                'phones' => null,
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-09-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FANIYAN AKINTUNDE B.',
                'email' => 'faniyanakintunde@gmail.com',
                'phones' => null,
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-03-27',
                'unit' => 'Organising Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTAYO BOLAJI R.',
                'email' => 'now:johnalo001@gmail.com',
                'phones' => null,
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-05-22',
                'unit' => 'Follow up/Counselling Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEKOLA OLADAPO M.',
                'email' => 'dapson4cheers@gmail.com',
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-11-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELEYE BOLUWAJI M.',
                'email' => 'adebolu36@yahoo.com',
                'phones' => null,
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-03-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBAKPOLOR ABIODUN',
                'email' => 'steph4bak@yahoo.com',
                'phones' => null,
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-12-27',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALADE OLUWASEUN M.',
                'email' => 'oluwaseunfalade72@yahoo.com',
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-10-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIYI EMMANUEL',
                'email' => 'emmanuel4glory44@yahoo.com',
                'phones' => null,
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-09-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],

            [
                'name' => 'SHOFOLABO OLUSEGUN',
                'email' => 'shopolaboadewale@yahoo.com',
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-07-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IJIBADEJO SAMSON D.',
                'email' => 'kellyjeff00@yahoo.com',
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-12-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TAIWO ANUNOLUWAPO S.',
                'email' => 'samuel_taiwoanu@yahoo.com',
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-03-18',
                'unit' => 'Academic Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALOWO GBEMINIYI',
                'email' => 'gbemzeal@yahoo.com',
                'phones' => null,
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-09-18',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLU-OJO EMMANUEL',
                'email' => 'oluojoemmanuel@yahoo.com',
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-12-24',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESOJI KOLAWOLE E.',
                'email' => 'adesojikolawole@yahoo.com',
                'phones' => null,
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-07-28',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNSUYI VICTOR A.',
                'email' => 'victorogunsuyi@yahoo.com',
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-08-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEMO DOLAPO P.',
                'email' => 'dolly_boy01@yahoo.co.uk',
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-06-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYESORO BABATUNDE',
                'email' => 'tunnez_zito_enit20@yahoo.com',
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-10-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'HEZEKIAH OMOTSUEBE',
                'email' => 'hezecom@gmail.com',
                'phones' => null,
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-01-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLARINMOYO OLAJIDE P',
                'email' => 'captjopaul@yahoo.com',
                'phones' => null,
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-08-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARIBANUSI FUNKE R',
                'email' => 'funkkydee@yahoo.com',
                'phones' => null,
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-06-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAJIDE KEHINDE HENRY',
                'email' => 'kennysimpson05@yahoo.com',
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-05-03',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLABOWALE OLUWASEYI J',
                'email' => 'sheyyboiy4life@yahoo.com',
                'phones' => null,
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-09-24',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALUKO ANUOLUWAPO O',
                'email' => 'anulus4uall@yahoo.com',
                'phones' => null,
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-09-22',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMONIJO ADENIKE H',
                'email' => 'omonyoadenike@yahoo.com',
                'phones' => null,
                'department_id' => 38,
                'gender' => 'F',
                'birth_date' => '2000-03-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDOJA SAMUEL A',
                'email' => 'ledo_sam10@yahoo.com',
                'phones' => null,
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-05-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINRINLOLA OLUMIDE E',
                'email' => 'ibitomiya1_4real@yahoo.com',
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-03-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SALAMI ADEMOLA',
                'email' => 'salami_ademola@yahoo.com',
                'phones' => null,
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-09-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMISAKIN OLUSOLA',
                'email' => 'sola4succes@rocketmail.com',
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-03-04',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINRINLOLA OYINLADE M.',
                'email' => 'oyinomoakin2000@yahoo.com',
                'phones' => null,
                'department_id' => 52,
                'gender' => 'M',
                'birth_date' => '2000-10-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEJOH EMMANUEL D.',
                'email' => 'adejoh_emmanuel2000@yahoo.com',
                'phones' => null,
                'department_id' => 49,
                'gender' => 'M',
                'birth_date' => '2000-08-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJIBOLA ABIOLA AHMED',
                'email' => 'ajibolaabiolaahmed@gmail.com',
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-11-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODEYEMI SAMSON O.',
                'email' => 'walexdino111@yahoo.com',
                'phones' => null,
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-09-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MASANWOOLA MAYOWA',
                'email' => 'mayusworld2003@yahoo.com',
                'phones' => null,
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-03-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DANIJU OLUSOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-04-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNTIMEHIN KAYODE',
                'email' => 'six2kay@yahoo.com',
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-12-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABIOLA SHOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-12-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOBOYE FEMI',
                'email' => 'femoakenkolo@yahoo.com',
                'phones' => null,
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-09-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWADARE TOSIN V.',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-01-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWONUSI OLAJIDE A',
                'email' => 'awonusiolajide@yahoo.com',
                'phones' => null,
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-04-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWUNMI TEMITOPE',
                'email' => 'topsonakinwumi@yahoo.com',
                'phones' => null,
                'department_id' => 52,
                'gender' => 'M',
                'birth_date' => '2000-11-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUBISOYE AYOTUNDE S',
                'email' => 'samuelolubisose@yahoo.com',
                'phones' => null,
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABAAGBA FEBISARA PEACE',
                'email' => 'febibas@yahoo.com',
                'phones' => null,
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-07-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKUNLE ADESOJI MARCUS',
                'email' => 'adesojimarcus@yahoo.com',
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-01-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLEYE GABRIEL A',
                'email' => 'gabo4success@yahoo.com',
                'phones' => null,
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-02-19',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JEGEDE OLUWATOMILOLA',
                'email' => 'tjegzy21@gmail.com',
                'phones' => null,
                'department_id' => 43,
                'gender' => 'F',
                'birth_date' => '2000-02-10',
                'unit' => 'Choir Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUDORO OLUWATOSIN',
                'email' => 'temmycute25@yahoo.com',
                'phones' => null,
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-05-12',
                'unit' => 'Drama Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MALIK OSHOS N',
                'email' => 'malikoshos@yahoo.com',
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-06-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYO-OLOWO TAYE O',
                'email' => 'kaloskeny@yahoo.com',
                'phones' => null,
                'department_id' => 32,
                'gender' => 'M',
                'birth_date' => '2000-07-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AZUBUIKE VALERIE',
                'email' => 'valerizing4luv@yahoo.com',
                'phones' => null,
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-04-09',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'YUSUF AYODELE',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-05-27',
                'unit' => 'Prayer Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'WOLEMIWA TEMIDAYO',
                'email' => null,
                'phones' => null,
                'department_id' => 33,
                'gender' => 'M',
                'birth_date' => '2000-02-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TAIWO TIMILEYIN B',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-07-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'POROYE MICHAEL',
                'email' => 'mikkimonreal@yahoo.com',
                'phones' => null,
                'department_id' => 45,
                'gender' => 'M',
                'birth_date' => '2000-08-13',
                'unit' => 'Welfare Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYESORO BABATUNDE',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-10-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEKOLA OLADAPO',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-11-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ORIRETAN BEATRICE',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => 'F',
                'birth_date' => '2000-07-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ORMOLADE OMOLARA',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-03-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONIJIGUN GBENGA',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-05-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONIBUDO OLUWASEGUN',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-08-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONI AYODEJI',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-08-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTOSO OLUWAMAYOWA',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-06-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEJUMO FUNSHO',
                'email' => 'pinnaccle1992@yahoo.com',
                'phones' => null,
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYESINA AYODEJI',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-10-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJULO OLUWADUNSIN',
                'email' => null,
                'phones' => null,
                'department_id' => 30,
                'gender' => 'F',
                'birth_date' => '2000-03-15',
                'unit' => 'Media and Ambience Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALADE CAROLINE',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'F',
                'birth_date' => '2000-08-18',
                'unit' => 'Ushering Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEKOLA OLADAPO',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-11-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOLADE OMOLARA',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'F',
                'birth_date' => '2000-03-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDOKUN AYOBAMI',
                'email' => null,
                'phones' => null,
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-06-18',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LASISI OLUWATOYIN',
                'email' => null,
                'phones' => null,
                'department_id' => 38,
                'gender' => 'F',
                'birth_date' => '2000-10-12',
                'unit' => 'Academic Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO OLUWATOBILOBA',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-03-02',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IDAHANGBON NOSA A.',
                'email' => null,
                'phones' => null,
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-02-06',
                'unit' => 'Bible Study Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI FRANCIS',
                'email' => null,
                'phones' => null,
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-05-03',
                'unit' => 'Sanctuary Keeping Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LAWAL TEMITAYO',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'F',
                'birth_date' => '2000-08-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'CHUKWUKA NNEKA',
                'email' => null,
                'phones' => null,
                'department_id' => 33,
                'gender' => 'F',
                'birth_date' => '2000-09-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBOWALE PHILIP',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-04-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BELLO OLUWASEGUN',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-07-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EKPENYONG EFIOK EVO',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-09-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EBHOHIMEN TOLULOPE',
                'email' => null,
                'phones' => null,
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-04-24',
                'unit' => 'Evangelism Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINROLABI OLUWAKEMI',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-05-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDAIRO SUNDAY K.',
                'email' => 'ogundairosunday@yahoo.com',
                'phones' => null,
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-07-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JOHNSON GBENGA',
                'email' => 'Jgbenga50@yahoo.com',
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-05-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKE FUNKE M.',
                'email' => 'm2funky88@yahoo.com',
                'phones' => null,
                'department_id' => 38,
                'gender' => 'F',
                'birth_date' => '2000-10-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ANIBABA PAUL O.',
                'email' => 'anibabapaul@yahoo.com',
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-03-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JIMOH BABATUNDE',
                'email' => 'tundex4joy@yahoo.com',
                'phones' => null,
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-04-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDEJI EZEKIEL T.',
                'email' => 'adedejiezekiel28@yahoo.com',
                'phones' => null,
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-12-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FASUSI OLUWATOYIN',
                'email' => 'debbyfasusi@yahoo.com',
                'phones' => null,
                'department_id' => 45,
                'gender' => 'F',
                'birth_date' => '2000-01-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IKUNIKA OPEOLUWA',
                'email' => 'pixtolex2009@yahoo.com',
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-04-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSAWMONYI OSAS',
                'email' => 'jojoasa2@yahoo.com',
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-10-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODUDU BAMIJOKO',
                'email' => 'Bahme.abe125@gmail.com',
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-05-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: " . count($alumni) . " records");
    }
}
