<?php

namespace Database\Seeders\AlumniSeeder;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2004_2005Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::updateOrCreate(
            ['year' => '2004-2005'],
            ['name' => '2004-2005 Set']
        );

        $alumni = [
            [
                'name' => 'AINA EYITAYO',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKPE REMMY',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWEHEWHEJIN VICTOR',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDEJI SUNDAY. O',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBOLU TEMITOPE',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'HAPPY APOGHE',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'RAJI BABATUNDE .M',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FABUNMI OLUMIDE',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BELLO BOLANLE',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TENIOLA ISREAL',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AROWOLO FUNMI',
                'email' => null,
                'phones' => null,
                'department' => 'F',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYINKA . I.A',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABALOLA OLUMIDE',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ISINKALU AJAYI',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ISIMIJOLA FISAYO',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LASISI BOLARINWA',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKPOSIONU IJEOMA',
                'email' => null,
                'phones' => null,
                'department' => 'F',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AELEKOLUJO TOSIN',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINRINMADE ROTIMI',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDIRAN TUNDE',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAGUNDOYE OLUWAGBEMIRO',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBAFUNMILAYO DOTUN',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEMO BECKY',
                'email' => null,
                'phones' => null,
                'department' => 'F',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKEWOLE JOHN',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSALUSI ABOSEDE',
                'email' => null,
                'phones' => null,
                'department' => 'F',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBIYI KEMI',
                'email' => null,
                'phones' => null,
                'department' => 'F',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IDOWU SEFUNMI',
                'email' => null,
                'phones' => null,
                'department' => 'F',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUYEMI OLUWATOSIN',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJOMU USILE',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LALEYE OLUFUNMILOLA',
                'email' => null,
                'phones' => null,
                'department' => 'F',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'NWABUDIKE VICTOR',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFUYE OLUWATOSIN',
                'email' => null,
                'phones' => null,
                'department' => null,
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWONIYI ADEMOLA',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BALOGUN VICTOR',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKEREDOLU FEMI',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALEBIOSU A. B',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAWIBE AYO IYIOLA',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINTOLA YEMI',
                'email' => null,
                'phones' => null,
                'department' => 'M',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBINU BUKOLA',
                'email' => null,
                'phones' => null,
                'department' => 'F',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
