<?php

namespace Database\Seeders\AlumniSeeder;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2016_2017Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::updateOrCreate(
            ['year' => '2016-2017'],
            ['name' => '2016-2017 Set']
        );

        $alumni = [
            [
                'name' => 'ANDREW SHADRACH',
                'email' => null,
                'phones' => ['08189593722'],
                'department' => 'PMT',
                'gender' => 'M',
                'birth_date' => '2000-01-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BELLO BLESSING',
                'email' => 'ninoogus@yahoo.com',
                'phones' => ['07038971302'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-01-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINROTOYE PEACHES',
                'email' => 'peachesakinrotoye@gmail.com',
                'phones' => ['08117659288'],
                'department' => 'FST',
                'gender' => 'F',
                'birth_date' => '2000-01-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABATUNDE OLADIMEJI ZION',
                'email' => 'Oladimejibabatunde665@y.com',
                'phones' => ['08181722349'],
                'department' => 'FWT',
                'gender' => null,
                'birth_date' => '2000-01-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLASUNKANMI ISRAEL AYOADE',
                'email' => null,
                'phones' => ['07061008645'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-01-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FOLORUNSHO OLUWAGBENGA',
                'email' => 'gbengagideonf@gmail.com',
                'phones' => ['08069133140'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-01-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTOLA IBUKUNOLUWA',
                'email' => null,
                'phones' => ['07036330052'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-01-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIRAN OLUWAFEMI',
                'email' => 'oluwafemmy7@gmail.com',
                'phones' => ['07068366737'],
                'department' => 'SVG',
                'gender' => null,
                'birth_date' => '2000-01-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JESUYANMIFE FEYINTOLUWA',
                'email' => 'feyintoluwajesuyanmife@y.com',
                'phones' => null,
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-01-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBAYO OLUWOLE',
                'email' => 'adebayooluwolet@yahoo.com',
                'phones' => ['07032183535'],
                'department' => 'AGE',
                'gender' => 'M',
                'birth_date' => '2000-01-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWOLE  SEGUN O',
                'email' => 'oluwasegun61@yahoo.com',
                'phones' => ['07069505313'],
                'department' => 'MET',
                'gender' => null,
                'birth_date' => '2000-01-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBAJE OMOTOLANI',
                'email' => null,
                'phones' => ['08154028310'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-01-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYENIRAN SIJUADE (ASST. CORD.)',
                'email' => 'Sijuade.oyeniran14@y.com',
                'phones' => ['08031914407'],
                'department' => 'IDD',
                'gender' => 'F',
                'birth_date' => '2000-01-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JESUDOWOLE OPEYEMI DORCAS',
                'email' => 'opsy4il@yahoo.com',
                'phones' => ['08163463753'],
                'department' => 'FWT',
                'gender' => 'F',
                'birth_date' => '2000-01-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FIOLA TOLULOPE',
                'email' => 'Fiola_tolulope@yahoo.com',
                'phones' => ['08105930921'],
                'department' => 'IDD',
                'gender' => 'F',
                'birth_date' => '2000-01-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINNUBI ILEMOBAYO LAURA',
                'email' => null,
                'phones' => ['08162486690'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-01-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYELANA ADENIYI E',
                'email' => 'adeniyielijah@y.com',
                'phones' => ['08174413214'],
                'department' => 'AGY',
                'gender' => null,
                'birth_date' => '2000-01-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOJOLA VICTOR B',
                'email' => 'vikiflex@gmail.com',
                'phones' => ['08099391761'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-01-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO OLADEHINDE P',
                'email' => 'oladehindeojo@gmail.com',
                'phones' => ['08131829834'],
                'department' => 'CVE',
                'gender' => 'M',
                'birth_date' => '2000-01-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNMUYIWA ABAYOMI',
                'email' => null,
                'phones' => ['08106427753'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-02-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JOSEPH AYODEJI',
                'email' => 'jeremiahdejijoseph@y.com',
                'phones' => ['08130563068'],
                'department' => 'ARC',
                'gender' => null,
                'birth_date' => '2000-02-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLARINDE ELIZABETH',
                'email' => null,
                'phones' => ['08138986445'],
                'department' => 'ESM',
                'gender' => null,
                'birth_date' => '2000-02-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAJORIN DAMILOLA',
                'email' => 'Seyihbk87@hotmail.com',
                'phones' => ['07067694595'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-02-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINDOYIN OLUWAFISAYO H',
                'email' => 'Mail2hellen009@y.com',
                'phones' => ['07061945695'],
                'department' => 'STA',
                'gender' => null,
                'birth_date' => '2000-02-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DARAMOLA JOSEPH',
                'email' => 'dreliberty@gmail.com',
                'phones' => ['08107019302'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-02-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SMART G. DANIEL',
                'email' => 'hesjithe@gmail.com',
                'phones' => ['08090964880'],
                'department' => 'MET',
                'gender' => 'M',
                'birth_date' => '2000-02-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALADE FUNMILAYO E',
                'email' => 'Aladefunmilayo67@y.com',
                'phones' => ['07067214845'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-02-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAMISEGBE ADETOYE',
                'email' => null,
                'phones' => ['08137626630'],
                'department' => 'RSG',
                'gender' => null,
                'birth_date' => '2000-02-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'YELE ADEYELE',
                'email' => 'yeledeyele@gmail.com',
                'phones' => ['07068399404'],
                'department' => 'AEC',
                'gender' => null,
                'birth_date' => '2000-02-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADODO OLAOLUWA RAY',
                'email' => 'adodoolaoluwa@gmail.com',
                'phones' => ['08064798196'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-02-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESUYI BLESSING OLUWASEUN',
                'email' => 'bravoblessing@yahoo.com',
                'phones' => ['07068096042'],
                'department' => 'IDD',
                'gender' => 'M',
                'birth_date' => '2000-02-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBELUSI OLORUNTOBA SAMUEL',
                'email' => 'oloruntobaagbelusi@y.com',
                'phones' => ['08180962778'],
                'department' => 'CHE',
                'gender' => null,
                'birth_date' => '2000-02-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLASEHINDE ROTIMI',
                'email' => null,
                'phones' => ['07080940239'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-02-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OPATOKE ABIMBOLA',
                'email' => null,
                'phones' => ['08071667667'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-02-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETOLA OMOWUMI RUTH',
                'email' => null,
                'phones' => null,
                'department' => 'ESM',
                'gender' => null,
                'birth_date' => '2000-02-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLEYE ADEKUNLE ANTHONY',
                'email' => 'Kunleye25@gmail.com',
                'phones' => ['07066122526'],
                'department' => 'MNE',
                'gender' => 'M',
                'birth_date' => '2000-02-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IMORHOA CHARLES',
                'email' => 'imorhoacharles@gmai.com',
                'phones' => ['08110832844'],
                'department' => 'BIO',
                'gender' => 'M',
                'birth_date' => '2000-02-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBULUGBE OLUWANIFEMI',
                'email' => 'adegbulugbenifemi@gmail.com',
                'phones' => ['08100187792'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-02-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'PASEDA SEUN TOYOSI',
                'email' => null,
                'phones' => ['08134866792'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-02-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADOSU MICHAEL OLAYINKA',
                'email' => 'oladosuolayinka@aol.com',
                'phones' => ['08104764101'],
                'department' => 'MET',
                'gender' => 'M',
                'birth_date' => '2000-02-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TIJANI GOODNESS',
                'email' => null,
                'phones' => ['08162028614'],
                'department' => 'SVG',
                'gender' => null,
                'birth_date' => '2000-03-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINTOLURE BUKOLA',
                'email' => 'bukolaakintelure@gmail.com',
                'phones' => ['07032305818'],
                'department' => 'ARE',
                'gender' => 'F',
                'birth_date' => '2000-03-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EDUNWA NELSON',
                'email' => 'edunwanelson@gmail.com',
                'phones' => ['08075000421'],
                'department' => 'AGY',
                'gender' => null,
                'birth_date' => '2000-03-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MUMINI BUKUNMI',
                'email' => 'bestbukunmi@yahoo.com',
                'phones' => ['07032844198'],
                'department' => 'PMT',
                'gender' => 'M',
                'birth_date' => '2000-03-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TALABI YINKA',
                'email' => 'Yinkson01@yahoo.com',
                'phones' => ['08035019999'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-03-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IMUERE DESMOND',
                'email' => 'desmondimuere@gmail.com',
                'phones' => ['08062108459'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-03-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELEGAN OLUWAGBEMI',
                'email' => 'padelegan@yahoo.com',
                'phones' => ['08104812205'],
                'department' => 'TMT',
                'gender' => null,
                'birth_date' => '2000-03-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONWUKA OSITA DAMIAN',
                'email' => 'damianosinache@gmail.com',
                'phones' => ['08130625124'],
                'department' => 'TMT',
                'gender' => null,
                'birth_date' => '2000-03-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKUNLE ADEYINKA',
                'email' => 'Yincute4real@gmail.com',
                'phones' => ['08134705887'],
                'department' => 'ESM',
                'gender' => null,
                'birth_date' => '2000-03-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOPETU MARTINA',
                'email' => 'awopetumartina@gmail.com',
                'phones' => ['08185774147'],
                'department' => 'MET',
                'gender' => 'F',
                'birth_date' => '2000-03-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ELUE GIFT RITA',
                'email' => null,
                'phones' => ['07062778105'],
                'department' => 'AGY',
                'gender' => null,
                'birth_date' => '2000-03-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABIMBOLA JOSHUA SEYI',
                'email' => 'abimbolajoshua24@gmail.com',
                'phones' => ['07035195461'],
                'department' => 'AGE',
                'gender' => 'M',
                'birth_date' => '2000-03-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKEJU OLUWABUSAYO',
                'email' => null,
                'phones' => ['07039405636'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-03-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLADE MIRACLE',
                'email' => 'Toluwase103@gmail.com',
                'phones' => ['08132149729'],
                'department' => 'MME',
                'gender' => 'M',
                'birth_date' => '2000-03-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODETAYO BOLUWATIFE T',
                'email' => 'Odetayo.boluwatife@GMAIL.com',
                'phones' => ['08168558683'],
                'department' => 'AGP',
                'gender' => 'M',
                'birth_date' => '2000-03-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBAYO OLABODE',
                'email' => null,
                'phones' => ['08131316174'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-03-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDANNA PRECIOUS',
                'email' => 'adeayoogundanna@yahoo.com',
                'phones' => ['08052271472'],
                'department' => 'FST',
                'gender' => 'F',
                'birth_date' => '2000-03-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALADE ABAYOMI ADELEKE',
                'email' => null,
                'phones' => ['08146273062'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-03-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEOGUN OLOLADE',
                'email' => 'adeogunololade@gmail.com',
                'phones' => ['07068399402'],
                'department' => 'AEC',
                'gender' => null,
                'birth_date' => '2000-03-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALABI ANUOLUWAPO',
                'email' => null,
                'phones' => ['08103964338'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-03-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODETUNDE OLANREWAJU',
                'email' => 'Odetundeolanrewaju4@gmail.com',
                'phones' => ['08165378693'],
                'department' => 'FWT',
                'gender' => 'M',
                'birth_date' => '2000-03-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAOYE OLUWATIMILEHIN',
                'email' => 'timmiechamp@gmail.com',
                'phones' => ['08131895118'],
                'department' => 'MET',
                'gender' => 'M',
                'birth_date' => '2000-03-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAKARE OLUBUNMI MAYOWA',
                'email' => null,
                'phones' => ['08105764417'],
                'department' => 'SVG',
                'gender' => null,
                'birth_date' => '2000-03-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSEYE SUNDAY',
                'email' => 'sundayakinseye@yahoo.com',
                'phones' => ['08130197355'],
                'department' => 'AGP',
                'gender' => 'M',
                'birth_date' => '2000-03-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KEGBE CYNTHIA UFUOMA',
                'email' => 'cynthiakegbe@yahoo.com',
                'phones' => ['07037230695'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-03-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SOYEBO OPEOLUWA',
                'email' => null,
                'phones' => ['07066251669'],
                'department' => 'STA',
                'gender' => null,
                'birth_date' => '2000-04-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SHEBA WALE',
                'email' => 'shebawale@yahoo.com',
                'phones' => ['806118680'],
                'department' => 'BIO',
                'gender' => 'M',
                'birth_date' => '2000-04-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETULA RICHARD',
                'email' => 'Richard.adetula@gmail.com',
                'phones' => ['08178080946'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-04-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'GODSWILL ADAMU`',
                'email' => null,
                'phones' => ['08163899540'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-04-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KOMOLAFE OLAJUMOKE',
                'email' => 'g.prestige@yahoo.com',
                'phones' => ['08167307084'],
                'department' => 'MCB',
                'gender' => 'F',
                'birth_date' => '2000-04-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AMORE DAMILOLA',
                'email' => 'amoredamilola@gmail.com',
                'phones' => ['08180537549'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-04-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SHITTU OLUWASEUN',
                'email' => 'Holuwarsheunjenny77@gmail.com',
                'phones' => ['08104281382'],
                'department' => 'CSP',
                'gender' => 'M',
                'birth_date' => '2000-04-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNTOKUN ESTHER',
                'email' => 'Esther.oguntokun@yahoo.com',
                'phones' => ['07033829987'],
                'department' => 'BCH',
                'gender' => 'F',
                'birth_date' => '2000-04-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBOWALE MICHAEL A',
                'email' => 'Micade33@gmail.com',
                'phones' => ['08139655742'],
                'department' => 'AGY',
                'gender' => null,
                'birth_date' => '2000-04-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADIPUPO AYORINDE',
                'email' => 'Spik2ayo@gmail.com',
                'phones' => ['08133325847'],
                'department' => 'URP',
                'gender' => 'M',
                'birth_date' => '2000-04-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JOHN ENOBONG',
                'email' => 'johnenobong13@gmail.com',
                'phones' => ['08131241162'],
                'department' => 'MNE',
                'gender' => 'F',
                'birth_date' => '2000-04-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJISEYIRI AJOKE AGNES',
                'email' => null,
                'phones' => ['08060677173'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-04-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYEMI OLUMIDE',
                'email' => 'lumideez@yahoo.co.uk',
                'phones' => ['07061558340'],
                'department' => 'AGY',
                'gender' => 'M',
                'birth_date' => '2000-04-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BALOGUN TUNDE',
                'email' => null,
                'phones' => ['08101034666'],
                'department' => 'ARC',
                'gender' => null,
                'birth_date' => '2000-04-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLABIWONNU ABIODUN DAVID',
                'email' => 'Abiodun.olanbiwonnu@mail.com',
                'phones' => ['08131562545'],
                'department' => 'AGY',
                'gender' => 'M',
                'birth_date' => '2000-04-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUPONNA OLUWATAYO',
                'email' => 'Oluponna22@yahoo.com',
                'phones' => ['07062660497'],
                'department' => 'TMT',
                'gender' => 'M',
                'birth_date' => '2000-04-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWATOBI IYANUOLUWA',
                'email' => 'Iyanutobi1@yahoo.com',
                'phones' => ['08108461412'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-04-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AFE TEMIDAYO EBENEZER',
                'email' => null,
                'phones' => ['07032244087'],
                'department' => 'ARE',
                'gender' => null,
                'birth_date' => '2000-04-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FARAMO ADEWALE',
                'email' => 'Olajustin810@gmail.com',
                'phones' => ['07065124643'],
                'department' => 'EWM',
                'gender' => 'M',
                'birth_date' => '2000-04-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUFUNMI ADEBOWALE',
                'email' => 'Sanvilla69@yahoo.com',
                'phones' => ['07068384392'],
                'department' => 'ARC',
                'gender' => 'M',
                'birth_date' => '2000-04-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBORO EMMANUEL. S',
                'email' => 'sirshanme@gmail.com',
                'phones' => ['08101501553'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-04-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNTOYIN FEMI A',
                'email' => null,
                'phones' => ['08112558135'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-04-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLALEYE ISRAEL OLUMIDE',
                'email' => 'Olaleyeisrael99@livemail.com',
                'phones' => ['08162072200'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-04-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'NZEMEKE CHNEYEM',
                'email' => null,
                'phones' => ['08164463387'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-04-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'LAWAL JAMEAS OLADIPUPO',
                'email' => 'olamultiplylaw@yahoo.com',
                'phones' => ['07063957490'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-04-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLABANJI OLUKUNLE',
                'email' => 'olukay_olas@yahoo.com',
                'phones' => ['07062775848'],
                'department' => 'FAT',
                'gender' => null,
                'birth_date' => '2000-04-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FADIRAN ABIOLA',
                'email' => null,
                'phones' => ['08109820246'],
                'department' => 'ARE',
                'gender' => null,
                'birth_date' => '2000-05-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEKANMI LEKAN',
                'email' => 'l.oyekanmi@yahoo.com',
                'phones' => ['08193560169'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-05-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADEJO MERCY',
                'email' => 'mercyoladejo@yahoo.com',
                'phones' => ['07065852675'],
                'department' => 'SVG',
                'gender' => 'F',
                'birth_date' => '2000-05-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKUNUGA OLUWATOSIN S',
                'email' => 'Okunnugaoluwatosin@yahoo.com',
                'phones' => ['08136062810'],
                'department' => 'CHE',
                'gender' => 'M',
                'birth_date' => '2000-05-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINDELE DAVID',
                'email' => null,
                'phones' => ['08134150054'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-05-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBAYO VICTOR B',
                'email' => 'Vadebayo16@yahoo.com',
                'phones' => ['08149333273'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-05-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEYEMI SEFUNMI',
                'email' => null,
                'phones' => ['08166135613'],
                'department' => 'AEC',
                'gender' => null,
                'birth_date' => '2000-05-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAJIDE ADEMOLA',
                'email' => 'Olajideademola84@gmail.com',
                'phones' => ['08106174438'],
                'department' => 'MEE',
                'gender' => 'M',
                'birth_date' => '2000-05-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EJIGA SHADRACH',
                'email' => 'ejigashadrach@yahoo.com',
                'phones' => ['08166680878'],
                'department' => 'AEC',
                'gender' => null,
                'birth_date' => '2000-05-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKELEYE OLOLADE',
                'email' => 'Lolade.okeleye2@gmail.com',
                'phones' => ['08104374166'],
                'department' => 'EMT',
                'gender' => 'F',
                'birth_date' => '2000-05-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBOBOYE JOHNSON',
                'email' => 'ifedayojohn@gmail.com',
                'phones' => ['08130817586'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-05-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'GARBA JOHN SIMEON',
                'email' => 'garbaj@gmail.com',
                'phones' => ['08142251571'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-05-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBOOLA OLUWATOSIN',
                'email' => 'tosinagboolalizzy@yahoo.com',
                'phones' => ['08138703688'],
                'department' => 'STA',
                'gender' => 'F',
                'birth_date' => '2000-05-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BHADMUS OLUFUNKE',
                'email' => 'phunkepet@yahoo.com',
                'phones' => ['07036361316'],
                'department' => 'MCB',
                'gender' => 'M',
                'birth_date' => '2000-05-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINDELE DAVID K',
                'email' => 'Davidkehinde41@yahoo.com',
                'phones' => ['08134150054'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-05-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKANDE ADEOLA',
                'email' => null,
                'phones' => ['07062308800'],
                'department' => 'ARE',
                'gender' => null,
                'birth_date' => '2000-05-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'THOMAS VICTORIA',
                'email' => 'Vot4god@yahoo.com',
                'phones' => ['08165934217'],
                'department' => 'FST',
                'gender' => null,
                'birth_date' => '2000-05-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DADA FELIX O',
                'email' => null,
                'phones' => ['08163680582'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-05-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'VINCENT PHILLIP E',
                'email' => 'vincentphilipemmam@yahoo.co',
                'phones' => ['07081639709'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-05-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYELE PELUMI',
                'email' => 'pelumiakinyele@gmail.com',
                'phones' => ['07064845657'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-05-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAGBAMIGBE TAIWO',
                'email' => 'Fagbamigbe_taiwo@yahoo.com',
                'phones' => ['07035618481'],
                'department' => 'ARE',
                'gender' => null,
                'birth_date' => '2000-05-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MASEBINU GODWIN O.',
                'email' => 'Godwinmasebinu@yahoo.com',
                'phones' => ['08169770810'],
                'department' => 'TMT',
                'gender' => 'M',
                'birth_date' => '2000-05-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADODO VICTORIA',
                'email' => null,
                'phones' => ['08161830430'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-05-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODUO SUNDAY',
                'email' => null,
                'phones' => ['07069644691'],
                'department' => 'ESM',
                'gender' => null,
                'birth_date' => '2000-05-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IMOLETUYI BUKOLA',
                'email' => null,
                'phones' => ['08130004645'],
                'department' => 'EWM',
                'gender' => null,
                'birth_date' => '2000-05-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONIBI ABISOLA O.',
                'email' => 'Onibiabisola1@yahoo.com',
                'phones' => ['07062427374'],
                'department' => 'MTS',
                'gender' => 'F',
                'birth_date' => '2000-05-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINMABOGUNJE ADELAJA',
                'email' => null,
                'phones' => ['08100257430'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JOLAOYE SAMUEL O',
                'email' => 'jolaoyesamuel12@gmail.com',
                'phones' => ['08162846503'],
                'department' => 'TMT',
                'gender' => 'M',
                'birth_date' => '2000-05-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEYE SAMUEL A',
                'email' => 'Sadeyeye44@yahoo.com',
                'phones' => ['07030563936'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-05-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADARAMOLA OLUWASEYI',
                'email' => 'oluwaseyiadaramola@yahoo.com',
                'phones' => ['08186798622'],
                'department' => 'MNE',
                'gender' => 'M',
                'birth_date' => '2000-05-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EWEBAJO OLUWASEYI',
                'email' => 'seyiewebajo@gmail.com',
                'phones' => ['08179058217'],
                'department' => 'PHY',
                'gender' => 'M',
                'birth_date' => '2000-05-31',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JAGUN OMOLARA',
                'email' => 'Larryluv4christ@yahoo.com',
                'phones' => ['07084970736'],
                'department' => 'MTS',
                'gender' => 'F',
                'birth_date' => '2000-06-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IJANUSI IYINTITO',
                'email' => 'iyintitoijanusi@gmail.com',
                'phones' => ['08181624364'],
                'department' => 'CSP',
                'gender' => 'F',
                'birth_date' => '2000-06-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBOLA BAYO',
                'email' => null,
                'phones' => ['08161378656'],
                'department' => 'AGE',
                'gender' => null,
                'birth_date' => '2000-06-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUMIDE ABIMBOLA',
                'email' => null,
                'phones' => ['08130963932'],
                'department' => 'FST',
                'gender' => null,
                'birth_date' => '2000-06-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINDELE BABATUNDE',
                'email' => null,
                'phones' => ['07065850070'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-06-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAJIDE ABIMBOLA',
                'email' => null,
                'phones' => ['08102308036'],
                'department' => 'EMT',
                'gender' => null,
                'birth_date' => '2000-06-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLOKUN SAMUEL',
                'email' => null,
                'phones' => ['07039396068'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-06-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINWANDE PRECIOUS',
                'email' => null,
                'phones' => ['08062133105'],
                'department' => 'MCB',
                'gender' => null,
                'birth_date' => '2000-06-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEJUMO OLAJIDE',
                'email' => 'Adejumo_olajide@yahoo.com',
                'phones' => ['08187718821'],
                'department' => 'MTS',
                'gender' => 'M',
                'birth_date' => '2000-06-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDOKUN MARIA KEHINDE',
                'email' => 'kadedokunmaria@yahoo.com',
                'phones' => ['08102483789'],
                'department' => 'SVG',
                'gender' => 'F',
                'birth_date' => '2000-06-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAWAIYE OLUWASEYI',
                'email' => null,
                'phones' => ['07066039722'],
                'department' => 'MET',
                'gender' => null,
                'birth_date' => '2000-06-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IRIKEFE ONORIODE',
                'email' => 'onosiaeffe@gmail.com',
                'phones' => ['08071160555'],
                'department' => 'AGP',
                'gender' => 'M',
                'birth_date' => '2000-06-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWABUYI ABIMBOLA',
                'email' => 'bimbowande@gmail.com',
                'phones' => ['08063121221'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-06-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEPOJU ADEDAYO',
                'email' => 'adedayoelizabeth@yahoo.com',
                'phones' => ['08161133757'],
                'department' => 'BDG',
                'gender' => 'F',
                'birth_date' => '2000-06-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEDUGBE IREOLUWA',
                'email' => 'ireoluwaenoch@gmail.com',
                'phones' => ['09032985942'],
                'department' => 'AGP',
                'gender' => 'M',
                'birth_date' => '2000-06-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARAYELA JESUTOFUNMI',
                'email' => null,
                'phones' => ['08163788912'],
                'department' => 'BIO',
                'gender' => null,
                'birth_date' => '2000-06-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKONTA EVELYN N',
                'email' => null,
                'phones' => ['07037808375'],
                'department' => 'MCB',
                'gender' => null,
                'birth_date' => '2000-06-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAGUNJU TOSIN',
                'email' => null,
                'phones' => ['08100991362'],
                'department' => 'IDD',
                'gender' => null,
                'birth_date' => '2000-06-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYIYI HARRY',
                'email' => null,
                'phones' => ['08131387552'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-07-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MAKINDE SAMUEL B',
                'email' => 'samakkybest@gmail.com',
                'phones' => ['08139279193'],
                'department' => 'AGE',
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IDRIS OLUWATOSIN D',
                'email' => 'Edrisedris09@yahoo.com',
                'phones' => ['08062084964'],
                'department' => 'AGY',
                'gender' => 'M',
                'birth_date' => '2000-07-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKOYE PATRICK',
                'email' => 'Pokoye91@gmail.com',
                'phones' => ['08103436020'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-07-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEDIRAN OYEWOLE',
                'email' => 'oyediraoyewole@gmail.com',
                'phones' => ['08167237626'],
                'department' => 'MST',
                'gender' => 'M',
                'birth_date' => '2000-07-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESANYA SEUN',
                'email' => null,
                'phones' => ['08081430332'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-07-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUREMI SAMUEL',
                'email' => 'Samyom1995@yahoo.com',
                'phones' => ['08136617017'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-07-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TAIWO OMOWUYI',
                'email' => null,
                'phones' => ['08136058141'],
                'department' => 'CSP',
                'gender' => null,
                'birth_date' => '2000-07-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOYEDE ITUNUOLUWA',
                'email' => 'Highteewzy.mo@gmail.com',
                'phones' => ['07037186252'],
                'department' => 'BDG',
                'gender' => 'M',
                'birth_date' => '2000-07-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELUSI BUSAYO',
                'email' => 'floxybright@rocketmail.com',
                'phones' => ['08065170937'],
                'department' => 'ARE',
                'gender' => 'F',
                'birth_date' => '2000-07-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIRAN S FRANSIS',
                'email' => 'franciscares4u@gmail.com',
                'phones' => ['08169819600'],
                'department' => 'BCH',
                'gender' => 'M',
                'birth_date' => '2000-07-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEGUN GABRIEL',
                'email' => 'Talk2mcgcleff@yahoomail.com',
                'phones' => ['08176497044'],
                'department' => 'MET',
                'gender' => null,
                'birth_date' => '2000-07-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUGOSI OLUSOLA',
                'email' => 'olabayomisola@yahoo.com',
                'phones' => ['08108658225'],
                'department' => 'PMT',
                'gender' => 'M',
                'birth_date' => '2000-07-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYENIYO OLAYEMI',
                'email' => 'ayeniyoolayemi@gmail.com',
                'phones' => ['07033416630'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-07-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYEBAMERU DOYINSOLA',
                'email' => 'ayebamerudoyin@yahoo.com',
                'phones' => ['07036266050'],
                'department' => 'ESM',
                'gender' => 'F',
                'birth_date' => '2000-07-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALAO SUNDAY',
                'email' => null,
                'phones' => ['08034543960'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-07-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI MOYINOLUWA',
                'email' => 'Ajayimoyinoluwa895@yahoo.com',
                'phones' => ['08025116947'],
                'department' => 'PHY',
                'gender' => 'M',
                'birth_date' => '2000-07-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DIXON OLUWATOSIN',
                'email' => null,
                'phones' => ['08135356264'],
                'department' => 'AGY',
                'gender' => null,
                'birth_date' => '2000-07-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJALA AFOLABI NIYI',
                'email' => 'Andy_valentino007@yahoo.com',
                'phones' => ['08108461584'],
                'department' => 'STA',
                'gender' => 'M',
                'birth_date' => '2000-07-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINKUNMI TOLULOPE',
                'email' => 'tolulopeakinkunmi@yahoo.com',
                'phones' => ['08036957592'],
                'department' => 'FWT',
                'gender' => 'F',
                'birth_date' => '2000-07-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAJIDE DAMILOLA',
                'email' => 'damilola.olajide@yahoo.com',
                'phones' => ['08135945669'],
                'department' => 'MTS',
                'gender' => 'M',
                'birth_date' => '2000-07-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYONNU ADETOYE',
                'email' => null,
                'phones' => ['08035897857'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-07-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWANIYI BLESSING',
                'email' => null,
                'phones' => ['08136563699'],
                'department' => 'TMT',
                'gender' => null,
                'birth_date' => '2000-07-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAPADE SEGUN',
                'email' => 'isaacolap@yahoo.com',
                'phones' => ['08132354454'],
                'department' => 'CHE',
                'gender' => null,
                'birth_date' => '2000-07-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEKOLA OLAITAN',
                'email' => 'oyekolapetr@yahoo.com',
                'phones' => ['08108623249'],
                'department' => 'CSP',
                'gender' => 'M',
                'birth_date' => '2000-07-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABFEMI AYODELE',
                'email' => 'josephbabafemi@yahoo.com',
                'phones' => ['08085240192'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-07-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEJUMOBI VICTORIA',
                'email' => null,
                'phones' => ['08072498752'],
                'department' => 'FAT',
                'gender' => null,
                'birth_date' => '2000-07-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKUNLE DAMILARE',
                'email' => 'Adekunle21952@gmail.com',
                'phones' => ['08160248430'],
                'department' => 'ARC',
                'gender' => null,
                'birth_date' => '2000-07-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINDOLURE FOLARIN',
                'email' => 'Akindolure9@gmail.com',
                'phones' => ['08103143156'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-07-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNGBEMI OLUWASUNKANMI',
                'email' => 'paulobotos@gmail.com',
                'phones' => ['08168338204'],
                'department' => 'FST',
                'gender' => 'M',
                'birth_date' => '2000-07-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TITILADUNAYO SAMUEL',
                'email' => 'samtitiladunayo@yahoo.com',
                'phones' => ['08163320776'],
                'department' => 'MCB',
                'gender' => 'M',
                'birth_date' => '2000-07-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAMIGBOYE EMMANUEL',
                'email' => 'Emmabammy5@gmail.com',
                'phones' => ['08108106849'],
                'department' => 'ARC',
                'gender' => null,
                'birth_date' => '2000-07-31',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLALEYE OLUWASEUN',
                'email' => 'heritageolaleye@gmail.com',
                'phones' => ['08138312588'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-08-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OPEYEMI GIDEON O.',
                'email' => 'opeyemigideon@yahoo.com',
                'phones' => ['08108094431'],
                'department' => 'STA',
                'gender' => null,
                'birth_date' => '2000-08-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINYEMI AKINJIDE',
                'email' => null,
                'phones' => ['08134005802'],
                'department' => 'MME',
                'gender' => null,
                'birth_date' => '2000-08-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENOLA EMMANUEL',
                'email' => null,
                'phones' => ['08025241332'],
                'department' => 'MET',
                'gender' => null,
                'birth_date' => '2000-08-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASHOLA OLUWASEYI',
                'email' => 'Asholadavid@ymail.com',
                'phones' => ['08107213453'],
                'department' => 'ESM',
                'gender' => null,
                'birth_date' => '2000-08-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMONIYI OLUWATOBILOBA M.',
                'email' => 'Tobiloba.omoniyi@yahoo.com',
                'phones' => ['08137592285'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-08-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => '‘DIMIPE BAYO',
                'email' => null,
                'phones' => ['07030508174'],
                'department' => 'MET',
                'gender' => null,
                'birth_date' => '2000-08-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IHUA GBUBEMI PETER',
                'email' => 'Atomicwave2009@yahoo.com',
                'phones' => ['08039465943'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-08-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO OLUWATAYO',
                'email' => null,
                'phones' => ['07063316028'],
                'department' => 'AGE',
                'gender' => null,
                'birth_date' => '2000-08-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALEYE OLADAYO',
                'email' => null,
                'phones' => ['08188641225'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-08-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELUMO TEMITOPE',
                'email' => null,
                'phones' => ['08060489016'],
                'department' => 'RSG',
                'gender' => null,
                'birth_date' => '2000-08-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOLEYE DAMILOLA',
                'email' => 'Daryeleen485510@gmail.com',
                'phones' => ['07034865800'],
                'department' => 'CSP',
                'gender' => 'F',
                'birth_date' => '2000-08-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLANIPEKUN OLOLADE',
                'email' => null,
                'phones' => ['08111912228'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-08-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBOOLA OLUWASEUN PETER',
                'email' => 'Niflex000@gmail.com',
                'phones' => ['07038278974'],
                'department' => 'MET',
                'gender' => null,
                'birth_date' => '2000-08-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONIBI ABISOLA',
                'email' => 'onibiabisola1@yahoo.com',
                'phones' => ['07062427374'],
                'department' => 'MTS',
                'gender' => 'F',
                'birth_date' => '2000-08-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALUFA SOLA',
                'email' => null,
                'phones' => ['08135387664'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-08-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALMAROOF OLAITAN',
                'email' => 'horlaitejrocker@gmail.com',
                'phones' => ['08166495561'],
                'department' => 'MTS',
                'gender' => 'M',
                'birth_date' => '2000-08-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADUBI TEMITOPE',
                'email' => 'adubitemitope@gmail.com',
                'phones' => ['07065597080'],
                'department' => 'AGE',
                'gender' => 'F',
                'birth_date' => '2000-09-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SHITTU OLUWASEUN A.',
                'email' => null,
                'phones' => ['08104281382'],
                'department' => 'CSP',
                'gender' => null,
                'birth_date' => '2000-09-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNNEYE SAMUEL',
                'email' => null,
                'phones' => ['08068081313'],
                'department' => 'FWT',
                'gender' => null,
                'birth_date' => '2000-09-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'QUADRI OLAYINKA REUBEN',
                'email' => 'Reubenquadri5@gmail.com',
                'phones' => ['08095317051'],
                'department' => 'ARE',
                'gender' => null,
                'birth_date' => '2000-09-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYEBODE VICTOR O',
                'email' => 'Excelvictosin19@gmail.com',
                'phones' => ['08167997025'],
                'department' => 'STA',
                'gender' => 'M',
                'birth_date' => '2000-09-06',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODEPIDAN JOSHUA  O.',
                'email' => 'joushman@yahoo.com',
                'phones' => ['08183048484'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-09-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEYEMI OLUWAPELUMI',
                'email' => null,
                'phones' => ['08139619664'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-09-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AMOWE BUSAYO',
                'email' => 'amoweolubusayo@gmail.com',
                'phones' => ['08062897222'],
                'department' => 'CSC',
                'gender' => 'F',
                'birth_date' => '2000-09-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATIMILEYIN SUNDAY',
                'email' => 'olatimileyindamilola@gmail.com',
                'phones' => ['09034438582'],
                'department' => 'URP',
                'gender' => 'M',
                'birth_date' => '2000-09-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEYE VICTORIA B',
                'email' => 'V_adeyeye@yahoo.com',
                'phones' => ['07065177225'],
                'department' => 'BIO',
                'gender' => 'F',
                'birth_date' => '2000-09-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAIYA OLUSOLA',
                'email' => 'Olusola.olaya@yahoo.com',
                'phones' => ['08167405294'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-09-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELEYE ADEDAPO',
                'email' => 'dapsjoe@yahoo.com',
                'phones' => ['07062328929'],
                'department' => 'CHE',
                'gender' => null,
                'birth_date' => '2000-09-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADIGUN AYOMIPOSI',
                'email' => 'Ayomiposiabiola@yahoo.com',
                'phones' => ['07064390598'],
                'department' => 'AGP',
                'gender' => 'F',
                'birth_date' => '2000-09-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKEREJOLA OLUWATOSIN',
                'email' => 'Jolatosin23@yahoo.com',
                'phones' => ['08166617155'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-09-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SUNDAY EMMANUEL ADAH',
                'email' => 'emmydissolis@yahoo.com',
                'phones' => ['08076499607'],
                'department' => 'MCB',
                'gender' => null,
                'birth_date' => '2000-09-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'POWE JOHN',
                'email' => 'Powe74@gmail.com',
                'phones' => ['08065703007'],
                'department' => 'CSC',
                'gender' => 'M',
                'birth_date' => '2000-09-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLEYE SUNDAY',
                'email' => 'Fdalex09@yahoo.com',
                'phones' => ['08165349401'],
                'department' => 'MET',
                'gender' => null,
                'birth_date' => '2000-09-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEFISOYE KAYODE',
                'email' => 'Adefisoyeblessing@rocketmail.com',
                'phones' => ['09030985746'],
                'department' => 'CSP',
                'gender' => 'M',
                'birth_date' => '2000-09-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLADOYINBO BABATUNDE',
                'email' => null,
                'phones' => ['08189348692'],
                'department' => 'FWT',
                'gender' => null,
                'birth_date' => '2000-09-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAGUNJU DESMOND',
                'email' => null,
                'phones' => ['07062598295'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-09-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TEMITOPE PHILLIPS',
                'email' => 'temitopephil@gmail.com',
                'phones' => ['08101079657'],
                'department' => 'AGY',
                'gender' => null,
                'birth_date' => '2000-09-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MICHAEL ALADETAN',
                'email' => 'alaskaaladetan@yahoo.com',
                'phones' => ['08111786976'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-09-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BALOGUN OYEWUNMI FAITH',
                'email' => 'aderinsolaoyewunmi@gmail.com',
                'phones' => ['07063872166'],
                'department' => 'STA',
                'gender' => null,
                'birth_date' => '2000-10-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MEDOYE OLUSOJI I.',
                'email' => 'Medoye.olusoji@yahoo.com',
                'phones' => ['08033487856'],
                'department' => 'MNE',
                'gender' => 'M',
                'birth_date' => '2000-10-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AMOKADE TAIWO',
                'email' => null,
                'phones' => ['08062888230'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-10-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DOSUNMU ADEYINKA',
                'email' => 'Adeyinkaolusegun29@gmail.com',
                'phones' => ['08188641263'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-10-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABIDOYE OMOLARA.V',
                'email' => 'abidoyeomolara11@yahoo.com',
                'phones' => ['08133661991'],
                'department' => 'MCB',
                'gender' => 'F',
                'birth_date' => '2000-10-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'HAMMOND OLUWOLE',
                'email' => 'holuwole@yahoo.com',
                'phones' => ['08031186934'],
                'department' => 'URP',
                'gender' => 'M',
                'birth_date' => '2000-10-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAGBOHUN TEMITAYO',
                'email' => 'Jtayo1@yahoo.com',
                'phones' => ['08169344883'],
                'department' => 'BCH',
                'gender' => 'M',
                'birth_date' => '2000-10-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DAHUNSI JOY',
                'email' => null,
                'phones' => ['08127626604'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-10-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABIDAKUN IFEDAYO AYOMIDE',
                'email' => 'abidakunifedayo@yahoo.com',
                'phones' => ['08131812707'],
                'department' => 'EWM',
                'gender' => 'M',
                'birth_date' => '2000-10-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'COKER IFEOLUWA GREGORY',
                'email' => 'Ifecoker03@gmail.com',
                'phones' => ['08168566711'],
                'department' => 'URP',
                'gender' => 'M',
                'birth_date' => '2000-10-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLALEYE ISRAEL',
                'email' => null,
                'phones' => ['08166722949'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-10-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'NZETEH NWAKAEGO',
                'email' => 'nwakaegonzeteh@yahoo.com',
                'phones' => ['07034072256'],
                'department' => 'QSV',
                'gender' => 'F',
                'birth_date' => '2000-10-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JIMOH OMOWUNMI',
                'email' => 'bjmary@gmail.com',
                'phones' => ['08169153372'],
                'department' => 'MTS',
                'gender' => 'F',
                'birth_date' => '2000-10-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEMO OLUBUNMI',
                'email' => 'Supergal0001@yahoo.com',
                'phones' => ['08136121401'],
                'department' => 'QSV',
                'gender' => 'F',
                'birth_date' => '2000-10-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLABODE EMMANUEL',
                'email' => null,
                'phones' => ['07069248190'],
                'department' => 'BIO',
                'gender' => null,
                'birth_date' => '2000-10-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEBAMIJI FOLAHANMI',
                'email' => null,
                'phones' => ['08139459145'],
                'department' => 'AGY',
                'gender' => null,
                'birth_date' => '2000-10-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEYE BOSEDE',
                'email' => null,
                'phones' => ['07065174225'],
                'department' => 'BIO',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIGBA SAMUEL',
                'email' => 'Samuelforgod@yahoo.com',
                'phones' => ['07069697442'],
                'department' => 'STA',
                'gender' => null,
                'birth_date' => '2000-10-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAMOSAYA ADEDAYO',
                'email' => null,
                'phones' => ['08161874828'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-10-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DARAMOLA TOLU',
                'email' => 'Daramola_tolu@yahoo.com',
                'phones' => ['08132808685'],
                'department' => 'STA',
                'gender' => null,
                'birth_date' => '2000-10-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBITE OLUWAFEMI',
                'email' => 'adegbitefemisamson@gmail.com',
                'phones' => ['07065256580'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-10-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYEGORO OLUWABOR',
                'email' => 'oluwabori@gmail.com',
                'phones' => ['07066736598'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-10-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOSANMI DAMILARE NAOMI',
                'email' => 'Dami_tunbi@yahoo.com',
                'phones' => ['07035644633'],
                'department' => 'FST',
                'gender' => 'F',
                'birth_date' => '2000-10-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUKOJU AYOMIDE',
                'email' => 'johnolukoju@gmail.com',
                'phones' => ['07039139808'],
                'department' => 'AGY',
                'gender' => null,
                'birth_date' => '2000-10-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IGE WLSON T',
                'email' => 'Ige.wilson.tosin@gmail.com',
                'phones' => ['08101075333'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-10-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNFOLAJU OLALEKAN',
                'email' => 'ogunfolajuolalekan94@yahoo.com',
                'phones' => ['08050383611'],
                'department' => 'CVE',
                'gender' => 'M',
                'birth_date' => '2000-10-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGAGBAYI OLUMUYIWA',
                'email' => 'Muyiwaogagbayi @yahoo.com',
                'phones' => ['08130809883'],
                'department' => 'BCH',
                'gender' => 'M',
                'birth_date' => '2000-10-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI WURAOLA',
                'email' => 'olufolayemi@gmail.com',
                'phones' => ['08062521771'],
                'department' => 'MCB',
                'gender' => 'F',
                'birth_date' => '2000-11-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAMILONI OLAJUMOKE',
                'email' => null,
                'phones' => ['08130700540'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-11-06',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJELADE PELUMI',
                'email' => 'Pelumi_pelumi@yahoo.co.uk',
                'phones' => ['08188233946'],
                'department' => 'AGY',
                'gender' => 'M',
                'birth_date' => '2000-11-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADENIYI MATTEUW',
                'email' => null,
                'phones' => ['07067433046'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-11-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWON FAARI TEMITOPE',
                'email' => 'topzy@gmail.com',
                'phones' => ['09039572491'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-11-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJIBOYE YETUNDE',
                'email' => 'D2dmama@yahoo.com',
                'phones' => ['07038604105'],
                'department' => 'FAT',
                'gender' => 'F',
                'birth_date' => '2000-11-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEWUYI ADEBIMPE',
                'email' => 'Bimpay2013@yahoo.com',
                'phones' => ['07069732071'],
                'department' => 'MTS',
                'gender' => 'F',
                'birth_date' => '2000-11-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MOHAMMED IDRIS OLUSESI',
                'email' => 'meedris@yahoo.com',
                'phones' => ['08034105165'],
                'department' => 'QSV',
                'gender' => 'M',
                'birth_date' => '2000-11-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'JEGEDE SEUN',
                'email' => 'Seunjege4christ@yahoo.com',
                'phones' => ['08109791041'],
                'department' => 'BDG',
                'gender' => 'M',
                'birth_date' => '2000-11-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOTOSHO SEGUN S',
                'email' => null,
                'phones' => ['08065957752'],
                'department' => 'TMT',
                'gender' => null,
                'birth_date' => '2000-11-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ABGETOLA OLUWAFEMI',
                'email' => 'Agbetola24@gmail.com',
                'phones' => ['08164635963'],
                'department' => 'MCB',
                'gender' => 'M',
                'birth_date' => '2000-11-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINRO AYODEJI',
                'email' => 'akinroayodeji@yahoo.com',
                'phones' => ['08100001064'],
                'department' => 'ARE',
                'gender' => null,
                'birth_date' => '2000-11-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'USIFO MARY',
                'email' => 'hardesuwa@yahoo.com',
                'phones' => ['08100075253'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-11-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAFASAKIN OLATUNJI',
                'email' => 'Fashtee92@gmail.com',
                'phones' => ['08026067235'],
                'department' => 'IDD',
                'gender' => null,
                'birth_date' => '2000-11-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGBETOLA OLUWAFEMI',
                'email' => 'Oluwafemi4me@gmail.com',
                'phones' => ['08164635963'],
                'department' => 'MCB',
                'gender' => null,
                'birth_date' => '2000-11-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SOBOWALE RAPHEAL. A',
                'email' => 'raphealsobowale@gmail.com',
                'phones' => ['08178146047'],
                'department' => 'MTS',
                'gender' => 'M',
                'birth_date' => '2000-11-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KAYODE SHERIF A',
                'email' => 'Kayodesherifadebayo@gmail.com',
                'phones' => ['07065179782'],
                'department' => 'AGE',
                'gender' => 'M',
                'birth_date' => '2000-12-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYENI  TEMIDAYO',
                'email' => 'Dayuscharity2003@yahoo.com',
                'phones' => ['08030422426'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-12-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYA ADEKUNLE',
                'email' => 'Adeya_mccoy@yahoo.com',
                'phones' => ['07037967499'],
                'department' => 'FAT',
                'gender' => null,
                'birth_date' => '2000-12-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ATANLUSI EMMANUELLA',
                'email' => 'thayutha@yahoo.com',
                'phones' => ['08147120929'],
                'department' => 'MET',
                'gender' => 'F',
                'birth_date' => '2000-12-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAJULUGBE OPEYEMI',
                'email' => 'Clavicord4jazz@gmail.com',
                'phones' => ['08134669711'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-12-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASIGOH ODUNAYO',
                'email' => 'asigoh2@gmail.com',
                'phones' => ['08101651717'],
                'department' => 'AGP',
                'gender' => 'M',
                'birth_date' => '2000-12-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'TAYLOR OLUWASEYI',
                'email' => 'Taylotseyi45@yahoo.com',
                'phones' => ['08162017900'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-12-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINGBOYE PATRICIA',
                'email' => 'Odunayo4path@yahoo.com',
                'phones' => ['08168678954'],
                'department' => 'CSP',
                'gender' => null,
                'birth_date' => '2000-12-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALADE SIMILEOLUWA',
                'email' => 'simileoluwafalade@yahoo.co.uk',
                'phones' => ['07038305040'],
                'department' => 'BCH',
                'gender' => 'F',
                'birth_date' => '2000-12-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKEBUNMI ODUNAYO',
                'email' => null,
                'phones' => ['08081811957'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-12-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLASANMI OLAYINKA',
                'email' => 'olasphushorolasphushor@yahoo.c',
                'phones' => ['07030429334'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-12-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FADEBI OLADOTUN O',
                'email' => 'keluvdoyun@gmail.com',
                'phones' => ['08175172180'],
                'department' => 'CHE',
                'gender' => 'M',
                'birth_date' => '2000-12-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DARAMOLA ADEKUNLE',
                'email' => 'Kunledorams @ovi.com',
                'phones' => ['08107536436'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-12-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KEHINDE ABIODUN',
                'email' => 'Toallmypals2005@yahoo.com',
                'phones' => ['08052792996'],
                'department' => 'ESM',
                'gender' => 'M',
                'birth_date' => '2000-12-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJIBUWA BENEDICT',
                'email' => 'obewediet@yahoo.com',
                'phones' => ['08130949540'],
                'department' => 'ARE',
                'gender' => null,
                'birth_date' => '2000-12-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAKARE RAMOTA O',
                'email' => 'Littlerammy4luv@yahoo.com',
                'phones' => ['08107070880'],
                'department' => 'BCH',
                'gender' => 'F',
                'birth_date' => '2000-12-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGBAYE BIDEMI',
                'email' => null,
                'phones' => ['08036075659'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-12-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINNUGBA DEBORAH',
                'email' => 'akindebrah@gmail.com',
                'phones' => ['08067499229'],
                'department' => 'ESM',
                'gender' => 'F',
                'birth_date' => '2000-12-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOGUNLOYE SUNDAY',
                'email' => null,
                'phones' => ['08162322002'],
                'department' => 'FAT',
                'gender' => null,
                'birth_date' => '2000-12-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLALERE OLAPEGBA',
                'email' => null,
                'phones' => ['07032929535'],
                'department' => 'MET',
                'gender' => null,
                'birth_date' => '2000-12-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGORIOYE DAVID',
                'email' => 'adegborioyedavid@gmail.com',
                'phones' => ['07062174036'],
                'department' => 'MCB',
                'gender' => 'M',
                'birth_date' => '2000-12-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEWOLE KAYODE',
                'email' => 'Oyewole.kayode@yahoo.com',
                'phones' => ['09033481448'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-12-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'QUIST OLAJUMOKE',
                'email' => null,
                'phones' => ['08094233447'],
                'department' => 'AEC',
                'gender' => null,
                'birth_date' => '2000-12-30',
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
