<?php

namespace Database\Seeders\AlumniSeeder;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2009_2010Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::updateOrCreate(
            ['year' => '2009-2010'],
            ['name' => '2009-2010 Set']
        );

        $alumni = [
            [
                'name' => 'Taiwo Babatunde',
                'email' => 'teta_tun@yahoo.com',
                'phones' => ['08069069630'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-01-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adesuyi O. Samuel (Prince)',
                'email' => 'princesammy4god@yahoo.com',
                'phones' => ['08033738797'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-01-06',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oni Temitope',
                'email' => 'temiaph@yahoo.com',
                'phones' => ['16312200435'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-01-06',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Omogunwa Babajide',
                'email' => 'jydemm@yahoo.co.uk',
                'phones' => ['08069393228'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-01-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Omotayo Tosin',
                'email' => 'tosinomotayo2000@yahoo.co.uk',
                'phones' => ['08060928118'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-01-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oyeniran Oluwabunmi',
                'email' => 'buntos2001@yahoo.com',
                'phones' => ['07032983885'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-01-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Osalusi Babatunde',
                'email' => 'tundex_s@yahoo.com',
                'phones' => ['08058308221'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-01-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajayi Olugbenga',
                'email' => 'ajayigbenga37@yahoo.com',
                'phones' => ['07033089935'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-01-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oyeyipo Temitope Funmi',
                'email' => null,
                'phones' => ['07034507947'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-01-31',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinola Tayelolu V.',
                'email' => 'tyvctr@yahoo.com',
                'phones' => ['08064631626'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-02-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oginni Olakunle',
                'email' => 'kunlesze88@yahoo.com',
                'phones' => ['08151915858'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-02-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oni S. Oluwalayo',
                'email' => 'slayomi@yahoo.com',
                'phones' => ['08062871300'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-02-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Mustapha Mahmud O.',
                'email' => 'de\'concepts08@yahoo.com',
                'phones' => ['08022488965'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-02-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Obienwe Amechi E.C',
                'email' => 'obienwe.amechi@yahoo.com,obienwe.amechi@gmail.com,kastrofigure@yahoo.co.uk',
                'phones' => ['08038226951'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-02-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Odewale Temitope',
                'email' => 'dammytop2004@yahoo.com',
                'phones' => ['08034168335'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-02-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olaiya Olatunji',
                'email' => 'teejaybros@yahoo.com',
                'phones' => ['08062279763'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-02-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajayi Olusegun M.',
                'email' => 'maolus2010@yahoo.com',
                'phones' => ['08067907065'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-02-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Falona Rotimi',
                'email' => 'rhoteh@gmail.com',
                'phones' => ['07067812964'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-02-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Balogun Olabisi',
                'email' => 'bissynol@yahoo.co.uk',
                'phones' => ['08030781684'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-02-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Momoh Belove O.',
                'email' => 'dabelovedtech@yahoo.com',
                'phones' => ['08134055749'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-03-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Kudehinbu W. Taiwo',
                'email' => 'taiwokudehinbu@yahoo.co.uk',
                'phones' => ['07033954323'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-03-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adedeji Funmi',
                'email' => 'fumi4real212@yahoo.com',
                'phones' => ['08067647317'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-03-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Alabi Olukemi Eunice',
                'email' => 'kemzychem@yahoo.com',
                'phones' => ['08063123886'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-03-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Okunlola Fiyinfoluwa',
                'email' => 'fiyin.okunlola@yahoo.com, fiyin.okunlola@gmail.com',
                'phones' => ['08038556197'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Aiyesa Olatunde',
                'email' => 'tudnoxzyl@yahoo.com',
                'phones' => ['07034418331'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adamolekun Tunde',
                'email' => 'tunman@yahoo.com',
                'phones' => ['08067907417'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olisa Adewale K.',
                'email' => 'olisaadewalek@yahoo.com',
                'phones' => ['08065217533'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajibola Temidayo',
                'email' => 'temmypiano@yahoo.com',
                'phones' => ['07033320543'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adisa Oluwafemi A.',
                'email' => 'femmyland@yahoo.com',
                'phones' => ['08053826919'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Nkwuka Chinedu',
                'email' => 'chinedu2rule@yahoo.com',
                'phones' => ['07032270917'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olaleye Shalom',
                'email' => null,
                'phones' => ['08035273655'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeoba Oyenike Mary',
                'email' => 'nikmay03@yahoo.com',
                'phones' => ['08062836269'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-06',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adesuyi Tosin',
                'email' => 'toussier01@yahoo.com',
                'phones' => ['08067117237'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Odanye Bunmi',
                'email' => 'odanyebunmi@yahoo.com',
                'phones' => ['08062795444'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Odewole Tomiwa',
                'email' => 'omoodewole@yahoo.com',
                'phones' => ['08132366272'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Areola Ifeoluwa O.',
                'email' => 'ife.areola@yahoo.com',
                'phones' => ['08066154302'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ayodele Ayodeji T.',
                'email' => 'ayodeejoo4luv06@yahoo.com',
                'phones' => ['08038128263'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinnibi Olufemi V.',
                'email' => 'kool_fm4real@yahoo.com',
                'phones' => ['07032716420'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Igbe Tobore',
                'email' => 'tobore2_ng@yahoo.com',
                'phones' => ['07063316938'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-04-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Amoo-Onidundu, Adedoyin (nee Haastrup)',
                'email' => 'aeamoo5@gmail.com, seun_strup4luv@yahoo.com',
                'phones' => ['08029096564'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-05-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olomo Omotola',
                'email' => 'olomotola@yahoo.com',
                'phones' => ['07032769232'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-05-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Betiku Olakunle S.',
                'email' => 'betiku@yahoo.com',
                'phones' => ['08035889802'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-05-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adelugba Omolara',
                'email' => 'omolaraadelugba@yahoo.com',
                'phones' => ['08060714709'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-05-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oluwaleye Adeleke',
                'email' => 'lekeoluwaleye@yahoo.com',
                'phones' => ['08063040378'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-05-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Aderinluwo Kemi E.',
                'email' => 'kemistry6320@yahoo.com',
                'phones' => ['07037845020'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-05-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Asogbon Mojisola G.',
                'email' => 'mojiasho@yahoo.com',
                'phones' => ['08064383679'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-05-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Owobumuyi Tolulope',
                'email' => 'toluowobumuyi@yahoo.com',
                'phones' => ['08038089626'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-05-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeyemi Adelayo T.',
                'email' => 'zecloid@yahoo.com',
                'phones' => ['08023503685'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-05-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adesina Busola',
                'email' => 'buscolaplace@yahoo.com',
                'phones' => ['07039585074'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-05-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Durojaye Titilope',
                'email' => 'duro2heart@yahoo.com',
                'phones' => ['07033385160'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Emasailue Godwin',
                'email' => 'wonos95@yahoo.com',
                'phones' => ['08038226584'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Babalola Damilola. O',
                'email' => 'calldamie4luv@yahoo.com',
                'phones' => ['08068303506'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olatominrin Ololade',
                'email' => 'lizrichola@yahoo.com',
                'phones' => ['07035015251'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ojo Sarah Abosede',
                'email' => 'sarah.abosede@yahoo.com',
                'phones' => ['08053614608'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oladipo Oladiran Solomon',
                'email' => 'oladee4sure@yahoo.com',
                'phones' => ['08068457761'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adedoyin James Adebisi',
                'email' => 'jamebiz@yahoo.co.uk',
                'phones' => ['08033703813'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Abodunrin Babajide B.',
                'email' => 'babajide4u@yahoo.com',
                'phones' => ['08034916324'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinmuleya Sumbo',
                'email' => 'sumboinfuta@yahoo.com',
                'phones' => ['07035755547'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeyemo A.A',
                'email' => null,
                'phones' => ['08061202308'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adegoke Olaoluwa A.',
                'email' => 'adegokeolaoluwaadeniyi515@gmail.com',
                'phones' => ['07036536772'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-06-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oladuji Yewande F.',
                'email' => 'perfectjuly@ymail.com',
                'phones' => ['08065036743'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinmabogunje Niyi',
                'email' => 'nuhycoolj@yahoo.com',
                'phones' => ['08032165888'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Macaulay Babajide Milton',
                'email' => 'mclonex@yahoo.com/babajidemacaulay@gmail.com',
                'phones' => ['447574885638'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-06',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Fagborun Tunmise',
                'email' => 'thimoty007@yahoo.com',
                'phones' => ['08038000903'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adewale Shofolabo',
                'email' => null,
                'phones' => ['08029296157'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Osatuyi Olusola',
                'email' => 'porima86@yahoo.com',
                'phones' => ['07084400150'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Abe John',
                'email' => 'johnnery2003@yahoo.com',
                'phones' => ['08038211322'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olagunju Benson',
                'email' => 'masekid2097@yahoo.co.uk',
                'phones' => ['08066906651'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Famakin Lanre S.',
                'email' => 'tumiss2002@yahoo.co.uk',
                'phones' => ['08068265443'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Jebutu Olawale',
                'email' => 'jebsontcube@yahoo.com',
                'phones' => ['08024464301'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Kuye Babatunde A.',
                'email' => 'tducks2003@yahoo.com',
                'phones' => ['08050760380'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-07-31',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinfolarin Olusanya',
                'email' => 'brotherlye@yahoo.co.uk',
                'phones' => ['08066652530'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Dada Adeyinka',
                'email' => null,
                'phones' => ['08066555144'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ipaye Daniel A.',
                'email' => 'daniel_2@yahoo.com',
                'phones' => ['08034452039'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olofinlade Funbi O.',
                'email' => 'funbinchi@yahoo.com',
                'phones' => ['08039428925'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Yode Owolade Adedotun',
                'email' => 'adedotunyode@yahoo.com, dotmant@gmail.com',
                'phones' => ['08037520573'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Monehin Peter Segun',
                'email' => 'pmonehin@yahoo.com',
                'phones' => ['08068782858'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Bayode Kehinde',
                'email' => 'kbayode_2008@yahoo.com',
                'phones' => ['08038934438'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinbiosose Oluyemi C.',
                'email' => null,
                'phones' => ['07066453297'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Tijani Funmi',
                'email' => 'funmiteejayi1@yahoo.com',
                'phones' => ['08025773198'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Obideji Olaoluwa A.',
                'email' => 'ask4boolove@yahoo.com',
                'phones' => ['08039662955'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogunniran M. Kayode',
                'email' => 'oguns4ril@yahoo.co.uk, ogunnirankayode@yahoo.com',
                'phones' => ['08066335527'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-08-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oyakhilome Michael',
                'email' => 'ayomikky2@yahoo.co.uk',
                'phones' => ['08020877570'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-09-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ilesanmi Olusegun I.',
                'email' => 'segzale007@yahoo.com',
                'phones' => ['08033440168'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-09-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Jegede Olakunle',
                'email' => 'arcjegedeolakunle@yahoo.com',
                'phones' => ['07037113855'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-09-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Osungbaro Adeyinka',
                'email' => 'yemyte4035@yahoo.com',
                'phones' => ['08035411623'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-09-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Afolabi Opeyemi',
                'email' => 'searchseun@yahoo.com',
                'phones' => ['07061275946'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-09-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Onun Gift K.',
                'email' => 'gift_onun@yahoo.com',
                'phones' => ['08067621293'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-09-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinmoladun Tope O.',
                'email' => 'akinmoladuntope@yahoo.com',
                'phones' => ['08067903115'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-09-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinde Bunmi P.',
                'email' => 'princilliayes@yahoo.co.uk',
                'phones' => ['08066091241'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-09-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Awoyemi Afolabi O.',
                'email' => 'folico56@yahoo.com',
                'phones' => ['08035195206'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-09-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogunmilade Joseph O.',
                'email' => 'sollyjoeguy_real@yahoo.com',
                'phones' => ['08030466036'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-09-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Agboola Tomiwa',
                'email' => 'tommybanji@hotmail.com',
                'phones' => ['08138033436'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olaoye Samuel',
                'email' => 'tjcruise2007@yahoo.co.uk',
                'phones' => ['08067864251'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oyedotun Oluwatoyin E',
                'email' => 'beckiousBabe@yahoo.com',
                'phones' => ['08034699040'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-06',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Owonifari Olusegun E',
                'email' => 'mrsegun87@yahoo.com',
                'phones' => ['08060758546'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-06',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Azike uchenna N.',
                'email' => 'saved2seal@yahoo.com',
                'phones' => ['08024088099'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olomiyesan Durojaye',
                'email' => 'olomiyesan@yahoo.co.uk',
                'phones' => ['08135957351'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Aro Oluwabukola',
                'email' => 'bukolaseun@gmail.com',
                'phones' => ['07038119688'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Fatunmole Oluronke',
                'email' => 'ronkybabes1234@yahoo.com',
                'phones' => ['08062081663'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Osadare Ebenezer O.',
                'email' => 'osara4real@yahoo.com',
                'phones' => ['08035419519'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ayedero Victor',
                'email' => 'victor4top@yahoo.com',
                'phones' => ['08066083885'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adesanmi Victor Adeolu',
                'email' => 'victoradesanmi@yahoo.com',
                'phones' => ['08033717513'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Owojori Fadekemi A',
                'email' => 'Kemi_fadeke@yahoo.com',
                'phones' => ['08032092869'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Onwuka Juliet',
                'email' => 'gift_onwuka@yahoo.com',
                'phones' => ['07039555292'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajele Omolarami Olusola',
                'email' => 'omolaraajele@gmail.com, ajeleomolarami@yahoo.ca',
                'phones' => ['08132128966'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adedeji Adenike V.',
                'email' => 'royalheart145@yahoo.com',
                'phones' => ['08025917802'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-10-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oni Taiwo, O',
                'email' => 'coatson005@yahoo.com',
                'phones' => ['08024652450'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Kofoworola Oluwayemisi Joke',
                'email' => 'yemivp@yahoo.com',
                'phones' => ['08051257386'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olowola Olumide',
                'email' => 'olowolaolumide@yahoo.com',
                'phones' => ['08053510319'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Bolarinwa Oluwaseyi A.',
                'email' => 'seymol@yahoo.co.uk',
                'phones' => ['08020634463'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Omole Olumuyiwa Niyi',
                'email' => 'distacode@yahoo.com',
                'phones' => ['07031545239'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Omogunlaye Olusegun Yemi',
                'email' => 'omogunlayeolusegun@yahoo.com',
                'phones' => ['08059981896'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Fakorede Oluwaseun',
                'email' => 'oluwaseunfakorede@yahoo.com',
                'phones' => ['08088571940'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Esan Oyedele Olalekan',
                'email' => 'oyedeleesan@yahoo.com',
                'phones' => ['08063443818'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oshunubi Oladimeji',
                'email' => 'oshodimeji@yahoo.com',
                'phones' => ['08088096110'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Merayebu Segun',
                'email' => 'segunmera@yahoo.com',
                'phones' => ['07039170757'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ekperusi Joshua A.',
                'email' => 'geebry-2@yahoo.com',
                'phones' => ['08039161090'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Williams Babajide',
                'email' => 'babswills2003@yahoo.com',
                'phones' => ['08034188840'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Megbowon Omolere',
                'email' => 'megbowon@yahoo.com',
                'phones' => ['08066467017'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Obolo Olanrewaju',
                'email' => 'calarry@yahoo.com',
                'phones' => ['08062706652'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ojo olusola',
                'email' => 'duppysolex@yahoo.com',
                'phones' => ['08032431192'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-12-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Dada Ajibola Abisoye',
                'email' => 'gdjibs@yahoo.com',
                'phones' => ['08025958433'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-12-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Fatayo Imoleayo T.',
                'email' => 'f.imoleayo@gmail.com',
                'phones' => ['08060244281'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-12-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Lawani Olabisi B.',
                'email' => 'bissylaw@yahoo.co.uk',
                'phones' => ['08060706169'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-12-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Fapetu Abimbola',
                'email' => null,
                'phones' => ['07036844188'],
                'department' => null,
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeyeye Yemi O.',
                'email' => 'adeyeye_yemi@yahoo.com, yemi.ifsa@gmail.com',
                'phones' => ['447438566758'],
                'department' => null,
                'gender' => null,
                'birth_date' => '2000-11-25',
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
