<?php

namespace Database\Seeders;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2012_2013Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2012-2013'],
            ['name' => '2012-2013 Set']
        );

        $alumni = [
            [
                'name' => 'Disu Francis Abiodun',
                'email' => null,
                'phones' => ['08084229208'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-01-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Alawode Adedayo',
                'email' => null,
                'phones' => ['07032283817'],
                'department' => 'CHE',
                'gender' => null,
                'birth_date' => '2000-01-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeyeye Olumide',
                'email' => null,
                'phones' => ['08169774763'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-01-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogunbiyi Temitope',
                'email' => null,
                'phones' => ['08064393103'],
                'department' => 'FST',
                'gender' => null,
                'birth_date' => '2000-01-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinmulero Funmilayo',
                'email' => null,
                'phones' => ['07062964901'],
                'department' => 'AEE',
                'gender' => null,
                'birth_date' => '2000-01-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Omogbemi Nelson D.',
                'email' => null,
                'phones' => ['08066503889'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-01-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinmolayan Oluwafemi Paul',
                'email' => null,
                'phones' => ['08067898531'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-01-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogunmodede Tolulope B.',
                'email' => null,
                'phones' => ['08037722407'],
                'department' => 'BIO',
                'gender' => null,
                'birth_date' => '2000-01-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajayi Oluwatosin',
                'email' => null,
                'phones' => ['07036555818'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-01-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Tijani Abiola',
                'email' => null,
                'phones' => ['08025323332'],
                'department' => 'FAT',
                'gender' => null,
                'birth_date' => '2000-01-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akintoroye Oluwakayomide F.',
                'email' => null,
                'phones' => ['08139353268'],
                'department' => 'IDD',
                'gender' => null,
                'birth_date' => '2000-01-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Amona Elizabeth',
                'email' => null,
                'phones' => ['08166809866'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-01-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akintuyi Akinyele P.',
                'email' => null,
                'phones' => ['08026755862'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-01-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Babatunde Tosin Kunle',
                'email' => null,
                'phones' => ['08137511559'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-01-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinmolayan Mercy T.',
                'email' => null,
                'phones' => ['07031814134'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-01-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeola Johnson',
                'email' => null,
                'phones' => ['07066295525'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-01-31',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adegbulugbe Adebola',
                'email' => null,
                'phones' => ['08038232709'],
                'department' => 'AEE',
                'gender' => null,
                'birth_date' => '2000-01-31',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oladapo Temitope S.',
                'email' => null,
                'phones' => ['07081619585'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-01-31',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Kayode Oyeyemi S.',
                'email' => null,
                'phones' => ['07061286132'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-02-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oke Aduragbemi',
                'email' => null,
                'phones' => ['08067030503'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-02-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Amogbon Tunde',
                'email' => null,
                'phones' => ['07032241291'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-02-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Orisaiku Olusola Precious',
                'email' => null,
                'phones' => ['08038631848'],
                'department' => 'STAT',
                'gender' => null,
                'birth_date' => '2000-02-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Afolabi Ayoola J.',
                'email' => null,
                'phones' => ['08032499009'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-02-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Odeyemi Babatunde',
                'email' => null,
                'phones' => ['08037288150'],
                'department' => 'EWM',
                'gender' => null,
                'birth_date' => '2000-02-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Omotosho Olanrewaju',
                'email' => null,
                'phones' => ['08051158039'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-02-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Alexander O.T',
                'email' => null,
                'phones' => ['08037748191'],
                'department' => 'AGE',
                'gender' => null,
                'birth_date' => '2000-02-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogunyomi Idowu G.',
                'email' => null,
                'phones' => ['08062107242'],
                'department' => 'MME',
                'gender' => null,
                'birth_date' => '2000-02-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ojo Ayodeji O.',
                'email' => null,
                'phones' => ['08061501940'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-03-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Opayinka Sanjo',
                'email' => null,
                'phones' => ['08087079198'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-03-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akanbi Segun',
                'email' => null,
                'phones' => ['08063805455'],
                'department' => 'ESM',
                'gender' => null,
                'birth_date' => '2000-03-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olonilua Idowu E.',
                'email' => null,
                'phones' => ['08068385211'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-03-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinkumi Temitope',
                'email' => null,
                'phones' => ['07031254338'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-03-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oke Oluwaseun Sunday',
                'email' => null,
                'phones' => ['07032353716'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-03-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Iso Maxwell O.',
                'email' => null,
                'phones' => ['08074438965'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-03-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Bello Olanrewaju',
                'email' => null,
                'phones' => ['08068355451'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-03-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Daramola Olumuyiwa',
                'email' => null,
                'phones' => ['07063708447'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-03-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olaniyan Damilola',
                'email' => null,
                'phones' => ['08065979655'],
                'department' => 'AEE',
                'gender' => null,
                'birth_date' => '2000-03-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeyina Omowunmi Esther',
                'email' => null,
                'phones' => ['07034641907'],
                'department' => 'MCB',
                'gender' => null,
                'birth_date' => '2000-04-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adesola Ojo',
                'email' => null,
                'phones' => ['08039775360'],
                'department' => 'ARC',
                'gender' => null,
                'birth_date' => '2000-04-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Aguda Temitope O.',
                'email' => null,
                'phones' => ['08134684751'],
                'department' => 'FST',
                'gender' => null,
                'birth_date' => '2000-04-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogunmuyiwa Emmanuel',
                'email' => null,
                'phones' => ['08037901224'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-04-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinduro Femi',
                'email' => null,
                'phones' => ['07064990898'],
                'department' => 'CSP',
                'gender' => null,
                'birth_date' => '2000-04-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olofinyokun Opeyemi',
                'email' => null,
                'phones' => ['08132909913'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-04-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adebayo Damilola A.',
                'email' => null,
                'phones' => ['08139298593'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-04-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ojodale Stephen S.',
                'email' => null,
                'phones' => ['08060893201'],
                'department' => 'MCB',
                'gender' => null,
                'birth_date' => '2000-04-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Falola Oluseye',
                'email' => null,
                'phones' => ['08033356987'],
                'department' => 'AGE',
                'gender' => null,
                'birth_date' => '2000-04-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olonisola Damilola F.',
                'email' => null,
                'phones' => ['08135891947'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-04-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olowookere Omoniyi',
                'email' => null,
                'phones' => ['08039628997'],
                'department' => 'IDD',
                'gender' => null,
                'birth_date' => '2000-04-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olusola Damilola',
                'email' => null,
                'phones' => ['08039678630'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-04-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogundele Subomi',
                'email' => null,
                'phones' => ['08067001867'],
                'department' => 'TMT',
                'gender' => null,
                'birth_date' => '2000-04-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oladapo Oluwarotimi S.',
                'email' => null,
                'phones' => ['08061529845'],
                'department' => 'FST',
                'gender' => null,
                'birth_date' => '2000-04-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Osore Oludare',
                'email' => null,
                'phones' => ['08035790908'],
                'department' => 'ARC',
                'gender' => null,
                'birth_date' => '2000-04-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Nwaimo Chioma',
                'email' => null,
                'phones' => ['07065949854'],
                'department' => 'ESM',
                'gender' => null,
                'birth_date' => '2000-04-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oloidi Opeyemi',
                'email' => null,
                'phones' => ['07033690482'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-04-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Fadahunsi Oluwasegun J.',
                'email' => null,
                'phones' => ['08065847676'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-04-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Jeje Olufunmilayo D.',
                'email' => null,
                'phones' => ['08137468819'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-04-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Elegbede Olawale J.',
                'email' => null,
                'phones' => ['08060993095'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-04-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adekunle Adebimpe b.',
                'email' => null,
                'phones' => ['07066295209'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-05-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Osowo Oladayo',
                'email' => null,
                'phones' => ['08025301045'],
                'department' => 'BIO',
                'gender' => null,
                'birth_date' => '2000-05-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogedengbe Olumide',
                'email' => null,
                'phones' => ['08023995512'],
                'department' => 'BIO',
                'gender' => null,
                'birth_date' => '2000-05-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ayadi Olusoji Q.',
                'email' => null,
                'phones' => null,
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-05-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akanbi Victor Olusola',
                'email' => null,
                'phones' => ['07033700970'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-05-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajala Oluwatolani',
                'email' => null,
                'phones' => ['08066482439'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-05-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olatimehin Folukemi',
                'email' => null,
                'phones' => ['08063085709'],
                'department' => 'ESM',
                'gender' => null,
                'birth_date' => '2000-05-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akerele Olalekan A.',
                'email' => null,
                'phones' => ['08034299975'],
                'department' => 'BIO',
                'gender' => null,
                'birth_date' => '2000-05-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olaremi Samuel O.',
                'email' => null,
                'phones' => ['08087844236'],
                'department' => 'IDD',
                'gender' => null,
                'birth_date' => '2000-05-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Obajuluwa Olumide',
                'email' => null,
                'phones' => ['08130620576'],
                'department' => 'CHE',
                'gender' => null,
                'birth_date' => '2000-05-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Salawu Michael A.',
                'email' => null,
                'phones' => ['08060124319'],
                'department' => 'MME',
                'gender' => null,
                'birth_date' => '2000-05-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akerele Tobi',
                'email' => null,
                'phones' => ['08084364209'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-05-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Apantaku Temitope',
                'email' => null,
                'phones' => ['08162391172'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-05-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adaramola Gideon',
                'email' => null,
                'phones' => ['07032827407'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-05-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeate Banke R.',
                'email' => null,
                'phones' => ['07069569425'],
                'department' => 'PMT',
                'gender' => null,
                'birth_date' => '2000-05-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Lawani Gideon',
                'email' => null,
                'phones' => ['07066132654'],
                'department' => 'FWT',
                'gender' => null,
                'birth_date' => '2000-05-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Asogbon Olumide M.',
                'email' => null,
                'phones' => ['08038381289'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-05-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Elegbede Roland',
                'email' => null,
                'phones' => ['07030294966'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-05-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Babagbemi Oluwabunmi',
                'email' => null,
                'phones' => ['07032473790'],
                'department' => 'CSP',
                'gender' => null,
                'birth_date' => '2000-05-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Erwerhahwe Ejineghene J.',
                'email' => null,
                'phones' => ['08029075359'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-06-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Amusa J.O',
                'email' => null,
                'phones' => ['08185708137'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-06-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oluwajana Morounfoluwa A.',
                'email' => null,
                'phones' => ['08029075359'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-06-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Philip Ariyo',
                'email' => null,
                'phones' => ['07032473790'],
                'department' => 'CSP',
                'gender' => null,
                'birth_date' => '2000-06-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Emore Onomo',
                'email' => null,
                'phones' => ['07032642788'],
                'department' => 'TMT',
                'gender' => null,
                'birth_date' => '2000-06-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akindoyin Oluwafemi B.',
                'email' => null,
                'phones' => ['08089940853'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-06-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Popoola Yeyunde O.',
                'email' => null,
                'phones' => ['07035658195'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-06-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Alebiosu Olumide Gladstone',
                'email' => null,
                'phones' => ['07032716595'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-06-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Abaas Alade A.',
                'email' => null,
                'phones' => ['08067643700'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-06-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogunyemi Olasunkanmi P.',
                'email' => null,
                'phones' => ['07030342149'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-06-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adesola Sunday J.',
                'email' => null,
                'phones' => ['07036315450'],
                'department' => 'ARC',
                'gender' => null,
                'birth_date' => '2000-06-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ojo Temitope',
                'email' => null,
                'phones' => ['08060889174'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-06-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olatundun Dayo',
                'email' => null,
                'phones' => ['07062395681'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-06-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajayi Oluwatosin',
                'email' => null,
                'phones' => ['08067728533'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-06-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ladipo Seun',
                'email' => null,
                'phones' => ['08132363295'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-06-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Abisoye Ayodeji J.',
                'email' => null,
                'phones' => ['07033787268'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => '2000-06-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adegunsoye Folasade K.',
                'email' => null,
                'phones' => ['08068496850'],
                'department' => 'MCB',
                'gender' => null,
                'birth_date' => '2000-07-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Bamidele Gbemiga M.',
                'email' => null,
                'phones' => ['07034588702'],
                'department' => 'IDD',
                'gender' => null,
                'birth_date' => '2000-07-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Apuabi Oladapo',
                'email' => null,
                'phones' => ['08035319765'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-07-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajiboye Oluwaseye K.',
                'email' => null,
                'phones' => ['08060835678'],
                'department' => 'CHE',
                'gender' => null,
                'birth_date' => '2000-07-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adedeji Adeyinka',
                'email' => null,
                'phones' => ['08039266361'],
                'department' => 'AGE',
                'gender' => null,
                'birth_date' => '2000-07-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Apuabi Oluwasina',
                'email' => null,
                'phones' => ['08035319864'],
                'department' => 'CHE',
                'gender' => null,
                'birth_date' => '2000-07-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Anthony Kolawole B.',
                'email' => null,
                'phones' => ['07033774981'],
                'department' => 'TMT',
                'gender' => null,
                'birth_date' => '2000-07-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Jimoh Adegoke',
                'email' => null,
                'phones' => ['07065949724'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-07-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Jones Feyisike',
                'email' => null,
                'phones' => ['07031397791'],
                'department' => 'AGE',
                'gender' => null,
                'birth_date' => '2000-07-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adamolugbe Funmilayo',
                'email' => null,
                'phones' => ['07036216279'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-07-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogungbesan Bankole',
                'email' => null,
                'phones' => ['08060815359'],
                'department' => 'IDD',
                'gender' => null,
                'birth_date' => '2000-07-22',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajaraye George O.',
                'email' => null,
                'phones' => ['08067189007'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-07-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adewumi Oyewole Isaac',
                'email' => null,
                'phones' => ['08063019715'],
                'department' => 'APH',
                'gender' => null,
                'birth_date' => '2000-07-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogundare Oluwatoyin A.',
                'email' => null,
                'phones' => ['07057807052'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-07-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Kadiri Oluwasegun O.',
                'email' => null,
                'phones' => ['07082176400'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-08-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Iraoya Ausitine',
                'email' => null,
                'phones' => ['08060831308'],
                'department' => 'AEE',
                'gender' => null,
                'birth_date' => '2000-08-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Nojeem Idris A.',
                'email' => null,
                'phones' => ['08051122280'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-08-02',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeebowale Muyiwa',
                'email' => null,
                'phones' => ['07030480818'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-08-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Egbon Osafu Augustine',
                'email' => null,
                'phones' => ['07038976018'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-08-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeagbo Gbenga A.',
                'email' => null,
                'phones' => ['07033659066'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-08-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinpelu Emmanuel',
                'email' => null,
                'phones' => ['08036165652'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-08-16',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adebayo Babatunde I.',
                'email' => null,
                'phones' => ['08071599555'],
                'department' => 'FST',
                'gender' => null,
                'birth_date' => '2000-08-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinmade Osayemi',
                'email' => null,
                'phones' => ['08130567579'],
                'department' => 'ESM',
                'gender' => null,
                'birth_date' => '2000-08-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Aborisade Lawrence',
                'email' => null,
                'phones' => ['08168275435'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-08-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oloniyo Seun',
                'email' => null,
                'phones' => ['08132129140'],
                'department' => 'FWT',
                'gender' => null,
                'birth_date' => '2000-08-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Fadele Opeoluwa E.',
                'email' => null,
                'phones' => ['08068853574'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-08-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ejimonye Paulyn K.',
                'email' => null,
                'phones' => ['08030509254'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-09-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ayoola Adeola O.',
                'email' => null,
                'phones' => ['07031175344'],
                'department' => 'EWM',
                'gender' => null,
                'birth_date' => '2000-09-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Julius Dare Isreal',
                'email' => null,
                'phones' => ['08060972906'],
                'department' => 'ARC',
                'gender' => null,
                'birth_date' => '2000-09-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Yusuf Olawale',
                'email' => null,
                'phones' => ['08037480374'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-09-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Odion Ayo-Oluwa',
                'email' => null,
                'phones' => ['08038278284'],
                'department' => 'CHE',
                'gender' => null,
                'birth_date' => '2000-09-15',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinyoade Akinpelu J.',
                'email' => null,
                'phones' => ['08138366622'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-09-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Osanyemi Mosimiloluwa',
                'email' => null,
                'phones' => ['08064956825'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-09-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ademodi Omowunmi',
                'email' => null,
                'phones' => ['07068417638'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-09-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Anyasodor Hayes K.',
                'email' => null,
                'phones' => ['07033740235'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-09-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Iluyemi Victor',
                'email' => null,
                'phones' => ['07060540338'],
                'department' => 'CVE',
                'gender' => null,
                'birth_date' => '2000-09-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinsulu Samuel A',
                'email' => null,
                'phones' => ['07032270741'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-10-01',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Alli Modupe',
                'email' => null,
                'phones' => ['08026013252'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-10-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ojo Oluwadare',
                'email' => null,
                'phones' => ['07064990884'],
                'department' => 'AEE',
                'gender' => null,
                'birth_date' => '2000-10-04',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Osunmo Kolawole G.',
                'email' => null,
                'phones' => ['08063091175'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-10-08',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adekanbi Abayomi',
                'email' => null,
                'phones' => ['07062320423'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-10-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Fadamoro Joy',
                'email' => null,
                'phones' => ['07062045167'],
                'department' => 'BIO',
                'gender' => null,
                'birth_date' => '2000-10-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oluwatosin Oluwake D.',
                'email' => null,
                'phones' => ['08137780205'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-10-13',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ogidan Ebenezer',
                'email' => null,
                'phones' => ['08038036363'],
                'department' => 'ARC',
                'gender' => null,
                'birth_date' => '2000-10-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinwande Toluwani S.',
                'email' => null,
                'phones' => ['07030424829'],
                'department' => 'CHE',
                'gender' => null,
                'birth_date' => '2000-10-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajani Olabisi Kikelomo',
                'email' => null,
                'phones' => ['08060360489'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-10-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Fapohunda Kofo',
                'email' => null,
                'phones' => ['07039480981'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-10-23',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Babatunde Olajide',
                'email' => null,
                'phones' => ['08033801622'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-10-25',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oyinlola Oluwafemi',
                'email' => null,
                'phones' => ['08161111123'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-10-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Omotayo Oluwatobi',
                'email' => null,
                'phones' => ['07031699912'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-10-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oke Babatunde',
                'email' => null,
                'phones' => ['08037700049'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-10-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinbisose Akinwunmi O.',
                'email' => null,
                'phones' => ['08165664565'],
                'department' => 'PHY',
                'gender' => null,
                'birth_date' => '2000-10-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ekanoye Dayo',
                'email' => null,
                'phones' => ['08037529341'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-10-30',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Iriburum Joam Aboghene',
                'email' => null,
                'phones' => ['07035762979'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-11-03',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oyedotun Femi',
                'email' => null,
                'phones' => ['08068205863'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-11-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Obabueki Osarume F.',
                'email' => null,
                'phones' => ['07066033222'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => '2000-11-07',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Doyin-Dada .A. Layo',
                'email' => null,
                'phones' => ['07037626785'],
                'department' => 'EEE',
                'gender' => null,
                'birth_date' => '2000-11-09',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinloye Omotayo',
                'email' => null,
                'phones' => ['08063093583'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-11-10',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinyemi Sola S.',
                'email' => null,
                'phones' => ['08057260931'],
                'department' => 'BCH',
                'gender' => null,
                'birth_date' => '2000-11-11',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adekunle Tolulope Abigail',
                'email' => null,
                'phones' => ['07033875074'],
                'department' => 'MCB',
                'gender' => null,
                'birth_date' => '2000-11-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajewole Timothy',
                'email' => null,
                'phones' => ['08035068331'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-11-17',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olaniyan Victor O.',
                'email' => null,
                'phones' => ['08060336753'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-11-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Mulero Opeyemi Abraham',
                'email' => null,
                'phones' => ['08066010408'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => '2000-11-20',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Macauly Paul',
                'email' => null,
                'phones' => ['07036555717'],
                'department' => 'AGE',
                'gender' => null,
                'birth_date' => '2000-11-21',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Omoniyi Oluwatobi',
                'email' => null,
                'phones' => ['07034314307'],
                'department' => 'AGE',
                'gender' => null,
                'birth_date' => '2000-11-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oke Tosin',
                'email' => null,
                'phones' => ['07035437521'],
                'department' => 'MEE',
                'gender' => null,
                'birth_date' => '2000-11-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adeoye Fadeke',
                'email' => null,
                'phones' => ['08074674079'],
                'department' => 'AEE',
                'gender' => null,
                'birth_date' => '2000-11-26',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adekunle Temitope S.',
                'email' => null,
                'phones' => ['08138268032'],
                'department' => 'MME',
                'gender' => null,
                'birth_date' => '2000-11-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Bobade Toyin',
                'email' => null,
                'phones' => ['07061103580'],
                'department' => 'EWM',
                'gender' => null,
                'birth_date' => '2000-11-28',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Agoola Arije',
                'email' => null,
                'phones' => ['07064337124'],
                'department' => 'QSV',
                'gender' => null,
                'birth_date' => '2000-11-29',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akinbode Sanmi',
                'email' => null,
                'phones' => ['08067619805'],
                'department' => 'FAT',
                'gender' => null,
                'birth_date' => '2000-12-05',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ajayi Paul',
                'email' => null,
                'phones' => ['07032407256'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-12-12',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Konigbagbe Ayotunde',
                'email' => null,
                'phones' => ['07069569044'],
                'department' => 'MME',
                'gender' => null,
                'birth_date' => '2000-12-14',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Popoola Taiwo O.',
                'email' => null,
                'phones' => ['07064303803'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-12-18',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Farayola Kanyinsola',
                'email' => null,
                'phones' => ['08132129169'],
                'department' => 'BIO',
                'gender' => null,
                'birth_date' => '2000-12-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Adara Mojisola',
                'email' => null,
                'phones' => ['08130567503'],
                'department' => 'ESM',
                'gender' => null,
                'birth_date' => '2000-12-19',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Akeresola Abiodun',
                'email' => null,
                'phones' => ['07038065476'],
                'department' => 'MNE',
                'gender' => null,
                'birth_date' => '2000-12-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Isiaka Tinuke',
                'email' => null,
                'phones' => ['08138493443'],
                'department' => 'EWM',
                'gender' => null,
                'birth_date' => '2000-12-24',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Olalekan Labode A.',
                'email' => null,
                'phones' => ['07029637516'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-12-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oladepo Ireti Isaac',
                'email' => null,
                'phones' => ['07036323633'],
                'department' => 'URP',
                'gender' => null,
                'birth_date' => '2000-12-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Elusoji Samuel O.',
                'email' => null,
                'phones' => ['08068773905'],
                'department' => 'FST',
                'gender' => null,
                'birth_date' => '2000-12-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ojo Adedayo',
                'email' => null,
                'phones' => ['08038142774'],
                'department' => 'AGE',
                'gender' => null,
                'birth_date' => '2000-12-27',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Rotimi Ifedayo Nelson',
                'email' => null,
                'phones' => ['08063806325'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Matthew Tope David',
                'email' => null,
                'phones' => ['08137271767'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oruku Sunday',
                'email' => null,
                'phones' => null,
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Egbokhare O. James',
                'email' => null,
                'phones' => ['08034151214'],
                'department' => 'AGP',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oke Olatunji A.',
                'email' => null,
                'phones' => ['08084679999'],
                'department' => 'CSC',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Oki Overcomer',
                'email' => null,
                'phones' => ['07068404945'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Otagbo Evelyn',
                'email' => null,
                'phones' => ['08036921473'],
                'department' => 'STAT',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'Ojo Donald',
                'email' => null,
                'phones' => ['08022552152'],
                'department' => 'MTS',
                'gender' => null,
                'birth_date' => null,
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: ".count($alumni).' records');
    }
}
