<?php

namespace Database\Seeders\AlumniSeeder;

use App\Models\Alumnus;
use App\Models\Tenure;
use Illuminate\Database\Seeder;

class Alumni2006_2007Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenure = Tenure::firstOrCreate(
            ['year' => '2006-2007'], ['name' => 'His Grace Generation',
            ]
        );

        $alumni = [
            [
                'name' => 'ABOSEDE ANISHERE',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-07-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADANIKIN OLUSOLA T.',
                'email' => null,
                'phones' => ['08039237709'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-02-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBANJO SHOLA',
                'email' => null,
                'phones' => ['08034874017'],
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-04-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEBIYI ESTHER ADEKEMI',
                'email' => null,
                'phones' => ['08038496718'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-02-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEFARAKAN ANTHONY',
                'email' => null,
                'phones' => ['08034175577'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-10-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEGOKE IDOWU A.',
                'email' => null,
                'phones' => ['08032066543'],
                'department_id' => 8,
                'gender' => 'F',
                'birth_date' => '2000-05-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEJUMO OLUWABUNMI',
                'email' => null,
                'phones' => ['08033861358'],
                'department_id' => 34,
                'gender' => 'F',
                'birth_date' => '2000-08-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEKANMBI TOPE',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-04-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADELEKAN A.O.',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-03-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEMUKOLU A.A.',
                'email' => null,
                'phones' => null,
                'department_id' => 43,
                'gender' => 'M',
                'birth_date' => '2000-03-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADERANTI ADENIRAN',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-08-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESANMI STEPHEN',
                'email' => null,
                'phones' => ['08051949577'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-06-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADESINA OLAIDE',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => null,
                'birth_date' => '2000-10-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETONA YEMISI',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-04-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADETORO JAIYEOLA MARTINS',
                'email' => null,
                'phones' => ['08056663419'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-01-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYANJU GABRIEL A.',
                'email' => null,
                'phones' => ['08035800345'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-06-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYANJU JOHNSON',
                'email' => null,
                'phones' => null,
                'department_id' => 38,
                'gender' => 'M',
                'birth_date' => '2000-09-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYELE TAIWO',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEMI BUSUYI',
                'email' => null,
                'phones' => ['08062434325'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-04-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYEYE ADEWALE',
                'email' => null,
                'phones' => null,
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-04-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADEYI ADEWALE',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-11-11',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ADIGUN DANIEL O.',
                'email' => null,
                'phones' => ['08039151934'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-09-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGUDA D. SEGUN',
                'email' => null,
                'phones' => null,
                'department_id' => 3,
                'gender' => 'M',
                'birth_date' => '2000-05-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AGUNBIADE B.',
                'email' => null,
                'phones' => ['08060223279'],
                'department_id' => 4,
                'gender' => 'M',
                'birth_date' => '2000-05-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AHIWE EVELYN',
                'email' => null,
                'phones' => ['08038466638'],
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => '2000-08-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJALA BUKOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-10-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJALA TOSIN',
                'email' => null,
                'phones' => null,
                'department_id' => 41,
                'gender' => 'F',
                'birth_date' => '2000-09-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI JEREMIAH O.',
                'email' => null,
                'phones' => ['08034630554'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-04-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJAYI O.O.',
                'email' => null,
                'phones' => ['08033952333'],
                'department_id' => 16,
                'gender' => null,
                'birth_date' => '2000-06-02',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJEWOLE J.A.',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => null,
                'birth_date' => '2000-12-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJIBADE TAYO',
                'email' => null,
                'phones' => ['08033645375'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-08-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJIBOLA TOPE',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'F',
                'birth_date' => '2000-01-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AJIM AKINYEMI',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-07-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKANDE U.E.',
                'email' => null,
                'phones' => ['08032098759'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-01-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBOWALE AKINGBOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-01-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINBOYETAN O.O.',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => null,
                'birth_date' => '2000-03-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINDAYINI W.O.',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => null,
                'birth_date' => '2000-09-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINKUOWO OMOLARA',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'F',
                'birth_date' => '2000-01-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINMAYOWA S.',
                'email' => null,
                'phones' => null,
                'department_id' => 36,
                'gender' => null,
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINMULEGAN A.',
                'email' => null,
                'phones' => null,
                'department_id' => 19,
                'gender' => null,
                'birth_date' => '2000-01-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINMUYISITAN I.W.',
                'email' => null,
                'phones' => null,
                'department_id' => 3,
                'gender' => null,
                'birth_date' => '2000-11-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKIODE OMOBOLANLE',
                'email' => null,
                'phones' => ['08035380785'],
                'department_id' => 13,
                'gender' => 'F',
                'birth_date' => '2000-02-17',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINOYE OLUGBENGA O.',
                'email' => null,
                'phones' => ['08034153929'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-08-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINSOLA ADEWOLE',
                'email' => null,
                'phones' => ['08035530836'],
                'department_id' => null,
                'gender' => 'F',
                'birth_date' => '2000-10-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AKINTUNDE TAIWO',
                'email' => null,
                'phones' => ['08036896988'],
                'department_id' => null,
                'gender' => null,
                'birth_date' => '2000-11-06',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALABI CHARLES',
                'email' => null,
                'phones' => null,
                'department_id' => 7,
                'gender' => 'M',
                'birth_date' => '2000-09-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALAGBADA ADEFEMI SAMUEL',
                'email' => null,
                'phones' => ['08035205379'],
                'department_id' => 18,
                'gender' => 'M',
                'birth_date' => '2000-05-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALAYE D.G.',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-10-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALIGBE EDWIN',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-09-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ALUBANKUDI REMI I',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-09-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AMAGBATOHEN J.',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-10-03',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ANOZIE CHUKWUMA',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => 'F',
                'birth_date' => '2000-03-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ARAOYINBO ROSEMARY',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => 'F',
                'birth_date' => '2000-09-23',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AROWOLO J. ISAAC',
                'email' => null,
                'phones' => ['08032523465'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-09-09',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASENOJUAN F.N.',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => 'F',
                'birth_date' => '2000-04-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ASHIEFO BASIL A.',
                'email' => null,
                'phones' => null,
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-08-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ATANDARE ROTIMI J.',
                'email' => null,
                'phones' => ['08033834549', '08053443153'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-11-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOLUSI O.O.',
                'email' => null,
                'phones' => null,
                'department_id' => 43,
                'gender' => 'F',
                'birth_date' => '2000-08-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AWOSEMO MOTUNRAYO C',
                'email' => null,
                'phones' => ['08035768018'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-01-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYILARAN ABIMBOLA',
                'email' => null,
                'phones' => ['08034481254'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-07-31',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AYOWELE OLUWASOLA',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-04-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'AZUBUIKE ABIODUN',
                'email' => null,
                'phones' => null,
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-01-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BABALOLA OLUWASEUN K.',
                'email' => null,
                'phones' => ['08028199150'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-05-30',
                'unit' => 'President\'s Unit',
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAYODE F.T.',
                'email' => null,
                'phones' => null,
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-10-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAYODE OLAKUNLE O.',
                'email' => null,
                'phones' => ['08029008551'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-10-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'BAYODE OLALEKAN E.',
                'email' => null,
                'phones' => null,
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-01-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DADA ODUNAYO',
                'email' => null,
                'phones' => ['08035289382'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-12-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'DEMEHIN O.O.',
                'email' => null,
                'phones' => null,
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-08-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EKUNOLA BLESSING',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-06-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EMOUSIUKO B. MIRACLE',
                'email' => null,
                'phones' => ['08030794064'],
                'department_id' => 37,
                'gender' => null,
                'birth_date' => '2000-01-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'EMUOSO CHRISTOPHER',
                'email' => null,
                'phones' => ['08032089201'],
                'department_id' => 34,
                'gender' => 'M',
                'birth_date' => '2000-01-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FABUSIWA MERCY',
                'email' => null,
                'phones' => null,
                'department_id' => 36,
                'gender' => 'F',
                'birth_date' => '2000-04-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FABODE FOLAKEMI',
                'email' => null,
                'phones' => ['08035855478'],
                'department_id' => 3,
                'gender' => 'F',
                'birth_date' => '2000-11-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FADAIRO JUMOKE',
                'email' => null,
                'phones' => ['08025530746'],
                'department_id' => 43,
                'gender' => 'F',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FADIPE SANYA',
                'email' => null,
                'phones' => null,
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-06-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAGBEMI ADEMOLA',
                'email' => null,
                'phones' => ['08051110880'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-07-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FAGBEMI OLUFUNKE O.',
                'email' => null,
                'phones' => ['08062305289'],
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALASE OPEMIPO_OLUWA',
                'email' => null,
                'phones' => ['08054153309'],
                'department_id' => 30,
                'gender' => 'F',
                'birth_date' => '2000-09-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FALOPE OLAJIDE O.',
                'email' => null,
                'phones' => ['08052807367'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-12-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'FARAYIBI PETER KAYODE',
                'email' => null,
                'phones' => ['08025617858'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'GANIYU LANRE',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-05-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IDEHEN DAVE',
                'email' => null,
                'phones' => ['08034113371'],
                'department_id' => 16,
                'gender' => 'M',
                'birth_date' => '2000-12-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'IPINSANMI DANIEL',
                'email' => null,
                'phones' => ['08034652714'],
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-11-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'KAYODE T.G.',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => '2000-04-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MAKINWA TUNDE',
                'email' => null,
                'phones' => ['08038458235'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-03-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'MORIYOMI KIKELOMO',
                'email' => null,
                'phones' => null,
                'department_id' => 13,
                'gender' => 'F',
                'birth_date' => '2000-12-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'NURUDEEN TUNDE',
                'email' => null,
                'phones' => ['08034121921'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-07-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBADELE TUNDE',
                'email' => null,
                'phones' => ['08027284078'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-12-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OBISESAN ADERONKE',
                'email' => null,
                'phones' => null,
                'department_id' => 7,
                'gender' => 'F',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODANYE BUNMI',
                'email' => null,
                'phones' => ['08028966406'],
                'department_id' => null,
                'gender' => 'F',
                'birth_date' => '2000-04-08',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODUBENA WALE',
                'email' => null,
                'phones' => ['08038575181'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-06-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ODUNIYI SAMUEL',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLASUNTANMI TUNJI S.',
                'email' => null,
                'phones' => ['08033175715'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-04-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAWEPO OLANREWAJU W.',
                'email' => null,
                'phones' => ['08062709040'],
                'department_id' => 19,
                'gender' => 'M',
                'birth_date' => '2000-11-26',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNBOYE SEYI',
                'email' => null,
                'phones' => null,
                'department_id' => 4,
                'gender' => 'M',
                'birth_date' => '2000-04-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNDARE PAUL O.',
                'email' => null,
                'phones' => ['08053363076'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-05-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNGBEMI YETUNDE',
                'email' => null,
                'phones' => null,
                'department_id' => 32,
                'gender' => 'F',
                'birth_date' => '2000-01-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNGBENRO STEPHEN',
                'email' => null,
                'phones' => ['08022011225'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-03-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNLEYE S.T.',
                'email' => null,
                'phones' => null,
                'department_id' => 19,
                'gender' => 'F',
                'birth_date' => '2000-12-12',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNMUYIWA ELIZABETH I.',
                'email' => null,
                'phones' => ['08029541082'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-03-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNWO MOSUNMOLA',
                'email' => null,
                'phones' => ['08035781878'],
                'department_id' => 8,
                'gender' => 'F',
                'birth_date' => '2000-06-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OGUNYANKINNU BISI J.',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'F',
                'birth_date' => '2000-04-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OJO BUNMI',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-03-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKE BUKOLA',
                'email' => null,
                'phones' => ['08044181347'],
                'department_id' => null,
                'gender' => 'F',
                'birth_date' => '2000-11-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKE OLAWALE',
                'email' => null,
                'phones' => null,
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-03-14',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKOH U.C.',
                'email' => null,
                'phones' => null,
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OKORIE SAMSON',
                'email' => null,
                'phones' => ['08056376405'],
                'department_id' => 30,
                'gender' => 'M',
                'birth_date' => '2000-12-25',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLALEYE OLAJUMOKE',
                'email' => null,
                'phones' => ['08034829019'],
                'department_id' => 4,
                'gender' => 'F',
                'birth_date' => '2000-04-18',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLANREWAJU TUNDE',
                'email' => null,
                'phones' => null,
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-04-04',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLAOMI MAYOWA',
                'email' => null,
                'phones' => ['08033650209'],
                'department_id' => 41,
                'gender' => 'M',
                'birth_date' => '2000-02-05',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLANIYAN JOHN A.',
                'email' => null,
                'phones' => null,
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLATUNYA D.E.',
                'email' => null,
                'phones' => ['08038617648'],
                'department_id' => 13,
                'gender' => 'M',
                'birth_date' => '2000-12-15',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLOGUNAGBA JOHN',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-09-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLORUNDARE BANJI',
                'email' => null,
                'phones' => null,
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => '2000-06-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUBIYI DIPO',
                'email' => null,
                'phones' => null,
                'department_id' => 3,
                'gender' => 'M',
                'birth_date' => '2000-05-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUFOJUDE B.O.',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-05-24',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUPONA FUNMI',
                'email' => null,
                'phones' => ['08060914303'],
                'department_id' => 13,
                'gender' => 'F',
                'birth_date' => '2000-09-20',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWOLE TEMIDAYO',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'M',
                'birth_date' => '2000-07-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUWABUNMI VICTOR',
                'email' => null,
                'phones' => ['08034274054'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-10-30',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OLUYEDE BUKOLA',
                'email' => null,
                'phones' => ['08036800670'],
                'department_id' => 10,
                'gender' => 'F',
                'birth_date' => '2000-01-13',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOLE LEKAN MICHAEL',
                'email' => null,
                'phones' => ['08026313152'],
                'department_id' => 26,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOPARIOLA JANET',
                'email' => null,
                'phones' => null,
                'department_id' => 18,
                'gender' => 'F',
                'birth_date' => '2000-02-16',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OMOSUYI A.I.',
                'email' => null,
                'phones' => ['08034288578'],
                'department_id' => 11,
                'gender' => 'M',
                'birth_date' => '2000-05-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONABOWU F. TOYIN',
                'email' => null,
                'phones' => ['08028991606'],
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-07-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ONI TUNJI',
                'email' => null,
                'phones' => ['08022506153'],
                'department_id' => 8,
                'gender' => 'M',
                'birth_date' => '2000-10-10',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ORIMOLOYE KAYODE',
                'email' => null,
                'phones' => ['08028613325'],
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => '2000-01-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OWOEYO F. IFEOLUWAPO',
                'email' => null,
                'phones' => ['08035614378'],
                'department_id' => 38,
                'gender' => null,
                'birth_date' => '2000-10-21',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEDELE CHRISTIANAH',
                'email' => null,
                'phones' => null,
                'department_id' => 40,
                'gender' => 'F',
                'birth_date' => '2000-03-19',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OYEDELE TITILOPEMIOLUWA E.',
                'email' => null,
                'phones' => ['08052370892'],
                'department_id' => 37,
                'gender' => 'F',
                'birth_date' => '2000-02-01',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'OSHIOGBE I.F.',
                'email' => null,
                'phones' => null,
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => '2000-02-07',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'PRINCE UBONG U.B.',
                'email' => null,
                'phones' => ['08028979524'],
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-06-22',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ROTIBA O. DAVID',
                'email' => null,
                'phones' => ['08034136496'],
                'department_id' => 44,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'ROTIMI OLUWASANMI',
                'email' => null,
                'phones' => ['08029407720'],
                'department_id' => null,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SHAREMI OLUJEJE A.',
                'email' => null,
                'phones' => ['08038353771'],
                'department_id' => 10,
                'gender' => 'M',
                'birth_date' => '2000-02-28',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'SHOGBANMU BAYO',
                'email' => null,
                'phones' => null,
                'department_id' => 17,
                'gender' => 'M',
                'birth_date' => null,
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'WOLE',
                'email' => null,
                'phones' => null,
                'department_id' => 37,
                'gender' => 'M',
                'birth_date' => '2000-07-27',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
            [
                'name' => 'YUSUF TEMIDAYO',
                'email' => null,
                'phones' => null,
                'department_id' => 25,
                'gender' => 'M',
                'birth_date' => '2000-07-29',
                'unit' => null,
                'state' => null,
                'address' => null,
            ],
        ];

        foreach ($alumni as $data) {
            if (empty($data['name'])) {
                continue;
            }

            Alumnus::updateOrCreate(
                ['name' => $data['name'], 'tenure_id' => $tenure->id],
                array_merge($data, ['tenure_id' => $tenure->id])
            );
        }

        $this->command->info("Seeded {$tenure->year} alumni: " . count($alumni) . " records");
    }
}
